### ISSUE TITLE
optionally save/reload an HS address and a filename, to use multiple times.

### ISSUE THREAD

**Issue by vecna** [micahflee/onionshare#100]
Two use case for this feature:

  * someone has to turn off the box, and close onionshare before someother has download yet. the users need to re-offer the same URL after the reboot, because has already communicated the previous address to share the file.

  * someone has distributed an onionshare URL, and the content changes periodically, without having to communicate a new URL.

**Comment by micahflee** [comment]
I don't think this is needed, it will make the UI way too complex.
