### ISSUE TITLE
***Multiple Url Support

### ISSUE THREAD

**Issue by Incredible-BB** [micahflee/onionshare#1013]
This platform is amazing!! This is not an issue but a friendly STRONGLY recommended feature to implement!

I would like to have the ability to share links to multiple files separately. Like my own file hosting site that issues links to multiple separate files.

Example: 
file1 = URL: 1234.onion
file2 = URL: 4321.onion

But both/all files are accessible as long as my computer/server is running, and the sharing button is turned on.

Thank you hope to see it soon!!

**Comment by trymeouteh** [comment]
It will be cool to be able to share multiple files under different URLs at once. If you want to share file1 with your Dad and file2 with a friend and share file3 with your boss you can all at once!

**Comment by mig5** [comment]
You will be able to do this with the new 'Tabs' mode that is coming in OnionShare 2.3. You can start as many 'Share' mode tabs as you like, and they can each share the same or different files, under a unique onion address each.
