### ISSUE TITLE
Provide some way to hide the Tor connection prefs in the Settings dialog

### ISSUE THREAD

**Issue by intrigeri** [micahflee/onionshare#1014]
Hi! In the context of Tails, we pre-configure OnionShare to use the system instance of tor. We need to do this because a tor process started by OnionShare (as the `amesia` user) would not be allowed to connect to the Tor network: our firewall would forbid it; and in any case, it's nice that bridges settings already configured by the user at the system level are automatically used for OnionShare connections.

But now we're facing a UX problem since recent versions of OnionShare expose Tor connection prefs in the _Settings_ dialog: as my colleague sajolida wrote on https://redmine.tails.boum.org/code/issues/16913, "in the context of Tails, these options are, at best, not useful, probably confusing, and possibly harmful if changing them can lead to a broken OnionShare". I suspect Whonix is affected by similar problems as well.

Could you please add a way for Tails to hide these prefs?

For example, if the `LOCK_DOWN_TOR_CONNECTION_SETTINGS` environment variable is set to 1, OnionShare would use whatever Tor connection settings are set in its configuration file, and would hide the corresponding prefs in the _Settings_ dialog.

**Comment by micahflee** [comment]
Thanks @intrigeri, I just made PR #1017 to solve this. Once this issue is merged and released, Tails can set `ONIONSHARE_HIDE_TOR_SETTINGS` to `1`, and the Tor connection settings will be hidden.

**Comment by intrigeri** [comment]
Micah Lee:
> Thanks @intrigeri, I just made PR #1017 to solve this. Once this issue is merged and released, Tails can set `ONIONSHARE_HIDE_TOR_SETTINGS` to `1`, and the Tor connection settings will be hidden.

Awesome, thanks a lot for the quick fix! :)))
