### ISSUE TITLE
use Unix socket for SocksPort

### ISSUE THREAD

**Issue by pabs3** [micahflee/onionshare#1015]
To prevent other users on the system from being able to use onionshare's Tor instance, it might be a good idea to use a Unix socket for the torrc SocksPort option:

SocksPort unix:/home/pabs/.config/onionshare/tmpktvcfl7s/

**Comment by mig5** [comment]
Thanks - actually, I'm gonna close this because it's a duplicate of #1006 , but I'll quote you there as it's another good reason for this idea.
