### ISSUE TITLE
Could not connect to the Tor controller. 

### ISSUE THREAD

**Issue by vivape** [micahflee/onionshare#1023]
Onion share doesn't find running in the background. 
![image](https://user-images.githubusercontent.com/30419879/64751540-d0b1d400-d4f2-11e9-800d-6629e12770e6.png)

What is going on?

**Comment by micahflee** [comment]
What happens when you go into settings and under "How should OnionShare connect to Tor?" choose "Use the Tor version built into OnionShare". Can you try that and post a screenshot if it fails?

**Comment by vivape** [comment]
> What happens when you go into settings and under "How should OnionShare connect to Tor?" choose "Use the Tor version built into OnionShare". Can you try that and post a screenshot if it fails?

Hi, @micahflee. I have tried all that options but that ones related to ports. None of them works.

**Comment by micahflee** [comment]
Can you show me the error you're getting when it fails?

**Comment by vivape** [comment]
@micahflee for sure. Here it is:

![Capture](https://user-images.githubusercontent.com/30419879/65381714-77edf280-dccd-11e9-9ca4-a8f5a29be5d6.JPG)

**Comment by nstorm1** [comment]
I am raising the question.
just like a colleague I checked all possible solutions.
I get the same message, what else can I do?
