### ISSUE TITLE
Feature Request: Password protected files & self destruct files

### ISSUE THREAD

**Issue by trymeouteh** [micahflee/onionshare#1040]
I think by adding the following features this can increase the security when sharing files.

Password protected file - You will require a password to download the file.

One-Time passwords - You can create a one time password to access the file. Once the password is used and the file has been downloaded that password will expire and cannot be used to access the file.

Self Destruct - The link will expire and stop sharing after a certain date and time or in X amounts of minutes, hours or days.

**Comment by mig5** [comment]
Hi,

> Password protected file - You will require a password to download the file.

OnionShare 2.2 (soon to be released) uses HTTP basic auth (username and password) to access the share/download files.

> 
> One-Time passwords - You can create a one time password to access the file. Once the password is used and the file has been downloaded that password will expire and cannot be used to access the file.

By default, the share stops automatically after the first download. This combined with password auth (as above, but even with the previous /slug solution) should be sufficient.

> Self Destruct - The link will expire and stop sharing after a certain date and time or in X amounts of minutes, hours or days.

This feature already exists, it's called 'Auto-stop timer' and can be enabled in the Settings, and a date/time configured for each share.
