### ISSUE TITLE
Restore previous sharing after closing/starting up

### ISSUE THREAD

**Issue by trymeouteh** [micahflee/onionshare#1043]
If your in the middle of sharing a file and you close onionshare or shutdown your computer it would be nice to have a setting to choose to have it so when you statup up your computer and onionshare again it will continue sharing the files under the same URL.

**Comment by mig5** [comment]
There is such a setting, it's called 'Persistent mode'. You'll have to choose the same files to share again, but the URL will be the same as the last time.
