### ISSUE TITLE
Onionshare can not connect to Torbrowser on macOS Catalina 10.15

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#1045]
While Torbrowser is running and I try to connect to it in onionshare it always fails with this error.
`[Oct 07 2019 10:55:59] TorConnectionThread.run: caught exception: Could not connect to the Tor controller. Is Tor Browser (available from torproject.org) running in the background?
`
macOS Catalina 10.15 (19A583) was released on 10-7-19
@micahflee 
@mig5

**Comment by mig5** [comment]
I don't reproduce it on macOS 10.14.6. So I guess it's some sandbox issue...

**Comment by micahflee** [comment]
I'm upgrading to macOS Catalina 10.15 to see if I can reproduce now...

**Comment by micahflee** [comment]
This is OnionShare 2.1, the current stable version and not what's in the develop branch, right? And you're talking about configuring OnionShare to "Attempt auto-configuration with Tor Browser", not "Use the Tor version built into OnionShare"?

**Comment by mig5** [comment]
It works for me on Catalina 10.15 using Tor Browser as the tor connection method, on OnionShare 2.2-dev

**Comment by micahflee** [comment]
It also works for me on Catalina using Tor Browser, and using bundled Tor, in version 2.1

**Comment by Baccount** [comment]
I’m not sure why it doesn’t work on my end, I will try testing it more.

**Comment by Baccount** [comment]
When Torbrowser.app is located on the desktop, onionshare can not connect to it. But if I move Torbrowser.app to the Applications folder and reopen it there is no problems.

**Comment by nerdspar** [comment]
@Baccount this likely is more of a tor project issue than a onionshare i feel.  we could submit a patch with some sort of warning but it doesn't seem super productive.

i'll see if i can submit a doc change to the torproject site to deal with this.
