### ISSUE TITLE
Ubuntu install error: python3-flask-httpauth dependency "not installable"

### ISSUE THREAD

**Issue by donmemorario** [micahflee/onionshare#1052]
sudo apt install -y onionshare

Not able to install some packages. This may mean that you have requested an impossible situation or, if you are using the distribution unstable that some required packages have not yet been created or taken from "Incoming". The following information may help to resolve the situation:

The following packages have unmet dependencies: onionshare : Depends: python3-flask-httpauth, but it is not installable E: failed to correct problems, you have held broken packages.

**Comment by pantraining** [comment]
same on xubuntu 18.04

**Comment by sts10** [comment]
Same on Kubuntu 18.04.3 here. 

We might want to change the title of this issue to something a bit more descriptive to the specific error, like:

> Ubuntu install error: python3-flask-httpauth dependency "not installable"

**Comment by donmemorario** [comment]
> Same on Kubuntu 18.04.3 here.
> 
> We might want to change the title of this issue to something a bit more descriptive to the specific error, like: "Ubuntu install error: python3-flask-httpauth dependency 'not installable'"

Great!

**Comment by mig5** [comment]
> We might want to change the title of this issue to something a bit more descriptive to the specific error, like: "Ubuntu install error: python3-flask-httpauth dependency 'not installable'"

Done!

Please note there is a workaround for these versions of Ubuntu/Debian variants that lack that package:

1) Clone the git repository (and optionally checkout the tag v.2.2)
2) Read the `BUILD.md` to install the packages directly (sans the httpauth package):
`sudo apt install -y python3-flask python3-stem python3-pyqt5 python3-crypto python3-socks python-nautilus tor obfs4proxy python3-pytest build-essential fakeroot python3-all python3-stdeb dh-python python3-distutils`
3) Use pip to install the python3-flask-httpauth package:
`sudo pip3 install flask-httpauth`
4) Run OnionShare via the `dev_scripts` scripts e.g `./dev_scripts/onionshare-gui`

**Comment by mig5** [comment]
I'm going to close this since:

1) we can't do anything to change those Ubuntu/Debian versions (it was a known issue in making this release)
2) there is a workaround (as above)
3) using flatpack or snaps as a long term uniformity fix for Linux packaging of OnionShare, is already on the radar and we have issues already for those.

Sorry for the inconvenience! I encourage all users affected to use the workaround above - there is functionally no difference between installing the deb vs running via the `dev_scripts` scripts (which are only named as they are useful helpers for the developers to run OnionShare quickly without installing a packaged version - but it's the same OnionShare experience)

**Comment by sts10** [comment]
Thanks, chief. 

Unfortunately when I follow your steps, when I run `./dev_scripts/onionshare-gui` I get the following error:

```
Traceback (most recent call last):
  File "./dev_scripts/onionshare-gui", line 27, in <module>
    import onionshare_gui
  File "/home/sschlinkert/code/onionshare/onionshare_gui/__init__.py", line 26, in <module>
    from .widgets import Alert
  File "/home/sschlinkert/code/onionshare/onionshare_gui/widgets.py", line 20, in <module>
    from PyQt5 import QtCore, QtWidgets, QtGui
ModuleNotFoundError: No module named 'PyQt5'
```

Whether I run on the latest commit or checkout tags/v2.2 I get the same error (above). Running `sudo apt install python3-pyqt5` on its own seems to indicate that that package installed just fine. 

Maybe something to do with my admittedly wonky Python development set up? Other folks: feel free to give me a thumbs down if you're NOT getting my error!

**Comment by mig5** [comment]
Ahh, that sounds unfortunate. I haven't tried this myself, but per the BUILD.md, maybe you'll have better luck if you use a virtualenv first (especially if you might have strange Python dependency/version clash issues on your system):

```
python3 -m venv venv
. venv/bin/activate
```

Then perhaps use pip to install *all* dependencies within that virtualenv:

```
pip3 install -r install/requirements.txt
```

**Comment by sts10** [comment]
Success! 

For the record, I think these are the commands I needed to run:
```
git clone https://github.com/micahflee/onionshare.git
cd onionshare
git checkout tags/v2.2
python3 -m venv venv
. venv/bin/activate
pip3 install -r install/requirements.txt
./dev_scripts/onionshare-gui
```

**Comment by 0xh4di** [comment]
Just ignore `python3-flask-httpauth` in first step, and run `apt install -y python3-flask python3-stem python3-pyqt5 python3-crypto python3-socks python-nautilus tor obfs4proxy python3-pytest build-essential fakeroot python3-all python3-stdeb dh-python python3-distutils` .

Then install `sudo apt install python3-pip` and after that run `sudo pip3 install flask_httpauth`

Finally when you run `./dev_scripts/onionshare` you got the result!

> OnionShare 2.2 | https://onionshare.org/
usage: onionshare [-h] [--local-only] [--stay-open] [--auto-start-timer <int>]
                  [--auto-stop-timer <int>] [--connect-timeout <int>]
                  [--stealth] [--receive] [--website] [--config config] [-v]
                  [filename [filename ...]]
> positional arguments:
  filename                  List of files or folders to share
> optional arguments:
  -h, --help                show this help message and exit
  --local-only              Don't use Tor (only for development)
  --stay-open               Continue sharing after files have been sent
  --auto-start-timer <int>  Schedule this share to start N seconds from now
  --auto-stop-timer <int>   Stop sharing after a given amount of seconds
  --connect-timeout <int>   Give up connecting to Tor after a given amount of
                            seconds (default: 120)
  --stealth                 Use client authorization (advanced)
  --receive                 Receive shares instead of sending them
  --website                 Publish a static website
  --config config           Custom JSON config file location (optional)
  -v, --verbose             Log OnionShare errors to stdout, and web errors to
                            disk

**Comment by Capitalmind** [comment]
> > We might want to change the title of this issue to something a bit more descriptive to the specific error, like: "Ubuntu install error: python3-flask-httpauth dependency 'not installable'"
> 
> Done!
> 
> Please note there is a workaround for these versions of Ubuntu/Debian variants that lack that package:
> 
> 1. Clone the git repository (and optionally checkout the tag v.2.2)
> 2. Read the `BUILD.md` to install the packages directly (sans the httpauth package):
>    `sudo apt install -y python3-flask python3-stem python3-pyqt5 python3-crypto python3-socks python-nautilus tor obfs4proxy python3-pytest build-essential fakeroot python3-all python3-stdeb dh-python python3-distutils`
> 3. Use pip to install the python3-flask-httpauth package:
>    `sudo pip3 install flask-httpauth`
> 4. Run OnionShare via the `dev_scripts` scripts e.g `./dev_scripts/onionshare-gui`

$sudo pip3 install flask-httpauth
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 10, in <module>
    sys.exit(main())
TypeError: 'module' object is not callable

**Comment by Bondarz** [comment]
> I downloaded the .deb from here https://ubuntu.pkgs.org/19.04/ubuntu-universe-amd64/python3-flask-httpauth_3.2.4-3_all.deb.html which worked on my system to remedy this. (Linux Mint 19.2)

thanks, after installing this package i could install it with "sudo apt-get install onionshare" the program.

**Comment by eloquence** [comment]
The instructions on https://onionshare.org/ still advertise the Ubuntu packages, even though these do not appear to be installable on Bionic, which is an LTS release. Could https://onionshare.org/ be updated to reflect the current recommendation/workaround?

**Comment by georgeowell** [comment]
Hi folks, I also came across this issue and accidentally opened a duplicate:
https://github.com/micahflee/onionshare/issues/1129

I don't see why this is a closed issue. There is no note on the website warning people about this problem.

I bet there are so many non-technical folks who have come across this and just given up. 

Don't you think we should at least warn people that the latest version of Onionshare it doesn't run on Ubuntu 18.04 and they should just install the version from the repos?

**Comment by mig5** [comment]
It's in our documentation.

https://github.com/micahflee/onionshare/wiki/How-Do-I-Install-Onionshare#problem-installing-due-to-python3-flask-httpauth-package-dependency

I'll re-open in case Micah wants to put something on the website (for people who don't read documentation)

**Comment by georgeowell** [comment]
@mig5 thanks for doing that!:heart: It just seems like a bit of a easy omission to solve. 

I would have opened an issue of the [website repo](https://github.com/micahflee/onionshare-website) but it has issues disabled.

**Comment by lupa18** [comment]
> It's in our documentation.
> 
> https://github.com/micahflee/onionshare/wiki/How-Do-I-Install-Onionshare#problem-installing-due-to-python3-flask-httpauth-package-dependency
> 
> I'll re-open in case Micah wants to put something on the website (for people who don't read documentation)

Sorry @mig5 , 

People access to the website and clearly says install "If you are using Ubuntu, open a terminal and type... " and you got a broken installation. I think someone should fix those wrong steps. 

Not all people installing software are expert, nor need to read documentation while steps and clear and simple (but not working).

**Comment by avimanyu786** [comment]
The following steps worked for me to resolve the error:

1. [Download](http://archive.ubuntu.com/ubuntu/pool/universe/p/python-flask-httpauth/python3-flask-httpauth_3.2.4-3.1_all.deb) the Ubuntu 20.04 based `python3-flask-httpauth` package.
2. Open a Terminal window on Ubuntu 18.04
3. Assuming the downloaded package is in the same directory, use the following command to install it:
`dpkg -i python3-flask-httpauth_3.2.4-3.1_all.deb`
4. Now you can install `onionshare` without the error.

**Comment by msevilla00** [comment]
> > I downloaded the .deb from here https://ubuntu.pkgs.org/19.04/ubuntu-universe-amd64/python3-flask-httpauth_3.2.4-3_all.deb.html which worked on my system to remedy this. (Linux Mint 19.2)
> 
> thanks, after installing this package i could install it with "sudo apt-get install onionshare" the program.

Link is broken. I used this:

[http://ftp.br.debian.org/debian/pool/main/p/python-flask-httpauth/python3-flask-httpauth_3.2.4-3_all.deb](http://ftp.br.debian.org/debian/pool/main/p/python-flask-httpauth/python3-flask-httpauth_3.2.4-3_all.deb)

**Comment by u451f** [comment]
The package exists in Debian repositories (https://tracker.debian.org/pkg/python-flask-httpauth) and Ubuntu repositories (https://launchpad.net/ubuntu/+source/python-flask-httpauth) for Xenial, Beaver, Fossa, Gorilla, and Hippo. You can find the latest binaries for Debian here: https://packages.debian.org/sid/all/python3-flask-httpauth/download

**Comment by micahflee** [comment]
This isn't an issue now that OnionShare is distributed via snap and flatpak
