### ISSUE TITLE
Add Onionshare use as a reverse proxy on a url website as cloudflare does

### ISSUE THREAD

**Issue by ASmith-** [micahflee/onionshare#1055]
Add an Onionshare enhancement of an reverse proxy on a url website as Cloudflare does.

With the first step of enabling a Hidden Tor Service Website via Onionshare, a nice enhancement would be the users optional ability to enter a existing https://domain.me url to the Onionshare settings, which would then create a Tor Networked reverse proxy to that website.

**Comment by micahflee** [comment]
This is an interesting idea but I think it would be quite hard to implement in practice if we want to do things like rewrite URLs inside the HTML so they also use the onion site. A better dedicated piece of software for this is EOTK: https://github.com/alecmuffett/eotk
