### ISSUE TITLE
self hosted OnionShare

### ISSUE THREAD

**Issue by 0xh4di** [micahflee/onionshare#1061]
Hi,

How can I install self hosted OnionShare on my Ubuntu box?
Is it possible to install OnionShare on private server like Owncloud ,etc..?

**Comment by micahflee** [comment]
You can install OnionShare in Ubuntu using the PPA, like this:

```
sudo add-apt-repository ppa:micahflee/ppa
sudo apt update
sudo apt install -y onionshare
```

Then, assuming your talking about a headless server, you can ssh into your Ubuntu server and use the OnionShare CLI interface to use it, e.g.:

```
onionshare ~/files_to_share
```
