### ISSUE TITLE
Broken dependancies

### ISSUE THREAD

**Issue by stemy2** [micahflee/onionshare#1072]
Hello,

I can't install it, the dependancies «python3-flask-httpauth» and «python3-distutils» are missing.

**Comment by sts10** [comment]
These seems similar to #1052

**Comment by mig5** [comment]
Yes, please see this section of the wiki. You may need to do a similar thing for the python3-distutils dependency...

https://github.com/micahflee/onionshare/wiki/How-Do-I-Install-Onionshare#problem-installing-due-to-python3-flask-httpauth-package-dependency
