### ISSUE TITLE
Add where to report issues

### ISSUE THREAD

**Issue by ghost** [micahflee/onionshare#1083]
Please link to where to report issues in the Preferences of Onionshare.

**Comment by mig5** [comment]
IMHO adding more such sections to the Settings dialog would clutter it too much. 

The Help button already takes the user to https://github.com/micahflee/onionshare/wiki/Getting-Help which has a clear section (with link) to the Issue Queue. 

Maybe a hover text could appear over the button that reads 'Get help or raise an issue'.
