### ISSUE TITLE
File name with "æ" changes to "+ª"

### ISSUE THREAD

**Issue by scootergrisen** [micahflee/onionshare#1088]
I took screenshots on one system (GNOME) using file name with "Skærmbillede[...]".
Then shared the files in OnionShare to Tor Browser in Windows and the file names ended up being "Sk+ªrmbillede[...]".

"æ" was changed to "+ª".

It would be nicer if the file names was preserved.

**Comment by comradekingu** [comment]
Does the tool use OCR to save data? Try it in a different screenshot tool?

**Comment by scootergrisen** [comment]
Maybe its the compression to a zip file that changes the filnames.
The file names look fine in tor browser but after clicking Download Files to get the zip file the file names are incorrect.
Seems there is always created a zip file regardless of just sharing one file or more files and i can't click to download the files individually.

**Comment by comradekingu** [comment]
Ah, the filename. I got that wrong. Seems more plausible, and I imagine because Gnome has file-picker issues (it does;), the Tor browser isn't in Danish(?), OnionShare does some sanitation, or the Windows system can't support UTF-8, which is more unlikely. Is the "æ" in the actual screenshot filename to begin with?

**Comment by scootergrisen** [comment]
Yes Tor Browser is in danish.
Yes æ is in the filename originally.
I also tried making some files on my own and it's the same.
Are there some way to disable compression to a zip file?
So i can transfer the fil without using a zip file.

**Comment by comradekingu** [comment]
@Kcchouette Worked fine sharing tekstæbøbå.txt to myself on
OnionShare 2.2
Tor Browser 10.0.13 (based on Mozilla Firefox 78.8.0esr) (64-bit)
LXQt

**Comment by scootergrisen** [comment]
Seems like the problem is there only when i use Windows 7 builtin unzipper/browser.
If i use 7-Zip the problem is not there.

If i use 2.3.1 and share a single file the single file will not be zipped and the problem is not there because it seems to do with the zip file.

I guess if Windows 7 is not suppose to be supported we can close this.
