### ISSUE TITLE
Generated link doesnt work

### ISSUE THREAD

**Issue by zenoob1974** [micahflee/onionshare#1097]
Hi,

On Whonix , generated links send always to "Unable to connect" onion page ...
Is it a known issue ? or maybe i didn't configure onionshare correctly

any help would welcome

thx

**Comment by mig5** [comment]
Hi,

Can you clarify if you are running OnionShare within Whonix as well, or elsewhere?

Can you try to access it via Tor Browser on something other than Whonix (to rule out a Whonix issue)?
