### ISSUE TITLE
[Solved] "Unable to detect a web browser..."

### ISSUE THREAD

**Issue by imstanz** [micahflee/onionshare#1100]
Just installed 2.2 on a minimal custom, Devuan beowulf 64bit system.

Using terminal:` $ ./dev_scripts/onionshare-gui`, all starts nicely.

I open "Settings", click on any highlighted "What's this?", shows in terminal:
> Unable to detect a web browser to launch 'https://github.com/micahflee/onionshare/wiki/Public-Mode'

Where would I edit, to input Palemoon Web Browser?

Also noticed, the "onionshare.json" file, was not created, till I clicked "Save", in "Settings".

**Comment by mig5** [comment]
Hi,

> Where would I edit, to input Palemoon Web Browser?

You could try https://wiki.debian.org/DefaultWebBrowser

```
sudo update-alternatives --config x-www-browser
```

Let us know if that solves the issue.

> Also noticed, the "onionshare.json" file, was not created, till I clicked "Save", in "Settings".

Yep, not a bug, this is expected. Default settings are loaded without requiring the json file, until custom settings are set, or til you explicitly save the Settings dialog.

**Comment by imstanz** [comment]
Greetings,
I'm running the Openbox desktop, but the link info did help confirm
x-www-browser - is pointing to /usr/bin/palemoon.

I've installed the .deb, following the instructions, which gives a .desktop file for my menu launcher...very helpful!

But still, not results from clicking "What's this?", on any choices.

This may be my issue - being a custom minimal build?

**Comment by mig5** [comment]
Hmm, yes it does sound a bit unique to your setup. I found this link, not sure if it helps you (it looks to suggest the same thing I did):

https://forum.palemoon.org/viewtopic.php?t=18197

OnionShare is a PyQT app, so the way we are doing those links is using the native QT functions such as `openUrl` which ensure it works across 'typical' Linux, Windows, and MacOS: https://doc.qt.io/qt-5/qdesktopservices.html#openUrl

I don't think we can do anything unique for your case, you may need to reach out on the Palemoon forum or Devuan's, to get any tips? If you find a way, we'll gladly add something to our wiki as there are/will be probably other users with custom setups.

**Comment by imstanz** [comment]
@mig5 - Thanks for this help and those links!!
One poster in PM post, is running similar setup and I'm good with those browser settings.
And I only have Palemoon in x-www - and set to "auto".
I do have Tor Browser installed - differently and ok with it.

The qt info, just hurt my head... LoL...sry

_Last chance?:_ The debian wiki mentioned "xdg-utils",  which I know I don't have installed - on purpose.
So I will install it and see if it does the job!

I'd like to include onionshare 2.2 with my distro release -- but,
this needs to work - for users (and just because onionshare is
an awesome tool) !
Back to comment soon...

**Comment by imstanz** [comment]
$ sudo apt install xdg-utils --no-install-recommends

$ sudo xdg-settings get default-web-browser
spacefm.desktop
LoL - a reason I don't install this!

$ sudo xdg-settings set default-web-browser palemoon.desktop

$ sudo xdg-settings get default-web-browser
palemoon.desktop

I'm sharing a "Publish Website" right now, but wanna try this...
be back..

**Comment by imstanz** [comment]
Well I'm stumped! Even with the settings/results above -
Now, it opens spacefm (file manager) and attempts to mount
the url with this error at the end:
`unknown filesystem type 'davfs'`  ...onionshare code? format?

**Comment by imstanz** [comment]
LoL...I still stumped! Rebooted with same result.
Ran again: `xdg-settings set default-web-browser palemoon.desktop`
No sudo..
And it worked!! Every one I clicked on - worked!
