### ISSUE TITLE
How to change /tmp directory?

### ISSUE THREAD

**Issue by microDM** [micahflee/onionshare#1101]
I want to share biggere files than my /tmp directory. Every time I run onionshare my /tmp gets full. I know somwhere in config file I can change it. But I am unable to find which argument I should give?

**Comment by kpcyrd** [comment]
Maybe onionshare should use /var/tmp instead, which is usually backed by disk instead of being limited by available ram.

**Comment by mig5** [comment]
Right now, unfortunately there's no way to change the temporary directory. This is something we want to add per #366 to make OnionShare more 'portable' (e.g run it entirely on a USB stick), I'm going to close this just to avoid the duplicate discussion.

Unfortunately there is no quick fix for this. We are using Python's `tempfile` module to create the temporary files in the operating system's temp drive, there is no configuration option to override it.
