### ISSUE TITLE
OnionShare issues

### ISSUE THREAD

**Issue by pokemochu4** [micahflee/onionshare#1108]
It tells me that I need to do client authorization. But I don't know what that means. To use client authorization, you need at least both Tor 0.2.9.1-alpha (or Tor Browser 6.5) and python3-stem 1.5.0.
What I have is up to date. This must be outdated information. Please fix it. Thanks, Sam Robinson

**Comment by pokemochu4** [comment]
![Screenshot from 2020-04-21 15-02-47](https://user-images.githubusercontent.com/64107826/79918412-31868080-83e1-11ea-9369-ae50972d698d.png)

**Comment by mig5** [comment]
> It tells me that I need to do client authorization. But I don't know what that means. 

If you don't know what it means, you probably don't/shouldn't be using client authorization.

Disable the setting 'Stealth Mode' in your Settings, and try again.
