### ISSUE TITLE
Where is Stealth Mode?

### ISSUE THREAD

**Issue by turbosmurfen** [micahflee/onionshare#1109]
I Downloaded latest OnionShare but there is no Stealth Mode inside the settings. Is that removed?

**Comment by mig5** [comment]
@turbosmurfen right now, Stealth Mode only works for 'v2' style onion addresses - what we call 'Legacy' Mode. You have to check the box 'use legacy addresses', then the Stealth Mode/Client Authorization checkbox will appear beneath it.
