### ISSUE TITLE
Apt wants to remove Onionshare in Ubuntu 20.04 if installing nautilus-admin

### ISSUE THREAD

**Issue by bungabunga** [micahflee/onionshare#1110]
I don't know if this is Onionshare or nautilus-admin issue: apt wants to remove Onionshare in Ubuntu 20.04 if installing nautilus-admin

> sudo apt install nautilus-admin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libpython2.7 python-gi python3-flask python3-flask-httpauth
  python3-itsdangerous python3-jinja2 python3-pyinotify python3-stem
  python3-werkzeug
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  python3-nautilus
The following packages will be REMOVED:
  onionshare python-nautilus
The following NEW packages will be installed:
  nautilus-admin python3-nautilus

**Comment by kpcyrd** [comment]
try `sudo aptitude install nautilus-admin onionshare` and post the output

**Comment by bungabunga** [comment]
> The following packages have unmet dependencies:
 python3-nautilus : Conflicts: python-nautilus but 1.2.3-1ubuntu1 is installed
 python-nautilus : Conflicts: python3-nautilus but 1.2.3-1ubuntu1 is to be installed
The following actions will resolve these dependencies:
     Remove the following packages:                 
1)     onionshare [2.2.ppa1-1 (eoan, now)]          
2)     python-nautilus [1.2.3-1ubuntu1 (focal, now)]

**Comment by kpcyrd** [comment]
It seems you've installed onionshare from the eoan ppa and it's conflicting with packages in the latest ubuntu. One way to fix this is:

1) first removing the onionshare ppa
2) afterwards switch to the version of onionshare that ubuntu itself is shipping (also 2.2) with `sudo aptitude install onionshare/focal`

Note that this should work but I haven't tested it myself. The ppa doesn't have any packages for 20.04 yet unfortunately.

**Comment by bungabunga** [comment]
it worked!! thanks a lot!!

i'll leave this issue open until ppa reaches 20.04 package and everything is working right.

**Comment by micahflee** [comment]
This is because onionshare 2.2 depends on `python-nautilus`, but `nautilus-admin` depends on `python3-nautilus`, and you can't have both `python-nautilus` and `python3-nautilus` installed at the same time. Let me see about fixing this for the ubuntu 20.04 PPA...

**Comment by u451f** [comment]
@micahflee maybe you could abandon maintaining onionshare in a PPA. Ubuntu should synchronize packages automatically from Debian, and in Debian the package has been quite well maintained lately. Maybe it would be more useful to concentrate efforts to the maintenance in Debian, and let Ubuntu pick up the changes automatically? Just an idea to reflect on :)
