### ISSUE TITLE
Show onion address as QR code [suggestion]

### ISSUE THREAD

**Issue by FrancisPouliot** [micahflee/onionshare#1115]
I just used onion share to send videos from Laptop to Phone. I would have like at that moment a QR code to scan instead of sending the link to myself. Food for thought!

**Comment by SaptakS** [comment]
This is actually an interesting idea. I wonder what @micahflee @mig5 thinks about it.

**Comment by matt1tk** [comment]
this would be cool, found this library https://fukuchi.org/works/qrencode/ or  this stackoverflow question https://stackoverflow.com/questions/21400254/how-to-draw-a-qr-code-with-qt-in-native-c-c

**Comment by FrancisPouliot** [comment]
We did it too in our own bitcoin server project. cc @kexkey what did we use?

**Comment by Kexkey** [comment]
Cyphernode's installation is text only.  I used something called libqrencode (https://github.com/fukuchi/libqrencode) to display the QR Code in the terminal.  Here is how we build it:

https://github.com/SatoshiPortal/cyphernode/blob/master/cyphernodeconf_docker/Dockerfile#L26

You can see how we use it here:

https://github.com/SatoshiPortal/cyphernode/blob/master/cyphernodeconf_docker/templates/installer/testdeployment.sh#L87

Hope this helps!
