### ISSUE TITLE
Ability to remove multiple items after sharing files

### ISSUE THREAD

**Issue by arunsathiya** [micahflee/onionshare#1116]
After clicking on `Stop sharing`, the list of files that I was sharing earlier continues to appear. Removing them using the `x` mark next to each file name works, but it would be nice to be able to remove all files at once.

**Comment by mig5** [comment]
A fix is forthcoming in the PR above for a Clear All button, but for the record and in the meantime, you can also click on one item in the File List, then use a keyboard to Shift+select (or Ctrl+a) to select all the other items, and then click the 'Delete' button, and it will also delete them all at once.
