### ISSUE TITLE
Initial setup to use OnionShare (Question)

### ISSUE THREAD

**Issue by saadmohammad122** [micahflee/onionshare#1117]
Hey, I'm running tor and onionshare on Windows 10, fresh install, and I can't seem to share files through Tor to friends. The onionshare program loads up a Tor link just fine, but when I send the link over to a friend, they receive the "No HostName" error, and can't access the files. Is there some sort of initial setup I should implement before running OnionShare? Port forwarding/firewall set up? 
Thanks

**Comment by mig5** [comment]
@saadmohammad122 your friends need to use Tor Browser to access the link. Make sure they aren't trying to load the link in a regular browser like Chrome or Firefox. The link will only work in Tor Browser.

**Comment by saadmohammad122** [comment]
It was a link copying mistake, thank you.
