### ISSUE TITLE
 Content Security Policy (CSP) header

### ISSUE THREAD

**Issue by 1234wxw** [micahflee/onionshare#1118]
In the setting area of my Windows ver 2.2 you are unchecking a box labeled "**Disable**  Content-Security-Policy header"

On the referred wiki page (https://github.com/micahflee/onionshare/wiki/Content-Security-Policy) it states:
"You can fix this by unchecking the box " **Enable** Content-Security-Policy header in the OnionShare settings. This will remove the entire Content-Security-Policy header from your share."

I might be misreading something but it might be a typo.

Thanks

**Comment by mig5** [comment]
Thank you @1234wxw , the documentation was out of date. I have now updated it.

To clarify: the Content Security Policy is enabled by default. You can check 'Disable Content Security Policy' to turn it off before you share a website, if it is breaking the functionality of the website.
