### ISSUE TITLE
RFE: Client-side encryption before transfer

### ISSUE THREAD

**Issue by elburz** [micahflee/onionshare#1134]
Thanks for making this great project. I think a useful feature would be to have the option of providing the Receive Mode on your system with your public PGP key or even a simple password so that when the user visits your onion service, it could encrypt the file on the client-side before transmitting it and would not decrypt it by default. This would add the benefit of having the data received in a method that leaves it encrypted at rest.

The PGP key would be nice because then even the server wouldn't be able to decrypt it without your private key, but a password could be a sufficient MVP that would be helpful.

Is this something you'd be interested in and something I could contribute to?

**Comment by micahflee** [comment]
Sorry about the extremely late response. I think it's an interesting idea but I worry it would make things overly complicated. It would also only be possible if the person uploading data has javascript enabled in Tor Browser, which is disabled if you set the security slider to Safest.

I think it makes sense for the OnionShare user to use disk encryption for encryption at rest, and for the Tor Browser user to encrypt files using separate software before they upload, if they wish, to avoid adding too much complexity to OnionShare itself.
