### ISSUE TITLE
User Account System via v3 Client Auth

### ISSUE THREAD

**Issue by kevATin** [micahflee/onionshare#1136]
This is more of a question and vague idea that I'm throwing into the room, rather than concrete suggestion;

Could v3 Client Authorization be used as a User Account system?

To my knowledge it is not possible to show a non-authorized client a default site when trying to access a service that uses client authorization. Instead a separate landing site service would have to run without v3CA where users can request new accounts and all that.
From the documentation I've seen on torproject I'm not sure if v3CA does or does not allow onion services to deliver different data to different clients.

Apart from being pretty cool by itself, it would have the advantage of not introducing any additional attack surface to the code/service, and to circumvent this account system one would have to break Tor itself- making it quite secure.

Possible applications of an account system would be: permanent usernames for chat #1096 , separate upload directories for users, different files offered for download for different users, maybe completely different sites visible to different users, etc

Any thoughts on this?

**Comment by micahflee** [comment]
I think it would be much simpler for the user to just make a separate tab for each person they want to send the link to. Once v3 ClientAuth is supported, this will have a similar affect and be simpler
