### ISSUE TITLE
OnionShare - Support vanity URL for permanent addresses

### ISSUE THREAD

**Issue by edu-cated** [micahflee/onionshare#1147]
Onion links are generally meaningless, but it is possible to create URLs with meaningful characters using Free Software. OnionShare should support vanity URLs.

Here is an example:

HTTP
https://onionshare.org
(This is meaningful. You can easily remember and type the name of the url.)

ONION
http://lldan5gahapx5k7iafb3s4ikijc4ni7gx5iywdflkba5y2ezyg6sjgyd.onion/
(After  http:// it is random and difficult to remember.

ONION with Vanity (non-functional link for example)
http://onionsharepx5k7iafb3s4ikijc4ni7gx5iywdflkba5y2ezyg6sjgyd.onion/
(There is a meaningful component in the URL at the beginning. Up to 6 or 7 meaningful characters can practicably be used.)

This issue might help with those who wish to use permanent URLs or be of value to people who wish to periodically update their website using OnionShare.

https://github.com/micahflee/onionshare/issues/1059

There is Free Software to achieve this available here:

https://github.com/ReclaimYourPrivacy/eschalot
https://github.com/cathugger/mkp224o

And a tutorial here:
https://opensource.com/article/19/8/how-create-vanity-tor-onion-address

**Comment by tyhp** [comment]
Possibly there could be a textbox for the private key of your vanity address in the advanced settings of the tab, like here:
![onionshare private key mockup](https://user-images.githubusercontent.com/73394599/97088275-4c9bac80-161f-11eb-9394-b01b2e08a30c.png)

**Comment by micahflee** [comment]
I think this might complicate the UI too much. If you wanted a vanity onion you could create a persistent share and then edit the config file to replace the key with your new vanity key.
