### ISSUE TITLE
PPA GnuPG key is 1024 bit

### ISSUE THREAD

**Issue by ooguz** [micahflee/onionshare#1153]
The GnuPG key that is used for PPA releases is 1024 bit RSA, so it's unsecure. 
```
pub   rsa1024 2013-11-01 [SC]
      7EF3 3F02 7E9E 4869 F46F  77E3 4E72 F77D 7D15 8F33
uid           [ unknown] Launchpad PPA for Micah Lee
```
Is there any specific reason for using 1024 bit RSA key? If not, switching to a 4096 bit key is very urgent, thus the releases would be more trusted.

**Comment by micahflee** [comment]
Sadly I don't have control over Launchpad's PPA keys. That's an Ubuntu Launchpad thing. But since the next version of OnionShare will include Flatpak support (#910) I think this will be the recommended way for installing OnionShare in Linux, and I will likely retire the PPA.
