### ISSUE TITLE
Localization for 2.3

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#1170]
- [x] Make weblate has access to the latest strings
- [x] Re-take screenshots for weblate
- [x] Add documentation component to weblate
- [x] Make a 2.3 development release for translators to use
- [x] Push for translations into supported languages

**Comment by comradekingu** [comment]
@micahflee Why was the license for one of the doc components changed to GPLv3-only today? GPLv3+ is preferable.
https://github.com/micahflee/onionshare/blob/develop/onionshare/common.py is GPLv3+

**Comment by micahflee** [comment]
> @micahflee Why was the license for one of the doc components changed to GPLv3-only today? GPLv3+ is preferable.
> https://github.com/micahflee/onionshare/blob/develop/onionshare/common.py is GPLv3+

It was? The commit here https://github.com/micahflee/onionshare/commit/4c4323a772c56c6fc38ed5ec99868ba2ce82285d was supposed to just change the copyright string from

>  Copyright © 2014-2018 Micah Lee <micah@micahflee.com>

to

> Copyright (C) 2014-2020 Micah Lee, et al. <micah@micahflee.com>

But I don't think it changed the actual license itself.

**Comment by comradekingu** [comment]
It can't be that (?), as Doc-install was relicensed from LGPL-3.0 to GPLv3-only the 14th of sept. Was master rebased on develop then maybe? It is still a stretch, because none of that is the change that happened.

https://hosted.weblate.org/projects/onionshare/#information is all GPLv3-only.
You can change it in https://hosted.weblate.org/settings/onionshare/translations/ and all other respective components

**Comment by emmapeel2** [comment]
I have changed the license, sorry!
I didnt knew which one to choose, really, and I wanted all the components to have the same license.  As Onionshare was published under GPL3, i decided to be more precise. But I can change it back if needed

**Comment by comradekingu** [comment]
@emmapeel2 "or later" just means the program will never be incompatible with its strings from what I can tell.
So changing it to that is preferable.

Some day I will find out if marking every file "or later" is what it takes, or if the projects marking the license "only" in the text is how things stop being "or later". In any event the pure license is one of those, and both are compatible with "or later".

**Comment by micahflee** [comment]
Also for this issue, and @emmapeel2 maybe you have opinions here, what languages should we aim for supporting for version 2.3 and the docs? These are what were supported for version 2.2:

```py
        # Dictionary of available languages in this version of OnionShare,
        # mapped to the language name, in that language
        self.available_locales = {
            "ar": "العربية",  # Arabic
            #'bn': 'বাংলা', # Bengali (commented out because not at 90% translation)
            "ca": "Català",  # Catalan
            "zh_Hant": "正體中文 (繁體)",  # Traditional Chinese
            "zh_Hans": "中文 (简体)",  # Simplified Chinese
            "da": "Dansk",  # Danish
            "nl": "Nederlands",  # Dutch
            "en": "English",  # English
            # "fi": "Suomi",  # Finnish (commented out because not at 90% translation)
            "fr": "Français",  # French
            "de": "Deutsch",  # German
            "el": "Ελληνικά",  # Greek
            "is": "Íslenska",  # Icelandic
            "ga": "Gaeilge",  # Irish
            "it": "Italiano",  # Italian
            "ja": "日本語",  # Japanese
            "nb": "Norsk Bokmål",  # Norwegian Bokmål
            "fa": "فارسی",  # Persian
            "pl": "Polski",  # Polish
            "pt_BR": "Português (Brasil)",  # Portuguese Brazil
            "pt_PT": "Português (Portugal)",  # Portuguese Portugal
            "ro": "Română",  # Romanian
            "ru": "Русский",  # Russian
            "sr_Latn": "Srpska (latinica)",  #  Serbian (latin)
            "es": "Español",  # Spanish
            "sv": "Svenska",  # Swedish
            "te": "తెలుగు",  # Telugu
            "tr": "Türkçe",  # Turkish
            "uk": "Українська",  # Ukrainian
        }
```

**Comment by emmapeel2** [comment]
@micahflee right now there are less of those languages at 90% translation of the app, and the docs have even less translation.

I say we stick to the languages where the strings of the application are at least 90% translated, and add languages to the docs when we have finish them. 

Maybe we should make a translation call so we can publish more, at the moment languages with 90% translated app are only: Spanish, Croatian, Icelandic, Ukranian (https://hosted.weblate.org/projects/onionshare/translations/)

And the docs are only translated 90% or more in Spanish, Croatian, Ukranian.

I miss at least French, Italian, Arabic, Chinese, Portuguese, Russian, Turkish that I think we can get translated if we make a call.

**Comment by emmapeel2** [comment]
Another thing: is there are way to preview the docs? I see some translators are not maintainting the formatting very well, maybe if we provide them a preview of the docs they can understand for example the double colons (::) and links.

**Comment by comradekingu** [comment]
I have been meaning to go over the docs to bring them in line with the actual program and the other changes. Need 3 days to get it done.

@michaflee In my view any percentage of good translations is useful, and brings the bar up to the artificial level sooner.
Let the people that want to have translations support themselves. Having it be incomplete is a good call to action. The smallest languages don't have any illusions about how many people are working on their translation.
Curiously, it becomes harder for smaller languages to get the same bang for their efforts with limits.

**Comment by comradekingu** [comment]
All the documentation PRs are in. Was going to have a go at the wiki, but it isn't open anymore.

**Comment by micahflee** [comment]
I'm trying to make a development build for OnionShare 2.3.dev1 to give to translators, but I'm hitting an issue #1200. So this is blocked until that it resolved. (Of course, translations can continue.)
