### ISSUE TITLE
Typo in docs Advanced or not?

### ISSUE THREAD

**Issue by IgorHordiichuk** [micahflee/onionshare#1182]
Looks like a typo in the last "line" word on the string 60. Should it be the word "like"? Or, probably, it needs to be reworded to become more understandable, if I'm wrong?
https://github.com/micahflee/onionshare/blame/develop/docs/source/advanced.rst

**Comment by micahflee** [comment]
You're right, that's a typo. Fixing now.

**Comment by micahflee** [comment]
Fixed https://github.com/micahflee/onionshare/commit/2779a1c2af109dcb13bf7ffd5ad7f2cc2906b189
