### ISSUE TITLE
Tor connection failure dialog problem

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#1184]
If you disconnect from the internet and then open OnionShare, and wait for Tor to fail to connect, it throws this error:

![Screenshot from 2020-09-20 15-47-56](https://user-images.githubusercontent.com/156128/93724066-c8a26080-fb58-11ea-823c-edbedba61c79.png)

It shouldn't say `'settings_error_bundled_tor_timeout'` in there...

**Comment by SaptakS** [comment]
So it seems that `settings_error_bundled_tor_timeout` is present as a key in some other locale files but not in en.json which makes me feel that this was a deliberate decision? So should I add the key back to en.json or just remove the text? :thinking: 

Also, on the similar terms, if I select to connect using tor browser and tor browser isn't running, it shows a `settings_error_automatic` in the dialogue in the same place. Should I add the keys back to en.json or show the same `Try changing how OnionShare connects to the Tor  network in the settings` message on all dialogues?

**Comment by SaptakS** [comment]
This is fixed in #1208
