### ISSUE TITLE
Share mode canceling download on its own (in Windows)

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#1185]
I'm testing share mode, sharing a 37mb file. I load the site in Tor Browser, start downloading the file, and then it Tor Browser it says the file is complete after 7.4mb, but in OnionShare it just shows the beginning of the file downloaded and says it was canceled.

**Comment by mig5** [comment]
Is it similar to #929 ? Does 'stay_open' mode help?

**Comment by micahflee** [comment]
Yeah now that I test this more, I think this is a duplicate of #929
