### ISSUE TITLE
License for Weblate translations incorrect

### ISSUE THREAD

**Issue by comradekingu** [micahflee/onionshare#1188]
From #1170

Doc-install was re-licensed from LGPL-3.0 to GPLv3-only the 14th of sept.
https://hosted.weblate.org/projects/onionshare/#information is all GPLv3-only.
Can be changed in

 https://hosted.weblate.org/settings/onionshare/application/
https://hosted.weblate.org/settings/onionshare/advanced/
https://hosted.weblate.org/settings/onionshare/developer/
https://hosted.weblate.org/settings/onionshare/features/
https://hosted.weblate.org/settings/onionshare/help/
https://hosted.weblate.org/settings/onionshare/index/
https://hosted.weblate.org/settings/onionshare/install/
https://hosted.weblate.org/settings/onionshare/security/
https://hosted.weblate.org/settings/onionshare/sphinx/
https://hosted.weblate.org/settings/onionshare/doc-tor/

and all other respective components

To my knowledge the whole application is GPLv3+ like
https://github.com/micahflee/onionshare/blob/develop/onionshare/common.py

Ultimately the mouseover on https://hosted.weblate.org/projects/onionshare/#information should all be "GPLv3-or-later".

**Comment by micahflee** [comment]
I'm totally happy with GPLv3+ for the translations. I just updated all of the weblate components.
