### ISSUE TITLE
Windows packaging crash

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#1200]
I'm trying to make a development build of version 2.3 for #1170, so that translators can have a very of the software to run and use to better understand context, and I've been running into a frustrating issue in Windows. The branch I'm working on at the moment is https://github.com/micahflee/onionshare/tree/release-changes.

I'm able to set up a Windows development environment, make a release, and then run my `onionshare-gui.exe` binary there without a problem. However if I move my binary (built with PyInstaller) to another Windows box that doesn't have the development environment installed, it crashes with this error:

```
Traceback (most recent call last):
  File "install\scripts\onionshare-pyinstaller", line 45, in <module>
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\onionshare-i_zmdpLh-py3.7\lib\site-packages\pyinstaller-3.6-py3.7.egg\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "onionshare_gui\__init__.py", line 30, in <module>
ImportError: DLL load failed: The specified module could not be found.
[976] Failed to execute script onionshare-pyinstaller
```

Line 30 of `onionshare_gui\__init__.py` is:

```python
from PyQt5 import QtCore, QtWidgets
```

So the problem seems to be that PyInstaller isn't including all of the correct Qt5 DLLs, though after making a build, `dist/onionshare` includes these:

- Qt5Core.dll
- Qt5Network.dll
- Qt5Quick.dll
- Qt5Widgets.dll
- Qt5DBus.dll
- Qt5Qml.dll
- Qt5Svg.dll
- Qt5Gui.dll
- Qt5QmlModels.dll
- Qt5WebSockets.dll

I've been smashing my head against the keyboard trying to solve this problem but so far no luck.

I'm actually considering attempting switching from PyInstaller to [Briefcase](https://docs.beeware.org/en/latest/) though this would involve a pretty huge change, including a lot of refactoring of the code I think. And if we do switch to Briefcase it's probably worth switching for macOS as well...

But maybe there's a simpler solution, I just haven't found it yet.

**Comment by mig5** [comment]
Did some googling, possible things to look at?

https://github.com/mu-editor/mu/issues/354

> This is because QtCore (and other Qt extensions) are linked to python3.dll rather than to python36.dll. The released versions of virtualenv (15.1 as I write) do not copy this file over. virtualenv master has a fix for this (cf pypa/virtualenv#1083) but no released version has this fix.


https://stackoverrun.com/fr/q/11793371

> This problem may be caused by the QT DLL's are not bundled by PyInstaller (see PyQT 5.7 DLLs are not bundled. https://github.com/pyinstaller/pyinstaller/issues/2152
> 
> Building and running your example code with the "--paths" directive works fine and the application created in the "dist" folder can be executed sucessfully:
> 
> pyinstaller --paths C:\Python35-32\Lib\site-packages\PyQt5\Qt\bin test.py

**Comment by crwood** [comment]
I ran into the same problem with a PyQt5 project that I work on and fixed the issue by extending PyInstaller's paths to include `PyQt5\Qt\bin` (as suggested above by @mig5). Note, however, that depending on the patch/version level of your target platform, you may _also_ need to bundle the Windows Universal C Runtime libraries -- whose location can vary depending on how you originally installed the Windows 10 SDK. See [this PyInstaller .spec file](https://github.com/gridsync/gridsync/blob/b8df60f3400c5dd4428dd815830bda745a5d8f97/misc/gridsync.spec) for an example of how/which additional directories to pass to PyInstaller to get a binary bundle that works across all currently-supported Windows versions.

**Comment by micahflee** [comment]
Unfortunately I still haven't gotten this to work.

Thanks @crwood, the example .spec file was really helpful. I tried adding these to the path, and I confirmed that those paths are correct on my system, and I can tell it's working properly because of my pyinstaller output:

```
C:\Users\user\code\onionshare>pyinstaller install\pyinstaller.spec -y
247 INFO: PyInstaller: 3.6
247 INFO: Python: 3.7.4
247 INFO: Platform: Windows-10-10.0.19041-SP0
247 INFO: UPX is not available.
263 INFO: Extending PYTHONPATH with paths
['C:\\Users\\user\\code\\onionshare\\install\\scripts',
 'C:\\Users\\user\\code\\onionshare',
 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python37-32\\Lib\\site-packages\\PyQt5\\Qt\\bin',
 'C:\\Program Files (x86)\\Windows Kits\\10\\bin\\x86',
 'C:\\Program Files (x86)\\Windows Kits\\10\\bin\\x64',
 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86',
 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64']
263 INFO: checking Analysis
263 INFO: Building because pathex changed
263 INFO: Initializing module dependency graph...
263 INFO: Caching module graph hooks...
292 INFO: Analyzing base_library.zip ...
```

However I still end up with the same problem. When I copy the final binary to another Windows computer and try running, I still hit this error:

```
C:\Users\user\Desktop\dist\onionshare>onionshare-gui.exe
Traceback (most recent call last):
  File "onionshare-pyinstaller", line 45, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyinstaller-3.6-py3.7.egg\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "onionshare_gui\__init__.py", line 30, in <module>
ImportError: DLL load failed: The specified module could not be found.
[980] Failed to execute script onionshare-pyinstaller
```

In this case, I also tried installing all of the dependencies directly with pip, rather than managing them with poetry, in case the issue I was running into was somehow related to poetry. It's not though.

And thanks @mig5, but still so far no luck. I do notice that the files in the dist folder that pyinstaller creates has both `python3.dll` and `python37.dll`.
