### ISSUE TITLE
Missing Flatpak release

### ISSUE THREAD

**Issue by nunesgh** [micahflee/onionshare#1201]
A Flatpak release of OnionShare is mentioned on the [README file](https://github.com/micahflee/onionshare/blob/develop/README.md), linking to what should be [installation instructions](https://docs.onionshare.org/en/install.html#install-in-linux-with-flatpak). Unfortunately that link is broken, and searching for OnionShare on FlatHub does not return any package.

Is Flatpak still supported?

**Comment by mig5** [comment]
Hi @nunesgh,

The README you've linked to is that in our 'develop' branch (granted, that is our default branch, so it's what is loaded by default). 

Both the Flatpak and the docs.onionshare.org are not actually released yet. It is being worked on right now as part of the upcoming 2.3 release. The README has been updated recently to reflect that, which is a bit confusing as it makes it look like it's already ready, but it's not.

Flatpak is therefore not only 'suppored' but is in fact the recommended way to install on Linux as of the *upcoming* release, which we hope to release 'soon'.

You can check out this PR https://github.com/micahflee/onionshare/pull/1139 which was recently merged for Flatpak support. Although it won't help you fetch a release from FlatHub, it does contain instructions on how to build your own Flatpak package.

Sorry for the confusion, hopefully all will work as expected when we actually release 2.3 off of develop branch.
