### ISSUE TITLE
Can't play uploaded songs or videos with special letters and symbols (v2.3)

### ISSUE THREAD

**Issue by RaidenMK** [micahflee/onionshare#1211]
I have tried to play a file (song and a video) that I have uploaded using "Share Files" feature and it seems that the file (the song and video) can't be played if the filename have special letters like ć and Ž. It get stuck and keeps loading and I get this "Cancelled" continously while the direct link of the file is loading. So for the file (song or video or whatever that can be played) to be played,I need to change whatever special letters and symbols there is in the filename to normal letters instead of special letters. If there are problems with other special letters and symbols,I don't know.. there are to many special letters and symbols to go through. If there are other files that can be played and not just .mp3 and mp4,I don't know.. but there might be the same problem with other files that can be played. so check that when you can.

**Comment by Kcchouette** [comment]
Can you try to reproduce it using latest onionshare version (2.3.1) @RaidenMK?

**Comment by mig5** [comment]
On 2.3.1 I tested playing a file called `Test_ćŽ.mp3` and it worked fine, at least on Linux and MacOS TorBrowsers, with Linux as the 'sharer' (the OnionShare process itself). It's possible this is Yet Another Windows issue, but as best as I can tell, it's ok. Please re-open if it continues to be a problem on 2.3.1 or higher.
