### ISSUE TITLE
Cannot upload files from Tor Browser for Android to computer

### ISSUE THREAD

**Issue by fklrx345** [micahflee/onionshare#1221]
Trying to transfer files from a phone to a computer. The official Tor Browser (10.0.4) on Android can go to the .onion site (which by the way does not seem to detect any "responsive design" that exists). Hitting the Browse button goes to the the storage of the phone as it should. Any file chosen though does not subsequently show up on the .onion site in order to send.

Reading past issues, it seems this function worked in the past, so don't know if it is just the phone or it stopped working with the newest Tor Browser update.

**Comment by u451f** [comment]
Just to understand your problem a bit better:

you have onionshare running on the computer, in receive mode and you want to upload files from your Android phone that has Tor browser installed. Correct?

**Comment by fklrx345** [comment]
Yes, that is correct. The computer is in receive mode and trying to upload files from an Android phone through the official Tor Browser.

Tried uploading files to this site https://upload.disroot.org through the Tor Browser and cannot do so. Also tried uploading a file to that same site using a different browser and it worked. So it's not the operating system either and it definitely seems to be a problem with the Tor Browser itself.

It would be nice to know if everyone else reading this has this problem too and it can be replicated.

Found what might be be a related issue: https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40283

**Comment by whew** [comment]
> It would be nice to know if everyone else reading this has this problem too and it can be replicated.
I also can't upload files anywhere with Tor Browser for Android.

**Comment by Kcchouette** [comment]
Seems more a limitation/bugs from tor browser for android than an issue of onionshare...

**Comment by red3047** [comment]
Hello. I have an android. Files are not loaded from the phone to sites / onion. Cannot upload files from Tor Browser for Android to computer #1221
