### ISSUE TITLE
Metapackaging down?

### ISSUE THREAD

**Issue by comradekingu** [micahflee/onionshare#1225]
https://github.com/micahflee/onionshare/blob/develop/docs/source/install.rst#L19 has a [link to a Flatpak](https://flathub.org/apps/details/org.onionshare.OnionShare), but it isn't on Flathub (under that URL anyways).

https://github.com/micahflee/onionshare/blob/develop/docs/source/install.rst#L21 has a [link to the Snap](https://snapcraft.io/onionshare), but that isn't there either.

https://github.com/micahflee/onionshare/blob/develop/docs/source/install.rst#L23 says they are to be found in https://onionshare.org/dist/ , but it doesn't look like it.

**Comment by micahflee** [comment]
Should be fixed now. Weblate actually pulls from this repo https://github.com/micahflee/onionshare-weblate which is a mirror of the onionshare repo, so I need to push to that repo for weblate to see the changes.
