### ISSUE TITLE
i'm getting the error "permission denied" when I try to share a file. im using onion share 1.3.2 on tails 4.13. 

### ISSUE THREAD

**Issue by onionhabbit** [micahflee/onionshare#1234]
i'm getting the error "permission denied" when I try to share a file. im using onion share 1.3.2 on tails 4.13. Thank You

**Comment by mig5** [comment]
Hi @onionhabbit,

I don't think this is a bug in OnionShare, but maybe to do with the filesystem or permissions on the file. OnionShare is probably surfacing an underlying permissions issue with the file, but likely isn't causing the problem itself.

Is the 'permission denied' error in the browser for the person downloading the file, or does it appear in the desktop OnionShare app in Tails?

Does it occur with other files or just this file?

**Comment by u451f** [comment]
This is likely due to AppArmor (https://en.wikipedia.org/wiki/AppArmor) not giving you access to certain folders.
You can ask the Tails help desk about it: https://tails.boum.org/support/

**Comment by efialtos** [comment]
Probably it can be because of snap permissions: https://github.com/micahflee/onionshare/issues/1308
