### ISSUE TITLE
Documentation not available

### ISSUE THREAD

**Issue by JoAllg** [micahflee/onionshare#1241]
Hey,

the documentation from the readme does not exist: https://docs.onionshare.org/

**Comment by mig5** [comment]
Hi,

The new documentation (which will be at that address) is not yet available, but will be soon, with the next release. 

You have probably found that URL via the README in our 'dev' branch (which is the default when loading Github), which sometimes includes 'upcoming' but as-yet unpublished changes. It's confusing, but it's a temporary situation.

For now, please use the Wiki in Github if you need help: https://github.com/micahflee/onionshare/wiki

Thanks!
