### ISSUE TITLE
Make a Debian compatible repo for Onionshare, or maintain the outdated package official Debian repos already have

### ISSUE THREAD

**Issue by ElonSatoshi** [micahflee/onionshare#1242]
Tails OS is still using an outdated version of Onionshare. Help them package a more recent version with the next version of Tails.

**Comment by u451f** [comment]
Tails has a person taking care of this, so I think this won't be necessary.

The Debian version is 2.2 - which is the latest official release of Onionshare - and normally this is also the version that should be included by Tails. Are you using an outdated version of Tails by any chance?

**Comment by u451f** [comment]
@micahflee I think you can close this issue.
