### ISSUE TITLE
Finalize localization, documentation, screenshots

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#1247]
Before the 2.3 release is ready:

- [x] Update the screenshots in the docs to use the latest screenshots
- [x] Pick which languages OnionShare will be translated to, enable those in settings, and make sure all the strings are merged
- [x] Pick which languages the docs will be translated to (ideally the same ones) and enable those in the docs (we can perhaps make the release without this one)

**Comment by mig5** [comment]
And I assume we want to deploy docs.onionshare.org to the server, let me know if you need help there.

**Comment by micahflee** [comment]
Yes absolutely

**Comment by micahflee** [comment]
In the OnionShare app itself, these languages are above complete:

- Arabic
- Bengali
- Chinese (Simplified)
- Croatian
- Danish
- English
- French
- Galician
- German
- Greek
- Icelandic
- Japanese
- Kurdish (Central)
- Norwegian Bokmål
- Portuguese (Brazil)
- Slovak
- Spanish
- Swedish
- Turkish
- Ukrainian

There are above 90% translated:

- Catalan
- Italian
- Dutch
- Portuguese (Portugal)
- Russian
- Finnish

These are above 85% translated:

- Chinese (Traditional)
- Polish

And Arabic is at 78%, which it's quite close and a huge language.

So I think I'm going to do a call-out on Twitter asking people to help translate the rest of Arabic, Chinese (Traditional), and Polish, and then we can include this list of languages in the final release.

**Comment by micahflee** [comment]
The documentation is completely translated into these languages, so I think it makes sense to include them in the release:

- English
- German
- Greek
- Spanish
- Turkish
- Ukrainian

I'm also asking a friend if he could translate the docs into Chinese traditional and simplified as well, because I'd like to include those too.
