### ISSUE TITLE
Refine OSX roadmap: or developers or users

### ISSUE THREAD

**Issue by remagio** [micahflee/onionshare#125]
I found 7 over 11 issues since may-june related to package/requirements/library/version for using it on OSX. Also for development porpouse there's not a unique solutions b/c some requirements differ from 10.5 to 10.9 or other minor issues. I'm not saying it's a Onionshare problem, but for sure is a UX problem.
If Onionshare, like I suppose, is useful for all users and not only for geek devs… the OSXs version require some more packaging/integration design.
What do you think about it?

**Comment by micahflee** [comment]
Pretty much all of the OSX issues were related to me bundling the OSX .app with the version of python that came with my Mac, rather than one that came from python.org. It now works great in OSX.
