### ISSUE TITLE
Onionshare does not appear to be listed on flathub

### ISSUE THREAD

**Issue by JLC6290** [micahflee/onionshare#1252]
https://flathub.org/apps/search/onionshare

Not listed, perhaps I'm missing something here?

**Comment by mig5** [comment]
Please see https://github.com/micahflee/onionshare/issues/1201 and https://github.com/micahflee/onionshare/issues/910#issuecomment-654013989. 

The flatpak is not yet released. You have read the README for our `develop` branch, where it is mentioned as part of our upcoming release, but it doesn't exist yet.
