### ISSUE TITLE
Onionshare's own 405 page is never shown

### ISSUE THREAD

**Issue by whew** [micahflee/onionshare#1253]
When you send a disallowed request e.g. POST to index.html, what you get back is some default 405 page not Onionshare's 405 page. [`error405`](https://github.com/micahflee/onionshare/blob/develop/cli/onionshare_cli/web/web.py#L296) is never actually called.

```
$ curl -x socks5h://127.0.0.1:9050 -X POST -v http://[onionshare].onion/
> POST / HTTP/1.1
> Host: [onionshare].onion
> User-Agent: curl/7.68.0
> Accept: */*
> 
< HTTP/1.0 405 METHOD NOT ALLOWED
< Content-Type: text/html
< Allow: OPTIONS, GET, HEAD
< Content-Length: 178
< Server: Werkzeug/0.16.1 Python/3.8.5
< Date: Fri, 18 Dec 2020 00:25:40 GMT
< 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```

Edit: I tested this on version 2.2.

**Comment by mig5** [comment]
Yep, this was observed in https://github.com/micahflee/onionshare/pull/1056 . For POST request it seems Flask throws its own 405, never found a fix for it. For OPTIONS or HEAD it does work however.

**Comment by whew** [comment]
For me OPTIONS and HEAD always gives 200 or Flask's 405 page:

Share mode `/`

|        | GET        | POST                        | OPTIONS    | HEAD                        |
|--------|------------|-----------------------------|------------|-----------------------------|
| Status | 200        | 405                         | 200        | 200                         |
| Server | OnionShare | Werkzeug/1.0.1 Python/3.8.5 | OnionShare | Werkzeug/1.0.1 Python/3.8.5 |

Receive mode `/upload`
|        | GET                         | POST                        | OPTIONS                     | HEAD                        |
|--------|-----------------------------|-----------------------------|-----------------------------|-----------------------------|
| Status | 405                         | 302                         | 405                         | 200                         |
| Server | Werkzeug/1.0.1 Python/3.8.5 | Werkzeug/1.0.1 Python/3.8.5 | Werkzeug/1.0.1 Python/3.8.5 | Werkzeug/1.0.1 Python/3.8.5 |

**Comment by whew** [comment]
jfinkels/flask-restless#362 is the same issue of Flask giving its own 405 response. They solved it(?) in jfinkels/flask-restless#366. I can't really tell, that PR isn't straightforward.

**Comment by whew** [comment]
I think that this happens because when you define routes in Flask you can specify a list of allowed http methods but if you don't it defaults to GET only: https://flask.palletsprojects.com/en/1.1.x/quickstart/#http-methods

So when we receive a POST request Flask sees it's not in the list of allowed methods and returns its own 405 page without ever entering our function. I think adding `methods=['GET', 'POST']` to [share_mode.py](https://github.com/micahflee/onionshare/tree/develop/cli/onionshare_cli/web/share_mode.py#L137) and [website_mode.py](https://github.com/micahflee/onionshare/tree/develop/cli/onionshare_cli/web/website_mode.py#L40) and would fix this.

Possibly a better way would be to override Flask's 405 page with our own somehow: https://flask-doc.readthedocs.io/en/latest/patterns/errorpages.html

**Comment by mig5** [comment]
I like the idea of setting the methods because this might even squash potentially other issues (let's say, some security vuln when using `HEAD` or `OPTIONS` or `PUT` with Flask or something).

**Comment by mig5** [comment]
Even with the methods set, the default Flask 405 page intercepted.

The solution turned out to be simple, we just needed to properly register the 405 error handler in our Web class

```
+        @self.app.errorhandler(405)
+        def method_not_allowed(e):
+            mode = self.get_mode()
+            history_id = mode.cur_history_id
+            mode.cur_history_id += 1
+            return self.error405(history_id)
```

I'm working on a PR, I might add a 500 error page in the same way, and I need to add some tests at least for the 405.
