### ISSUE TITLE
Receive Files Path 

### ISSUE THREAD

**Issue by wwwhtml** [micahflee/onionshare#1258]
Hello Micah,

Wondering if possible to display the path where files will be saved when folks use the "Receiving files" mode. It will be useful for new of first time uses. 

Many thanks!

Daniel

**Comment by mig5** [comment]
Is this not already on the screen in Receive Mode tabs..?

![Screenshot_2021-05-03_13-38-24](https://user-images.githubusercontent.com/99173/116839236-e5396780-ac14-11eb-83e8-428febb81d1a.png)
