### ISSUE TITLE
error in latest version

### ISSUE THREAD

**Issue by allenwrench** [micahflee/onionshare#1263]
![image](https://user-images.githubusercontent.com/69438439/104111668-c05e6480-52b2-11eb-92fe-42f946b5204f.png)

**Comment by mig5** [comment]
Hi,

You probably experienced this during a known, Tor-wide service degradation issue that affected 'v3' style onions (of which our 'check for new version' functionality relies on).

This was not an OnionShare specific issue. Please let us know if you continue to experience issues with the update check though.

https://darknetdaily.com/?p=1030
https://gitlab.torproject.org/tpo/core/tor/-/issues/40237
