### ISSUE TITLE
Cannot send link over Electron apps

### ISSUE THREAD

**Issue by dheadshot** [micahflee/onionshare#1269]
It seems that because of the deprecation of the [Basic Authentication Scheme](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#basic_authentication_scheme) used by later versions of Onionshare and the fact that Electron is basically just Chrome who [strip it out](https://bugs.chromium.org/p/chromium/issues/detail?id=82250#c7), you cannot share Onionshare links over Electron apps (like Discord, etc.) as the Authentication slug is stripped out.  The old method of having a slug after the "/" at the end worked fine when it was available, but while the Authentication is more secure, it falls foul of this problem.

Example:
I pasted `http://onionshare:sandpit-crisping@mo3hmf64optvmoifdfiuqhcwazc5znk4mnvubwhsxbat4fmdybjdgnid.onion` (I have since taken the onion down, so I can share this link) into Discord and it sent `http://mo3hmf64optvmoifdfiuqhcwazc5znk4mnvubwhsxbat4fmdybjdgnid.onion`, stripping out all authentication from the link, thus meaning the recipient couldn't use the link.

I would have thought the simplest solution would be to have an option that restores the old behaviour of using a slug after the slash that can be enabled for sharing links via electron apps?

**Comment by Kcchouette** [comment]
you can share the url without the authentication part and give credentials in the message after

**Comment by micahflee** [comment]
This will be fixed once #1343 is implemented
