### ISSUE TITLE
Onionshare could not be installed

### ISSUE THREAD

**Issue by ArmandoSaboia** [micahflee/onionshare#1270]
Hey,

When I try to install Onionshare using cli on Ubuntu 20.10, I get an error message: 

sudo add-apt-repository ppa:micahflee/ppa

sudo apt update

sudo apt install -y onionshare

    **_Some packages could not be installed. 
    This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming. The following information may help to resolve the situation:

    The following packages have unmet dependencies:
    onionshare : Depends: python-nautilus but it is not installable
    E: Unable to correct problems, you have held broken packages._**

Any hints how I can fix this issue are appreciated.

**Comment by Gez-Schegtel** [comment]
Hi, i had the same issue. The solution is remove the micahflee PPA, and then just type in terminal sudo apt install -y onionshare. I guess in ubuntu 20.10 the program is in the default repo. 

Hope it works for you. Cheers

**Comment by ArmandoSaboia** [comment]
Hi Gez-Schegtel,
Thanks for your hint, but i've installed via sudo snap install onionshare --edge and it works perfectly.
Cheers
