### ISSUE TITLE
Dependency on python-nautilus disturbs dependencies of Python 3

### ISSUE THREAD

**Issue by agharbeia** [micahflee/onionshare#1274]
In Ubuntu, the exclusive dependency on package python-nautilus causes Python-Nautilus bindings libraries of other versions such as python3-nautilus, to be removed, and consequently, their dependencies, such as nautilus-admin.

Suggested solution: make it an alternative dependency.

Rant:
The naming scheme of the Python-Nautilus packages could probably have been approached differently as to not require third-party packages to make temporal or distro-specific assumptions. A different approach could be that a generically named "python-nautilus" package is a virtual one that depended on the Python version implementation chosen by the platform, i.e either python2-nautilus or python3-nautilus.

**Comment by mig5** [comment]
This sounds more or less like a duplicate (equivalent but opposite outcome) to #1110
