### ISSUE TITLE
File directories not working

### ISSUE THREAD

**Issue by Rkmskmrobots** [micahflee/onionshare#1275]
Might be me, but I also can't find a set tutorial on getting this to work.

Every time I try to drag files to onionshare and then go live I get a 500 Server error when trying to connect.

I've seen other examples where people can view a site with file directories, but I can only get mine to work with individual files and no folders.

What's the solution here or is it broke?

**Comment by Rkmskmrobots** [comment]
This is on windows if relevant

**Comment by 1000i100** [comment]
It look related to #1053

**Comment by Kcchouette** [comment]
what is your onionshare version?

I've no problem to work with directory; I create a directory "website" and inside I have my main index.html and all folder related
and then I share the "website" folder inside onionshare in website mode

**Comment by Rkmskmrobots** [comment]
> what is your onionshare version?
2.2, but just saw it got updated to 2.3.1 in the last few days, so I might try that.

> 
> I've no problem to work with directory; I create a directory "website" and inside I have my main index.html and all folder related
> and then I share the "website" folder inside onionshare in website mode


When I put a bunch of folders with subfolders in onionshare for the "website" mode, it gives me the error. It might be an error on my part not using the right formatting in an html file maybe? Is there any specific code I should have in my index.html to get the folders to show up?

It works fine when I have just files listed, just folders never show up.

**Comment by Kcchouette** [comment]
you can try to go to a subfolder and it should show you all the files if the folder doesn't contain index.html
like I said, you should have one super root folder, which contains all subfolder/img and one index.html

**Comment by Rkmskmrobots** [comment]
I can't browse any subfolders because it gives me the internal error. I tried uploading just folders with no index.html and it doesn't even show a super root folder. It just gives me the internal error message

**Comment by 1000i100** [comment]
idem here (onionshare 2.3.1 on windows10 x64) : 
With and index.html file : the root display the index.html (but subfolder file contained fail to load with 404).
With no index.html -> error 500 for the root folder, fine for files in root folder, 404 for subfolder or it content.
and same result if i copy the main folder content including subfolder or the main folder itself in onionshare.

**Comment by Kcchouette** [comment]
Maybe it's specific to windows :/
On Linux, here a detailed case of a directory working:
- clone https://github.com/micahflee/onionshare-website.git
  - it create you a "onionshare-website" folder with onionshare website content
- open onionshare, go to website tab and add this folder (onionshare-website)
- access to the website it created
- you can see all the pictures (even the main big one with come from `assets/img/logo.png`) (identical website 

![Screenshot](https://user-images.githubusercontent.com/3000936/108786622-489f7d00-7574-11eb-9bbd-0b21addeafad.png)

![Screenshot2](https://user-images.githubusercontent.com/3000936/108786709-7edcfc80-7574-11eb-974b-e172eab71099.png)


if you try this, does it work for you?

**Comment by 1000i100** [comment]
I've just tried it : 
/ 200
/assets/css/reset.css 404
/assets/css/style.css 404
/assets/img/windows-logo.png 404
/assets/img/logo.png 404
/assets/img/apple-logo.png 404
/assets/img/linux-logo.png 404
/assets/img/wired.png 404
/assets/img/tor.png 404

**Comment by 1000i100** [comment]
Tested with and without http privacy header, with or without password.

**Comment by Rkmskmrobots** [comment]
Same, still not working and getting error when trying to view the site

**Comment by Rkmskmrobots** [comment]
Like, it works fine showing it as a website, but I can't get it to be viewable like an FTP site layout where it just shows folders and subfolders

**Comment by Rkmskmrobots** [comment]
Anytime I put JUST the "asset" folder into the website view it says 

"Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

**Comment by Kcchouette** [comment]
> Like, it works fine showing it as a website, but I can't get it to be viewable like an FTP site layout where it just shows folders and subfolders

@Rkmskmrobots so it shows you like my 2nd screenshot?

**Comment by Rkmskmrobots** [comment]
If I load just the files you listed, sort of. It doesn't load any of the assets and instead shows it in plain text.

![onionshareex](https://user-images.githubusercontent.com/37608972/109052208-361a6600-7690-11eb-82ab-cd63a9479fc3.PNG)

**Comment by Rkmskmrobots** [comment]
> > Like, it works fine showing it as a website, but I can't get it to be viewable like an FTP site layout where it just shows folders and subfolders
> 
> @Rkmskmrobots so it shows you like my 2nd screenshot?

So Ya, overall it seems like it won't even recognize the asset folder exists with or without the index.html

**Comment by 1000i100** [comment]
> So Ya, overall it seems like it won't even recognize the asset folder exists with or without the index.html

Yep, same here.

**Comment by sandyvb** [comment]
I'm having the same problems. Using Windows.

**Comment by Kcchouette** [comment]
@micahflee this problem is windows-related

here explanation that I saw:

https://github.com/micahflee/onionshare/blob/dfaa55d2a40edfb892e123f370f5d22b79e33d04/cli/onionshare_cli/web/send_base_mode.py#L58-L109

In this function, windows path finish by `\` instead of `/`

So at the end, the var `self.files` would contains something like this:
```
{'.git': 'C:/onionshare-website\\.git',
 '.git\\HEAD': 'C:/onionshare-website\\.git\\HEAD',
 '.git\\config': 'C:/onionshare-website\\.git\\config',
 '.git\\description': 'C:/onionshare-website\\.git\\description',
 '.git\\hooks': 'C:/onionshare-website\\.git\\hooks',
 '.git\\hooks\\applypatch-msg.sample': 'C:/onionshare-website\\.git\\hooks\\applypatch-msg.sample',
 '.git\\hooks\\commit-msg.sample': 'C:/onionshare-website\\.git\\hooks\\commit-msg.sample',
 '.git\\hooks\\fsmonitor-watchman.sample': 'C:/onionshare-website\\.git\\hooks\\fsmonitor-watchman.sample',
 '.git\\hooks\\post-update.sample': 'C:/onionshare-website\\.git\\hooks\\post-update.sample',
 '.git\\hooks\\pre-applypatch.sample': 'C:/onionshare-website\\.git\\hooks\\pre-applypatch.sample',
 '.git\\hooks\\pre-commit.sample': 'C:/onionshare-website\\.git\\hooks\\pre-commit.sample',
 '.git\\hooks\\pre-merge-commit.sample': 'C:/onionshare-website\\.git\\hooks\\pre-merge-commit.sample',
 '.git\\hooks\\pre-push.sample': 'C:/onionshare-website\\.git\\hooks\\pre-push.sample',
 '.git\\hooks\\pre-rebase.sample': 'C:/onionshare-website\\.git\\hooks\\pre-rebase.sample',
 '.git\\hooks\\pre-receive.sample': 'C:/onionshare-website\\.git\\hooks\\pre-receive.sample',
 '.git\\hooks\\prepare-commit-msg.sample': 'C:/onionshare-website\\.git\\hooks\\prepare-commit-msg.sample',
 '.git\\hooks\\push-to-checkout.sample': 'C:/onionshare-website\\.git\\hooks\\push-to-checkout.sample',
 '.git\\hooks\\update.sample': 'C:/onionshare-website\\.git\\hooks\\update.sample',
 '.git\\index': 'C:/onionshare-website\\.git\\index',
 '.git\\info': 'C:/onionshare-website\\.git\\info',
 '.git\\info\\exclude': 'C:/onionshare-website\\.git\\info\\exclude',
 '.git\\logs': 'C:/onionshare-website\\.git\\logs',
 '.git\\logs\\HEAD': 'C:/onionshare-website\\.git\\logs\\HEAD',
 '.git\\logs\\refs': 'C:/onionshare-website\\.git\\logs\\refs',
 '.git\\logs\\refs\\heads': 'C:/onionshare-website\\.git\\logs\\refs\\heads',
 '.git\\logs\\refs\\heads\\master': 'C:/onionshare-website\\.git\\logs\\refs\\heads\\master',
 '.git\\logs\\refs\\remotes': 'C:/onionshare-website\\.git\\logs\\refs\\remotes',
 '.git\\logs\\refs\\remotes\\origin': 'C:/onionshare-website\\.git\\logs\\refs\\remotes\\origin',
 '.git\\logs\\refs\\remotes\\origin\\HEAD': 'C:/onionshare-website\\.git\\logs\\refs\\remotes\\origin\\HEAD',
 '.git\\objects': 'C:/onionshare-website\\.git\\objects',
 '.git\\objects\\info': 'C:/onionshare-website\\.git\\objects\\info',
 '.git\\objects\\pack': 'C:/onionshare-website\\.git\\objects\\pack',
 '.git\\objects\\pack\\pack-52a9cd69a497042be89f011f573738eb4cc299a8.idx': 'C:/onionshare-website\\.git\\objects\\pack\\pack-52a9cd69a497042be89f011f573738eb4cc299a8.idx',
 '.git\\objects\\pack\\pack-52a9cd69a497042be89f011f573738eb4cc299a8.pack': 'C:/onionshare-website\\.git\\objects\\pack\\pack-52a9cd69a497042be89f011f573738eb4cc299a8.pack',
 '.git\\packed-refs': 'C:/onionshare-website\\.git\\packed-refs',
 '.git\\refs': 'C:/onionshare-website\\.git\\refs',
 '.git\\refs\\heads': 'C:/onionshare-website\\.git\\refs\\heads',
 '.git\\refs\\heads\\master': 'C:/onionshare-website\\.git\\refs\\heads\\master',
 '.git\\refs\\remotes': 'C:/onionshare-website\\.git\\refs\\remotes',
 '.git\\refs\\remotes\\origin': 'C:/onionshare-website\\.git\\refs\\remotes\\origin',
 '.git\\refs\\remotes\\origin\\HEAD': 'C:/onionshare-website\\.git\\refs\\remotes\\origin\\HEAD',
 '.git\\refs\\tags': 'C:/onionshare-website\\.git\\refs\\tags',
 '.gitignore': 'C:/onionshare-website\\.gitignore',
 '.htaccess': 'C:/onionshare-website\\.htaccess',
 'LICENSE': 'C:/onionshare-website\\LICENSE',
 'README.md': 'C:/onionshare-website\\README.md',
 'assets': 'C:/onionshare-website\\assets',
 'assets\\css': 'C:/onionshare-website\\assets\\css',
 'assets\\css\\gh-fork-ribbon.css': 'C:/onionshare-website\\assets\\css\\gh-fork-ribbon.css',
 'assets\\css\\normalize.css': 'C:/onionshare-website\\assets\\css\\normalize.css',
 'assets\\css\\reset.css': 'C:/onionshare-website\\assets\\css\\reset.css',
 'assets\\css\\style.css': 'C:/onionshare-website\\assets\\css\\style.css',
 'assets\\fonts': 'C:/onionshare-website\\assets\\fonts',
 'assets\\fonts\\RobotoSlab-Bold.woff': 'C:/onionshare-website\\assets\\fonts\\RobotoSlab-Bold.woff',
 'assets\\fonts\\RobotoSlab-Regular.woff': 'C:/onionshare-website\\assets\\fonts\\RobotoSlab-Regular.woff',
 'assets\\img': 'C:/onionshare-website\\assets\\img',
 'assets\\img\\apple-logo.png': 'C:/onionshare-website\\assets\\img\\apple-logo.png',
 'assets\\img\\fayerwayer.png': 'C:/onionshare-website\\assets\\img\\fayerwayer.png',
 'assets\\img\\genbeta.png': 'C:/onionshare-website\\assets\\img\\genbeta.png',
 'assets\\img\\gizmodo.png': 'C:/onionshare-website\\assets\\img\\gizmodo.png',
 'assets\\img\\linux-logo.png': 'C:/onionshare-website\\assets\\img\\linux-logo.png',
 'assets\\img\\logo.png': 'C:/onionshare-website\\assets\\img\\logo.png',
 'assets\\img\\lookatme.png': 'C:/onionshare-website\\assets\\img\\lookatme.png',
 'assets\\img\\omicrono.png': 'C:/onionshare-website\\assets\\img\\omicrono.png',
 'assets\\img\\tor.png': 'C:/onionshare-website\\assets\\img\\tor.png',
 'assets\\img\\windows-logo.png': 'C:/onionshare-website\\assets\\img\\windows-logo.png',
 'assets\\img\\wired.png': 'C:/onionshare-website\\assets\\img\\wired.png',
 'assets\\img\\xakep.png': 'C:/onionshare-website\\assets\\img\\xakep.png',
 'assets\\img\\zuckerberg.png': 'C:/onionshare-website\\assets\\img\\zuckerberg.png',
 'favicon.ico': 'C:/onionshare-website\\favicon.ico',
 'index.html': 'C:/onionshare-website\\index.html'
```

---

To quick & dirty fix, I add `.replace("\\", "/")` each time it save something to the var `self.files`; eg
```
	                    # Add the files in this dir
	                    for nested_filename in nested_filenames:
	                        self.files[
	                            os.path.join(normalized_root, nested_filename).replace("\\", "/")
	                        ] = os.path.join(root, nested_filename).replace("\\", "/")
```

**Comment by efialtos** [comment]
Probably it is relevant to https://github.com/micahflee/onionshare/issues/1308

**Comment by Rkmskmrobots** [comment]
> @micahflee this problem is windows-related
> 
> here explanation that I saw:
> 
> https://github.com/micahflee/onionshare/blob/dfaa55d2a40edfb892e123f370f5d22b79e33d04/cli/onionshare_cli/web/send_base_mode.py#L58-L109
> 
> In this function, windows path finish by `\` instead of `/`
> 
> So at the end, the var `self.files` would contains something like this:
> 
> ```
>  'LICENSE': 'C:/onionshare-website\\LICENSE',
>  'README.md': 'C:/onionshare-website\\README.md',
>  'assets': 'C:/onionshare-website\\assets',
>  'assets\\css': 'C:/onionshare-website\\assets\\css',
>  'assets\\css\\gh-fork-ribbon.css': 'C:/onionshare-website\\assets\\css\\gh-fork-ribbon.css',
>  'assets\\css\\normalize.css': 'C:/onionshare-website\\assets\\css\\normalize.css',
>  'assets\\css\\reset.css': 'C:/onionshare-website\\assets\\css\\reset.css',
>  'assets\\css\\style.css': 'C:/onionshare-website\\assets\\css\\style.css',
>  'assets\\fonts': 'C:/onionshare-website\\assets\\fonts',
>  'assets\\fonts\\RobotoSlab-Bold.woff': 'C:/onionshare-website\\assets\\fonts\\RobotoSlab-Bold.woff',
>  'assets\\fonts\\RobotoSlab-Regular.woff': 'C:/onionshare-website\\assets\\fonts\\RobotoSlab-Regular.woff',
>  'assets\\img': 'C:/onionshare-website\\assets\\img',
>  'assets\\img\\apple-logo.png': 'C:/onionshare-website\\assets\\img\\apple-logo.png',
>  'assets\\img\\fayerwayer.png': 'C:/onionshare-website\\assets\\img\\fayerwayer.png',
>  'assets\\img\\genbeta.png': 'C:/onionshare-website\\assets\\img\\genbeta.png',
>  'assets\\img\\gizmodo.png': 'C:/onionshare-website\\assets\\img\\gizmodo.png',
>  'assets\\img\\linux-logo.png': 'C:/onionshare-website\\assets\\img\\linux-logo.png',
>  'assets\\img\\logo.png': 'C:/onionshare-website\\assets\\img\\logo.png',
>  'assets\\img\\lookatme.png': 'C:/onionshare-website\\assets\\img\\lookatme.png',
>  'assets\\img\\omicrono.png': 'C:/onionshare-website\\assets\\img\\omicrono.png',
>  'assets\\img\\tor.png': 'C:/onionshare-website\\assets\\img\\tor.png',
>  'assets\\img\\windows-logo.png': 'C:/onionshare-website\\assets\\img\\windows-logo.png',
>  'assets\\img\\wired.png': 'C:/onionshare-website\\assets\\img\\wired.png',
>  'assets\\img\\xakep.png': 'C:/onionshare-website\\assets\\img\\xakep.png',
>  'assets\\img\\zuckerberg.png': 'C:/onionshare-website\\assets\\img\\zuckerberg.png',
>  'favicon.ico': 'C:/onionshare-website\\favicon.ico',
>  'index.html': 'C:/onionshare-website\\index.html'
> ```
> 
> To quick & dirty fix, I add `.replace("\\", "/")` each time it saves something to the var `self.files`; eg
> 
> ```
> 	                    # Add the files in this dir
> 	                    for nested_filename in nested_filenames:
> 	                        self.files[
> 	                            os.path.join(normalized_root, nested_filename).replace("\\", "/")
> 	                        ] = os.path.join(root, nested_filename).replace("\\", "/")
> ```

I apologize since I don't have much programming experience, but how would I go about fixing this or is this going to fixed soon in a new update for the windows version?

**Comment by mig5** [comment]
@micahflee is this a bug in Windows and should be considered for the 2.3.2 milestone?

**Comment by micahflee** [comment]
I'll need to take some time looking into it, but I just added the 2.3.2 milestone tag.
