### ISSUE TITLE
Flatpak App Not Found

### ISSUE THREAD

**Issue by snakyjake1** [micahflee/onionshare#1290]
The link to install the OnionShare Flatpak application is broken

From:
https://docs.onionshare.org/2.3/en/install.html#install-in-linux

To:
https://flathub.org/apps/details/org.onionshare.OnionShare

![image](https://user-images.githubusercontent.com/8312560/108779206-5f65b580-751b-11eb-8e23-4e60571d9654.png)

**Comment by micahflee** [comment]
This is coming soon! Just need to get the flathub app finished and approved https://github.com/flathub/flathub/pull/2129

**Comment by Eonfge** [comment]
It's up. Everybody can now use the latest Onion Share using Flathub
