### ISSUE TITLE
Too long usernames in chat cause cookie / state corruption

### ISSUE THREAD

**Issue by s-rah** [micahflee/onionshare#1291]
You might want to consider setting a server-side limit on username setting. Too long usernames seem to both mess up the session cookie + JS messages and trigger a gui-side exception:

    /snap/onionshare/3/lib/python3.6/site-packages/werkzeug/wrappers/base_response.py:479: UserWarning: The "b'session'" cookie is too large: the value was 11290 bytes but the header required 26 extra bytes. The final size was 11316 bytes but the limit is 4093 bytes. Browsers may silently ignore cookies larger than this.
      samesite=samesite,
    Traceback (most recent call last):
      File "/snap/onionshare/3/lib/python3.6/site-packages/onionshare/tab/tab.py", line 556, in timer_callback
        mode.handle_request_individual_file_started(event)
      File "/snap/onionshare/3/lib/python3.6/site-packages/onionshare/tab/mode/__init__.py", line 479, in handle_request_individual_file_started
        self.toggle_history.update_indicator(True)
    AttributeError: 'ChatMode' object has no attribute 'toggle_history'

**Comment by SaptakS** [comment]
@s-rah That's a good point. Thanks! I will look into it.

**Comment by whew** [comment]
I get the exact same traceback when I make a request that results in a 404.

**Comment by mig5** [comment]
The `toggle_history` exception is resolved by #1353
