### ISSUE TITLE
Onionshare won't appear after installment

### ISSUE THREAD

**Issue by OmegaSquadron27** [micahflee/onionshare#1297]
Not to long ago, I decided to download the installer. After that, I then clicked on the installer to install Onionshare.

However, I noticed that after installation, nothing appeared. I looked around to see if it installed elsewhere, but couldn't find it. I've installed a few more times thinking that it was just some glitch, but nope. Any way around this?

**Comment by micahflee** [comment]
What operating system are you using?

**Comment by Variok-cmd** [comment]
I also seem to be having issues, after running the installer some of the files are saved in my local app data folder but it does not seem to have run a setup script. This is on windows.

**Comment by Variok-cmd** [comment]
If OP is using windows, upon executing the installer I struggled to find the files also. In my case they had been saved in my appdata local folder, and the shortcut was found in appdata roaming. Hope this helps.
