### ISSUE TITLE
Set password to custom password

### ISSUE THREAD

**Issue by trymeouteh** [micahflee/onionshare#1303]
Please allow for the option to set a custom password instead of having the password generated for us.

**Comment by micahflee** [comment]
What's the benefit of this?

Right now the random passwords are 2 words from a wordlist of 7776 words, which means the passwords have ~25.8 bits of entropy, so there are about 60.4 million possible passwords. After 20 wrong guesses the server shuts down. This is quite secure.

If we allow users to set custom passwords, they might choose really insecure passwords, and it would decrease the security that passwords provide.
