### ISSUE TITLE
Display URL without username and password

### ISSUE THREAD

**Issue by trymeouteh** [micahflee/onionshare#1304]
When you are sharing a file or recieving files, please also display the URL without the username and password which can be easily copied by clicking a button and a button to display its QR code

**Comment by micahflee** [comment]
What do you mean?

If you check "Don't use a password" and then start a server, it will display the URL without a password.

If you want a password though, you're going to need to send people the password as well, and it's simpler to copy the password as part of the URL.

**Comment by mig5** [comment]
For most people it's convenient having the user/pass automatically copied with the URL, so I'm against either:

a) breaking this into separate things to copy/paste (adds effort for most users)
b) adding the same URL as is already displayed, but display it separately with its own copy button or own QR code (clutters the UI)
c) any sort of 'setting' that allows toggling the behavior (clutters the Settings UI)

This is a bit like https://github.com/micahflee/onionshare/issues/952 (and #1303) - these sorts of customization either clutter the UI, risk reducing security, or add effort for the majority of users.

Using public mode ('Don't use a password') or using persistent mode (same password each time, so only needs to be copied and shared once) are likely simpler ways (albeit with their own trade-offs) to avoid the nuisance of having to share the passwords all the time. I think this strikes a reasonable balance 

Finally: you can actually click and highlight *just* the onion address in the display, and copy it to your clipboard - without the username/password. E.G, the display of the URL itself is 'selectable'. So in fact, I think we already provide a way to do this even with the default mode.
