### ISSUE TITLE
Onionshare v2.3.1 not working on macOS v10.13.6

### ISSUE THREAD

**Issue by spiderman666** [micahflee/onionshare#1307]
App gives unconfirmed developer identity when trying to open.  Can use control+open to bypass the warning and open but then app crash closes after a few seconds.  No errors or logs found for onionshare when searching via console.app

![onionshare](https://user-images.githubusercontent.com/7891269/109460513-9861d500-7a9b-11eb-93ec-c252e28f0c6c.jpg)

**Comment by micahflee** [comment]
macOS 10.13 is unsupported by Apple as of December 2020: https://en.wikipedia.org/wiki/MacOS_High_Sierra

So OnionShare will also not support it. It should work fine in newer versions of macOS.
