### ISSUE TITLE
Cannot see configuration windows when running in standalone Qubes/Debian

### ISSUE THREAD

**Issue by davterra** [micahflee/onionshare#1310]
Running Qubes 4.03, in a standalone Debian Qube, I installed Onionshare using snapd package. 
When I attempt to start Onionshare, I get a couple of windows open that I assume are asking for configuration choices, but I cannot see any text within the windows. (Screenshots attached). My first thought was "not enough ram", so I restarted the Qube (It has 6gb ram allocated) and tried again to open Onionshare as the only app running in the Qube. Same result. 
![onionshare1](https://user-images.githubusercontent.com/37884409/109662974-76f6fc80-7b20-11eb-9758-b59d9f3d4c21.png)
![onionshare2](https://user-images.githubusercontent.com/37884409/109662987-78c0c000-7b20-11eb-885c-09feac2dc857.png)

**Comment by mig5** [comment]
Hmm, I don't reproduce this on a Debian 10 Qubes 4.1 VM with OnionShare installed via snap 2.49.2 from https://snapcraft.io/install/onionshare/debian#install .
![Screenshot_2021-04-28_15-03-50](https://user-images.githubusercontent.com/99173/116349278-fb20e400-a832-11eb-9899-bf9807cca30c.png)

**Comment by mig5** [comment]
I still cannot reproduce this, even in a Standalone (not a disposable) Qube on Qubes 4.0, also running Debian 10, max 4000MB of RAM allocated.

My only guess it's either a Qubes issue, a Debian version difference, some snap version issue/difference.

```
user@oniontest:~$ snap --version
snap    2.49.2
snapd   2.49.2
series  16
debian  10
kernel  5.4.98-1.fc25.qubes.x86_64
```

> When I attempt to start Onionshare, I get a couple of windows open that I assume are asking for configuration choices, but I cannot see any text within the windows.

This already sounds suspicious like something bigger is wrong. The only extra window that would open, normally, is a progress dialog as OnionShare connects to its bundled Tor, and the only button in that window is a Cancel button (there is no 'exclamation' icon). 

So, if you got some sort of Alert dialog as the original screenshot suggests, then there maybe is a bigger problem.

If it happens for you again, please try running OnionShare from the command line with some verbosity enabled, something like this:

```
/snap/bin/onionshare --verbose
```

.. and then re-open the issue or open a new one. Thanks!
