### ISSUE TITLE
Automatic check for updates should use onionshare.org, not GitHub

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#1377]
The code that checks for available updates in Windows and macOS checks GitHub releases to see what the latest release is, then links to the GitHub release page for that release when you click download update.

Instead it should check the onion site verison of https://onionshare.org/latest-version.txt, and link to https://onionshare.org/.

**Comment by BotMaster3000** [comment]
When I am not misinterpreting the Code from the update_checker.py, then the current develop-branch already checks for the current version of OnionShare via the Tor-Adress of OnionShare. 
So the only thing remaining would be to redirect to onionshare.org instead of Github.
