### ISSUE TITLE
Write OnionShare documentation

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#143]
OnionShare can be used for diverse purposes. I think the most common use of it right now is to send files between friends and colleagues, as an alternative to using email or a file sharing service, in which case anonymity is not too important.

However it can also be used in much higher-risk scenarios, like by a source leaking documents to a journalist. There have been feature requests to help make sure the user protects their anonymity for the latter case (#79, #94), but I think other tools besides OnionShare are better fit for the job of modifying files before sending them.

Instead there should be documentation, maybe on https://onionshare.org or in the github wiki, or even in this source repository like https://github.com/freedomofpress/securedrop does, that explains how to protect your anonymity when using OnionShare if it's in your threat model.

**Comment by freddymartinez9** [comment]
Hi Micah how is this issue coming along? I have experience writing documentation for open-source projects, I can volunteer to help.

**Comment by commandnotfound** [comment]
It would also be helpful if there was a UNIX-style `man` page for macOS and Linux installs, such that when you run `man onionshare` you can get helpful documentation without visiting https://onionshare.org/.

**Comment by micahflee** [comment]
Hey @fred-a-kemp thank for volunteering to help, nearly two years ago :). Still interested? I think a great place to put all of the documentation is on the new wiki: https://github.com/micahflee/onionshare/wiki

**Comment by micahflee** [comment]
@commandnotfound I agree about man pages as well. I think it would be difficult to support in OSX, since OnionShare is shipped as an app bundle in /Applications and isn't installed using a package manager. But man pages for Linux would be great. I think they could briefly describe the project, and all of the command line arguments.

**Comment by fred-a-kemp** [comment]
Micah Lee:
> Hey

Hi!

> @fred-a-kemp

FWIW, fred-a-kemp == anonym (from Tails). :)

> thank for volunteering to help, nearly two years ago :). Still
> interested? I think a great place to put all of the documentation is
> on the new wiki: https://github.com/micahflee/onionshare/wiki

I do not recall volunteering. I think you mixed me up with
@freddymartinez9.

Cheers!

**Comment by micahflee** [comment]
Haha oops, sorry @fred-a-kemp. Yes, I totally meant @freddymartinez9. Autocorrect mistake.

**Comment by freddymartinez9** [comment]
@micahflee Yes I'm still interested in helping. I'll get the latest version and start adding screenshots and more documentation in the new year.

**Comment by micahflee** [comment]
There's enough documentation in the wiki that I think this issue can be closed-- but of course, more documentation is always welcome.
