### ISSUE TITLE
Complete confidentiality through use of HidServAuth

### ISSUE THREAD

**Issue by HulaHoopWhonix** [micahflee/onionshare#144]
I think it important to have Onionshare use, by default, the Authentication feature of Hidden services to stop anyone from accessing the data being transferred unless given permission. Becuase Hidden Service addresses are not secret, any unintended snooping by a Hidden Service Directory Authority that could crawl the address does happen, for example as mentioned here: https://lists.torproject.org/pipermail/tor-talk/2014-September/034751.html

The needed fields for the cookie secret key could be added in the gui. (In our vm transparent proxy model, If the authentication cookie is long we can safely transfer it to the workstation via a readonly iso image or shared folders so that's not a problem.)

Of course I believe this should still be optional because there might be a situation where a leaker wants as many people to get the data as possible with no particular need for confidentiality for example the Gama International hacker who used DropBox. 
[He used Whonix btw :)]

References:
Specific Tor features from manual https://www.torproject.org/docs/tor-manual.html.en
HiddenServiceAuthorizeClient
HidServAuth

https://gitweb.torproject.org/torspec.git/blob/HEAD:/proposals/121-hidden-service-authentication.txt

**Comment by micahflee** [comment]
This was never resolved.

**Comment by micahflee** [comment]
In the future all hidden services that onionshare creates will be ephemeral. It looks like stem's [create_ephemeral_hidden_service()](https://stem.torproject.org/api/control.html#stem.control.Controller.create_ephemeral_hidden_service) method doesn't have any way to specify the `HiddenServiceAuthorizeClient` option. I wonder if ephemeral hidden services don't support stealth, or if just stem doesn't?

**Comment by adrelanos** [comment]
@azadi any idea?

**Comment by micahflee** [comment]
As of stem 1.5.0, the `create_ephemeral_hidden_service` function has added the `basic_auth` argument, which allows for ephemeral stealth onion services: https://stem.torproject.org/api/control.html#stem.control.Controller.create_ephemeral_hidden_service

This means that this feature should be pretty easy to implement now. Related to #313.
