### ISSUE TITLE
Consider switching to twisted

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#149]
There's a discussion in #117 about refactoring OnionShare to use twisted, specifically to be able to switch from Flask to twisted-web. It turns out that that's not needed anymore to fix #117, but switching to twisted is still an option.

One reason to use twisted would be to be able to use txtorcon, which can easily launch a new tor process and start a hidden service, which could effectively remove the TBB dependency and also solve #130 and #87 (except the Windows and OSX versions would need to bundle Tor, which means pushing emergency onionshare releases each time there's a Tor security release). It might be possible to do this without switching to twisted, however.

This is the new issue to discuss refactoring to use twisted.

**Comment by meejah** [comment]
I just noticed this thread, if you need any help integrating txtorcon or if it lacks features you need, don't hesitate to ask.

One thing that might help is that Twisted does have decent OS integration, e.g. can run as a proper windows service on Windows, and a systemd daemon on Linux. I understand that "Twisted" versus "no dependency" is a big change, and I'm pretty biased ;) so ... but if you do decide to switch, please ping me and I'm happy to help.

Note also that there's experimental support coming for "ephemeral" hidden-services in recent Tor and a branch of txtorcon to support this -- this will allow *much* easier integration with any "system" Tor, and the possibility to have onion keys that have never seen a disk (of course, you can do that now with TMPDIR=/dev/shm).

**Comment by micahflee** [comment]
Because of #178 and ephemeral hidden services, I don't think there's much incentive to switch from flask to twisted-web anymore.
