### ISSUE TITLE
Write AppArmor profile for OnionShare

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#171]

**Comment by u451f** [comment]
At Tails we've started to write some profiles. I'm gonna review them and will propose them upstream when I'm done.

See profiles for onionshare{,-gui} and an abstraction they can share:
* https://git-tails.immerda.ch/tails/tree/config/chroot_local-includes/etc/apparmor.d/usr.bin.onionshare?h=feature/7870-include_onionshare
* https://git-tails.immerda.ch/tails/tree/config/chroot_local-includes/etc/apparmor.d/usr.bin.onionshare-gui?h=feature/7870-include_onionshare
* https://git-tails.immerda.ch/tails/tree/config/chroot_local-includes/etc/apparmor.d/abstractions/onionshare?h=feature/7870-include_onionshare

**Comment by u451f** [comment]
If you want to, you can assign this issue to me.
