### ISSUE TITLE
Generate metalink file upon sharing (for robust pause/resume and data integrity verification)

### ISSUE THREAD

**Issue by sptankard** [micahflee/onionshare#175]
I imagine this will be quite complex to implement and will likely require extensive changes to the codebase, but I think it is potentially a very valuable long-term goal.

Note: relates to #123.  Also, this might be better split into two issues.

#### Rationale

As it stands, OnionShare is excellent for transferring small files, but large files present problems (interruption of transfer, potential for data corruption).  This is unfortunate, because while there are many existing methods for one-off transferring of small files between individuals (email, IM), there are much fewer methods for transferring large files. Bittorrent comes to mind, but has many downsides for privacy.

It would be amazing if OnionShare could be used to incrementally transfer large files (> 5gb, even 100 gb...).

**Pause/resume.** An essential for transferring large files is the ability to pause the transfer and resume later (whether from the same HS or a different one).  Torrents achieve this by chunking the files and using metadata to keep track of the download state.  Perhaps something similar could be implemented for OnionShare.

**Verifying data integrity.** Data integrity checking is already provided somewhat by the display of a checksum, which the user can then manually verify.  Automating this verification would improve the user experience.

#### Considerations/implications

This whole feature-set assumes a much more active role on the receiving side than OnionShare currently implements.

There are at least three conceivable ways to implement this:
* Javascript in the HS-served webpage
* An OnionShare browser extension for TBB
* Implement the receiving functionality in OnionShare core itself (download happens through OnionShare UI instead of TBB)

JS in the webpage preserves the current user experience, however it is technically difficult to implement because webpage-JS is sandboxed.  Nevertheless, such a thing may not be impossible:
https://stackoverflow.com/questions/3067774/how-to-create-a-file-using-javascript-in-mozilla-firefox

An OnionShare browser extension is a middle path, preserving the current user experience while changing the architecture of OnionShare significantly.  However, (1) the receiving user has to download two separate pieces of software, TBB and OnionShare extension, and (2) for security reasons, the Tor Project might not appreciate the promotion of extensions specifically for TBB.

As such, I think the browser extension avenue is the *least* desirable method.

Finally, implementing this functionality in the OnionShare core implies a major change to both the code and the manner of use. However, this might end up being desirable, long-term: once #153 is resolved, the dependency on TBB could be dropped entirely.

This would put OnionShare in somewhat more direct competition with projects like [Anomos] (http://anomos.info/), or even I2P/GNUnet etc., but the "one-time only", "from me to you" use-case is something that these projects do not address well.

**Comment by sptankard** [comment]
A better idea on how to implement this:

1. OnionShare generates a metalink file upon sharing, and makes it available on the server.
2. The receiver torifies a download manager such as curl, [aria2] (http://aria2.sourceforge.net/) or [uGet] (http://ugetdm.com/) to access the metalink file and perform the download.  (This assumes these downloaders have torification-compliant behavior -- don't try to jailbreak the environment, reveal IP, etc.)

OnionShare just has to generate the metalink file. Nothing else.

Users downloading small files can use the TBB webpage method, and users accessing larger files can use their preferred download manager (put recommendations for Tor-friendly ones in the OnionShare docs).

[metalink-library] (https://code.google.com/p/metalink-library/) implements a metalink generator and parser in [under 3,000 lines of Python (GPL v2.1+)] (https://code.google.com/p/metalink-library/source/browse/trunk/metalink.py).  OnionShare needs only the generator part.

Advantages:
* Preserves OnionShare's current use-case/philosophy and user experience entirely
* Only a small change to the codebase
* Uses standard technologies
* Flexible -- users may even use a Firefox download manager add-on (if there is a TBB-friendly one)
* Compared to webpage-JS: more secure. Receiver does not have to execute any code sent by sender.

Disadvantages:
* Downloaders often do not work well with Tor. Curl has issues, but [can work with the proper configuration] (https://trac.torproject.org/projects/tor/ticket/6542).

Metalink
http://www.metalinker.org/
https://tools.ietf.org/html/rfc5854

aria2 also provides Python bindings
http://aria2.sourceforge.net/manual/en/html/aria2c.html#rpc-interface
http://xyne.archlinux.ca/projects/python3-aria2jsonrpc/

**Comment by micahflee** [comment]
This would increase the complexity of onionshare by a lot, and require a custom client to download files besides just Tor Browser (either a Tor Browser extension or some downloader program). I like the idea of being able to support pause/resume, but I think one of the best things about onionshare is how incredibly simple it is, so I'm not sure that it makes sense to implement this.

**Comment by micahflee** [comment]
Like I said before, I don't think it makes sense to implement this because I want the receiver to only need Tor Browser, and no extra software installed.
