### ISSUE TITLE
Build fails on Ubuntu vivid

### ISSUE THREAD

**Issue by pde** [micahflee/onionshare#176]
```
./build_deb.sh 
rm: cannot remove ‘deb_dist’: No such file or directory
/usr/lib/python2.7/dist-packages/setuptools/dist.py:282: UserWarning: Normalizing '0.7dev' to '0.7.dev0'
  normalized_version,
running bdist_deb
running sdist_dsc
running egg_info
writing onionshare.egg-info/PKG-INFO
writing top-level names to onionshare.egg-info/top_level.txt
writing dependency_links to onionshare.egg-info/dependency_links.txt
reading manifest file 'onionshare.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'onionshare/strings.json'
writing manifest file 'onionshare.egg-info/SOURCES.txt'
running sdist
warning: sdist: standard file not found: should have one of README, README.rst, README.txt

running check
creating onionshare-0.7.dev0
creating onionshare-0.7.dev0/bin
creating onionshare-0.7.dev0/images
creating onionshare-0.7.dev0/locale
creating onionshare-0.7.dev0/onionshare
creating onionshare-0.7.dev0/onionshare.egg-info
creating onionshare-0.7.dev0/onionshare_gui
creating onionshare-0.7.dev0/setup
creating onionshare-0.7.dev0/test
making hard links in onionshare-0.7.dev0...
hard linking BUILD.md -> onionshare-0.7.dev0
hard linking LICENSE -> onionshare-0.7.dev0
hard linking MANIFEST.in -> onionshare-0.7.dev0
hard linking README.md -> onionshare-0.7.dev0
hard linking setup.cfg -> onionshare-0.7.dev0
hard linking setup.py -> onionshare-0.7.dev0
hard linking version -> onionshare-0.7.dev0
hard linking bin/onionshare -> onionshare-0.7.dev0/bin
hard linking bin/onionshare-gui -> onionshare-0.7.dev0/bin
hard linking images/drop_files.png -> onionshare-0.7.dev0/images
hard linking images/logo.png -> onionshare-0.7.dev0/images
hard linking images/server_started.png -> onionshare-0.7.dev0/images
hard linking images/server_stopped.png -> onionshare-0.7.dev0/images
hard linking images/server_working.png -> onionshare-0.7.dev0/images
hard linking locale/de.json -> onionshare-0.7.dev0/locale
hard linking locale/en.json -> onionshare-0.7.dev0/locale
hard linking locale/es.json -> onionshare-0.7.dev0/locale
hard linking locale/fi.json -> onionshare-0.7.dev0/locale
hard linking locale/fr.json -> onionshare-0.7.dev0/locale
hard linking locale/it.json -> onionshare-0.7.dev0/locale
hard linking locale/nl.json -> onionshare-0.7.dev0/locale
hard linking locale/no.json -> onionshare-0.7.dev0/locale
hard linking locale/pt.json -> onionshare-0.7.dev0/locale
hard linking locale/ru.json -> onionshare-0.7.dev0/locale
hard linking locale/tr.json -> onionshare-0.7.dev0/locale
hard linking onionshare/404.html -> onionshare-0.7.dev0/onionshare
hard linking onionshare/__init__.py -> onionshare-0.7.dev0/onionshare
hard linking onionshare/helpers.py -> onionshare-0.7.dev0/onionshare
hard linking onionshare/index.html -> onionshare-0.7.dev0/onionshare
hard linking onionshare/onionshare.py -> onionshare-0.7.dev0/onionshare
hard linking onionshare/socks.py -> onionshare-0.7.dev0/onionshare
hard linking onionshare/strings.py -> onionshare-0.7.dev0/onionshare
hard linking onionshare/web.py -> onionshare-0.7.dev0/onionshare
hard linking onionshare.egg-info/PKG-INFO -> onionshare-0.7.dev0/onionshare.egg-info
hard linking onionshare.egg-info/SOURCES.txt -> onionshare-0.7.dev0/onionshare.egg-info
hard linking onionshare.egg-info/dependency_links.txt -> onionshare-0.7.dev0/onionshare.egg-info
hard linking onionshare.egg-info/top_level.txt -> onionshare-0.7.dev0/onionshare.egg-info
hard linking onionshare_gui/__init__.py -> onionshare-0.7.dev0/onionshare_gui
hard linking onionshare_gui/common.py -> onionshare-0.7.dev0/onionshare_gui
hard linking onionshare_gui/downloads.py -> onionshare-0.7.dev0/onionshare_gui
hard linking onionshare_gui/file_selection.py -> onionshare-0.7.dev0/onionshare_gui
hard linking onionshare_gui/onionshare_gui.py -> onionshare-0.7.dev0/onionshare_gui
hard linking onionshare_gui/options.py -> onionshare-0.7.dev0/onionshare_gui
hard linking onionshare_gui/server_status.py -> onionshare-0.7.dev0/onionshare_gui
hard linking setup/onionshare.desktop -> onionshare-0.7.dev0/setup
hard linking setup/onionshare80.xpm -> onionshare-0.7.dev0/setup
hard linking test/test_helpers.py -> onionshare-0.7.dev0/test
copying setup.cfg -> onionshare-0.7.dev0
Writing onionshare-0.7.dev0/setup.cfg
Creating tar archive
removing 'onionshare-0.7.dev0' (and everything under it)
Traceback (most recent call last):
  File "setup.py", line 87, in <module>
    'locale/tr.json'
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/stdeb/command/bdist_deb.py", line 22, in run
    self.run_command('sdist_dsc')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/stdeb/command/sdist_dsc.py", line 72, in run
    assert actual_package_dirname==expected_package_dirname
AssertionError

To install, run:
sudo dpkg -i deb_dist/onionshare_0.7dev-1_all.deb
```

**Comment by Zaxscdvf** [comment]
It still works for me.

backbox@backbox:~/onionshare$ ./build_deb.sh
rm: cannot remove ‘deb_dist’: No such file or directory
running bdist_deb
running sdist_dsc
running egg_info
creating onionshare.egg-info
writing onionshare.egg-info/PKG-INFO
writing top-level names to onionshare.egg-info/top_level.txt
writing dependency_links to onionshare.egg-info/dependency_links.txt
writing manifest file 'onionshare.egg-info/SOURCES.txt'
reading manifest file 'onionshare.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'onionshare/strings.json'
writing manifest file 'onionshare.egg-info/SOURCES.txt'
CALLING dpkg-source -b onionshare-0.7dev (in dir deb_dist)
dpkg-source: info: using options from onionshare-0.7dev/debian/source/options: --extend-diff-ignore=\.egg-info
dpkg-source: info: using source format `3.0 (quilt)'
dpkg-source: info: building onionshare using existing ./onionshare_0.7dev.orig.tar.gz
dpkg-source: info: building onionshare in onionshare_0.7dev-1.debian.tar.gz
dpkg-source: info: building onionshare in onionshare_0.7dev-1.dsc
dpkg-source: warning: extracting unsigned source package (onionshare_0.7dev-1.dsc)
dpkg-source: info: extracting onionshare in onionshare-0.7dev
dpkg-source: info: unpacking onionshare_0.7dev.orig.tar.gz
dpkg-source: info: unpacking onionshare_0.7dev-1.debian.tar.gz
dpkg-buildpackage: source package onionshare
dpkg-buildpackage: source version 0.7dev-1
dpkg-buildpackage: source distribution trusty
dpkg-buildpackage: source changed by Micah Lee <micah@micahflee.com>
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build onionshare-0.7dev
dpkg-source: info: using options from onionshare-0.7dev/debian/source/options: --extend-diff-ignore=\.egg-info
 fakeroot debian/rules clean
dh clean --with python2 --buildsystem=python_distutils
   dh_testdir -O--buildsystem=python_distutils
   dh_auto_clean -O--buildsystem=python_distutils
pyversions: missing X(S)-Python-Version in control file, fall back to debian/pyversions
pyversions: missing debian/pyversions file, fall back to supported versions
running clean
'build/lib.linux-x86_64-2.7' does not exist -- can't clean it
'build/bdist.linux-x86_64' does not exist -- can't clean it
'build/scripts-2.7' does not exist -- can't clean it
   dh_clean -O--buildsystem=python_distutils
 debian/rules build
dh build --with python2 --buildsystem=python_distutils
   dh_testdir -O--buildsystem=python_distutils
   dh_auto_configure -O--buildsystem=python_distutils
   dh_auto_build -O--buildsystem=python_distutils
pyversions: missing X(S)-Python-Version in control file, fall back to debian/pyversions
pyversions: missing debian/pyversions file, fall back to supported versions
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/onionshare
copying onionshare/web.py -> build/lib.linux-x86_64-2.7/onionshare
copying onionshare/strings.py -> build/lib.linux-x86_64-2.7/onionshare
copying onionshare/socks.py -> build/lib.linux-x86_64-2.7/onionshare
copying onionshare/onionshare.py -> build/lib.linux-x86_64-2.7/onionshare
copying onionshare/helpers.py -> build/lib.linux-x86_64-2.7/onionshare
copying onionshare/__init__.py -> build/lib.linux-x86_64-2.7/onionshare
creating build/lib.linux-x86_64-2.7/onionshare_gui
copying onionshare_gui/server_status.py -> build/lib.linux-x86_64-2.7/onionshare_gui
copying onionshare_gui/options.py -> build/lib.linux-x86_64-2.7/onionshare_gui
copying onionshare_gui/onionshare_gui.py -> build/lib.linux-x86_64-2.7/onionshare_gui
copying onionshare_gui/file_selection.py -> build/lib.linux-x86_64-2.7/onionshare_gui
copying onionshare_gui/downloads.py -> build/lib.linux-x86_64-2.7/onionshare_gui
copying onionshare_gui/common.py -> build/lib.linux-x86_64-2.7/onionshare_gui
copying onionshare_gui/__init__.py -> build/lib.linux-x86_64-2.7/onionshare_gui
running egg_info
writing onionshare.egg-info/PKG-INFO
writing top-level names to onionshare.egg-info/top_level.txt
writing dependency_links to onionshare.egg-info/dependency_links.txt
reading manifest file 'onionshare.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'onionshare/strings.json'
writing manifest file 'onionshare.egg-info/SOURCES.txt'
copying onionshare/404.html -> build/lib.linux-x86_64-2.7/onionshare
copying onionshare/index.html -> build/lib.linux-x86_64-2.7/onionshare
running build_scripts
creating build/scripts-2.7
copying and adjusting bin/onionshare -> build/scripts-2.7
copying and adjusting bin/onionshare-gui -> build/scripts-2.7
changing mode of build/scripts-2.7/onionshare from 664 to 775
changing mode of build/scripts-2.7/onionshare-gui from 664 to 775
   dh_auto_test -O--buildsystem=python_distutils
 fakeroot debian/rules binary
dh binary --with python2 --buildsystem=python_distutils
   dh_testroot -O--buildsystem=python_distutils
   dh_prep -O--buildsystem=python_distutils
   dh_auto_install -O--buildsystem=python_distutils
pyversions: missing X(S)-Python-Version in control file, fall back to debian/pyversions
pyversions: missing debian/pyversions file, fall back to supported versions
running install
running build
running build_py
running egg_info
writing onionshare.egg-info/PKG-INFO
writing top-level names to onionshare.egg-info/top_level.txt
writing dependency_links to onionshare.egg-info/dependency_links.txt
reading manifest file 'onionshare.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'onionshare/strings.json'
writing manifest file 'onionshare.egg-info/SOURCES.txt'
running build_scripts
running install_lib
creating /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr
creating /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/lib
creating /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/lib/python2.7
creating /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/lib/python2.7/dist-packages
creating /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/lib/python2.7/dist-packages/onionshare_gui
copying build/lib.linux-x86_64-2.7/onionshare_gui/__init__.py -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/lib/python2.7/dist-packages/onionshare_gui
copying build/lib.linux-x86_64-2.7/onionshare_gui/common.py -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/lib/python2.7/dist-packages/onionshare_gui
copying build/lib.linux-x86_64-2.7/onionshare_gui/downloads.py -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/lib/python2.7/dist-packages/onionshare_gui
copying build/lib.linux-x86_64-2.7/onionshare_gui/file_selection.py -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/lib/python2.7/dist-packages/onionshare_gui
copying build/lib.linux-x86_64-2.7/onionshare_gui/onionshare_gui.py -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/lib/python2.7/dist-packages/onionshare_gui
copying build/lib.linux-x86_64-2.7/onionshare_gui/options.py -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/lib/python2.7/dist-packages/onionshare_gui
copying build/lib.linux-x86_64-2.7/onionshare_gui/server_status.py -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/lib/python2.7/dist-packages/onionshare_gui
creating /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/lib/python2.7/dist-packages/onionshare
copying build/lib.linux-x86_64-2.7/onionshare/index.html -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/lib/python2.7/dist-packages/onionshare
copying build/lib.linux-x86_64-2.7/onionshare/404.html -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/lib/python2.7/dist-packages/onionshare
copying build/lib.linux-x86_64-2.7/onionshare/__init__.py -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/lib/python2.7/dist-packages/onionshare
copying build/lib.linux-x86_64-2.7/onionshare/helpers.py -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/lib/python2.7/dist-packages/onionshare
copying build/lib.linux-x86_64-2.7/onionshare/onionshare.py -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/lib/python2.7/dist-packages/onionshare
copying build/lib.linux-x86_64-2.7/onionshare/socks.py -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/lib/python2.7/dist-packages/onionshare
copying build/lib.linux-x86_64-2.7/onionshare/strings.py -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/lib/python2.7/dist-packages/onionshare
copying build/lib.linux-x86_64-2.7/onionshare/web.py -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/lib/python2.7/dist-packages/onionshare
running install_data
creating /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/share
creating /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/share/applications
copying setup/onionshare.desktop -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/share/applications
creating /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/share/pixmaps
copying setup/onionshare80.xpm -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/share/pixmaps
creating /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/share/onionshare
creating /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/share/onionshare/images
copying images/logo.png -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/share/onionshare/images
copying images/drop_files.png -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/share/onionshare/images
copying images/server_stopped.png -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/share/onionshare/images
copying images/server_started.png -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/share/onionshare/images
copying images/server_working.png -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/share/onionshare/images
creating /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/share/onionshare/locale
copying locale/de.json -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/share/onionshare/locale
copying locale/en.json -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/share/onionshare/locale
copying locale/es.json -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/share/onionshare/locale
copying locale/fi.json -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/share/onionshare/locale
copying locale/fr.json -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/share/onionshare/locale
copying locale/it.json -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/share/onionshare/locale
copying locale/nl.json -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/share/onionshare/locale
copying locale/no.json -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/share/onionshare/locale
copying locale/pt.json -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/share/onionshare/locale
copying locale/ru.json -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/share/onionshare/locale
copying locale/tr.json -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/share/onionshare/locale
running install_egg_info
Copying onionshare.egg-info to /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/lib/python2.7/dist-packages/onionshare-0.7dev.egg-info
running install_scripts
creating /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/bin
copying build/scripts-2.7/onionshare-gui -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/bin
copying build/scripts-2.7/onionshare -> /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/bin
changing mode of /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/bin/onionshare-gui to 775
changing mode of /home/backbox/onionshare/deb_dist/onionshare-0.7dev/debian/onionshare/usr/bin/onionshare to 775
   dh_installdocs -O--buildsystem=python_distutils
   dh_installchangelogs -O--buildsystem=python_distutils
   dh_python2 -O--buildsystem=python_distutils
   dh_perl -O--buildsystem=python_distutils
   dh_link -O--buildsystem=python_distutils
   dh_compress -O--buildsystem=python_distutils
   dh_fixperms -O--buildsystem=python_distutils
   dh_installdeb -O--buildsystem=python_distutils
   dh_gencontrol -O--buildsystem=python_distutils
dpkg-gencontrol: warning: package onionshare: unused substitution variable ${python:Versions}
   dh_md5sums -O--buildsystem=python_distutils
   dh_builddeb -O--buildsystem=python_distutils
dpkg-deb: building package `onionshare' in `../onionshare_0.7dev-1_all.deb'.
 dpkg-genchanges -b >../onionshare_0.7dev-1_amd64.changes
dpkg-genchanges: binary-only upload - not including any source code
 dpkg-source --after-build onionshare-0.7dev
dpkg-source: info: using options from onionshare-0.7dev/debian/source/options: --extend-diff-ignore=\.egg-info
dpkg-buildpackage: binary only upload (no source included)

To install, run:
sudo dpkg -i deb_dist/onionshare_0.7dev-1_all.deb
backbox@backbox:~/onionshare$ sudo dpkg -i deb_dist/onionshare_*.deb
Selecting previously unselected package onionshare.
(Reading database ... 204395 files and directories currently installed.)
Preparing to unpack .../onionshare_0.7dev-1_all.deb ...
Unpacking onionshare (0.7dev-1) ...
Setting up onionshare (0.7dev-1) ...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...

**Comment by micahflee** [comment]
I can reproduce. Looking into it.

**Comment by micahflee** [comment]
I think this is related to the version string being set to `0.7dev` actually. For some reason during the pysetup packaging it expects the package directory to be called `onionshare-0.7~dev0` but really it's called `onionshare-0.7.dev0`, and so the build fails.

If I change the version from `0.7dev` to `0.7` it fixes it. Weird.

**Comment by micahflee** [comment]
Also weird, if I set the version to `0.7alpha`, `0.7development`, or `0.7develop` it all works fine. It's only a problem with `0.7dev`. So I'm gonna go ahead and change the dev version to `0.7develop`.
