### ISSUE TITLE
have a set time to turn off web sever

### ISSUE THREAD

**Issue by ghost** [micahflee/onionshare#177]
Can there be an option to turn off the web server for a set amount of time, for example you only want the download link available for 24 hours.

**Comment by micahflee** [comment]
Seems like a good idea.

**Comment by Zaxscdvf** [comment]
Do you think you'll add in this feature?

**Comment by micahflee** [comment]
I'd like to, but not in the immediate release I'm working on. I'm just gonna focus on bug fixes for now, and decide which new features to build in later for future releases. So, quite possibly, but not yet :). If you'd like to try implementing it yourself though, go ahead and create a pull request. I'm definitely open to merging it in.

**Comment by Zaxscdvf** [comment]
ok thanks I'll see what I can do.

**Comment by choltz95** [comment]
Is there a preference for the gui layout? i.e. replacing the check box with a drop-down list or textfield?

**Comment by micahflee** [comment]
I changed this to the 0.9.3 milestone because I thought the #296 PR would be easy to merge. But it still needs more work, so I'm changing back to 1.0 again.

**Comment by micahflee** [comment]
When #473 is finished, it will resolve this issue

**Comment by mig5** [comment]
\o/
