### ISSUE TITLE
Arch Linux documentation?

### ISSUE THREAD

**Issue by ghost** [micahflee/onionshare#180]
I don't see any build instructions for Arch linux? maybe I am missing something?

**Comment by micahflee** [comment]
I've never tried building in Arch. Have you been able to get it successfully working? If you want to record your steps and post them here I can test them and then add Arch instructions.

**Comment by Zaxscdvf** [comment]
I'll see but I did find this project on the AUR https://aur.archlinux.org/packages/onionshare/ when I try to install,

 yaourt -S  --nocolor aur/onionshare

==> Downloading onionshare PKGBUILD from AUR...
x .AURINFO
x PKGBUILD
onionshare 0.6-1  (2014-09-27 22:31)
( Unsupported package: Potentially dangerous ! )
==> Edit PKGBUILD ? [Y/n] ("A" to abort)
==> ------------------------------------
==> y

Please add $EDITOR to your environment variables
for example:
export EDITOR="vim" (in ~/.bashrc)
(replace vim with your favorite editor)

==> Edit PKGBUILD with:  

/usr/lib/yaourt/util.sh: line 198: PKGBUILD: command not found
==> onionshare dependencies:
 - python2-flask (already installed)
 - python2-stem-git (building from AUR)


==> Continue building onionshare ? [Y/n]
==> ------------------------------------
==> 
==> Building and installing package
==> Install or build missing dependencies for onionshare:

==> Downloading python2-stem-git PKGBUILD from AUR...
x PKGBUILD
Comment by phantome  (2015-04-12 17:17)
PKGBUILD fails to download the source.

To make it work you need to change 

source=('git://git.torproject.org/stem.git')

to

source=('git+https://git.torproject.org/stem.git')

python2-stem-git 1:1.1.1.r22.ga6d025d-1  (2013-11-23 22:06)
( Unsupported package: Potentially dangerous ! )
==> Edit PKGBUILD ? [Y/n] ("A" to abort)
==> ------------------------------------
==> y

Please add $EDITOR to your environment variables
for example:
export EDITOR="vim" (in ~/.bashrc)
(replace vim with your favorite editor)

==> Edit PKGBUILD with:  

/usr/lib/yaourt/util.sh: line 198: PKGBUILD: command not found
==> python2-stem-git dependencies:
 - python2 (already installed)
 - git (already installed)


==> Continue building python2-stem-git ? [Y/n]
==> ------------------------------------------
==> 
==> Building and installing package
==> Making package: python2-stem-git 1:1.1.1.r22.ga6d025d-1 (Fri May 15 13:48:17 MDT 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning stem git repo...
Cloning into bare repository '/tmp/yaourt-tmp-ping/aur-python2-stem-git/stem'...
fatal: unable to connect to git.torproject.org:
git.torproject.org[0: 154.35.132.68]: errno=Connection refused

==> ERROR: Failure while downloading stem git repo
    Aborting...
==> ERROR: Makepkg was unable to build python2-stem-git.
==> Restart building python2-stem-git ? [y/N]
==> -----------------------------------------
==>

**Comment by Zaxscdvf** [comment]
ok I got it installed just have to change 

source=('git://git.torproject.org/stem.git')

to

source=('git+https://git.torproject.org/stem.git')

for python2-stem-git

**Comment by Zaxscdvf** [comment]
build from source,

 cd onionshare-master
 sudo python2 setup.py install --root="$pkgdir/" --optimize=1
 sudo install -D -m 644 install/onionshare.desktop "${pkgdir}/usr/share/applications/"
 sudo install -D -m 644 install/onionshare80.xpm "${pkgdir}/usr/share/pixmaps/"
 sudo chmod +x $pkgdir/usr/bin/onionshare $pkgdir/usr/bin/onionshare-gui

Should be found under "internet" if not

onionshare-gui or just use through command line

**Comment by simonsmiley** [comment]
@micahflee I'm the maintainer of a [PKGBUILD](https://aur.archlinux.org/packages/onionshare/) for onionshare. You can link to it you want. 
The issue @Zaxscdvf  was having is from a dependency. I'm working on resolving that...
I guess you can close the issue (not sure about the last comment though I don't understand it...)

**Comment by simonsmiley** [comment]
I guess this can be closed. Automatic installation now works though aur.

**Comment by micahflee** [comment]
Thanks @simonsmiley
