### ISSUE TITLE
Make sure OnionShare works with Tor Browser Launcher's AppArmor confinement

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#185]
Some users might be running Tor Browser confined with AppArmor profiles included in Tor Browser Launcher. In this case, OnionShare needs to make sure chooses a hidden service directory in a place that tor has permissions to write to.

Related to https://github.com/micahflee/torbrowser-launcher/issues/182

**Comment by micahflee** [comment]
In Linux, the hidden service directories will always be in `/tmp/onionshare/*` now.

**Comment by jvoisin** [comment]
When is the `/tmp/onionshare/` folder deleted?

**Comment by micahflee** [comment]
Sorry about the late answer to your question. Individual hidden service dirs get deleted as soon as onionshare closes (see https://github.com/micahflee/onionshare/blob/master/onionshare/onionshare.py#L83). The full `/tmp/onionshare` directory doesn't get deleted, but as long as onionshare hasn't crashed it should always be empty when there isn't an onionshare in use.
