### ISSUE TITLE
Clarify Socksipy version

### ISSUE THREAD

**Issue by jvoisin** [micahflee/onionshare#208]
Currently, there is a `socks.py` file embedded within onionshare, stating that the version in use is 1.5.0, while the latest upstream version is [1.0](http://sourceforge.net/projects/socksipy/files/socksipy/SocksiPy%201.00/). Where does your version come from? 

I have some patches for it, and I was wondering where I should send them.

**Comment by micahflee** [comment]
I don't remember my reasoning at the time, but after looking into it it appears that I'm using this fork of SocksiPy: https://github.com/Anorov/PySocks

The master branch there is at 1.5.6, although the latest git tag is 1.5.0.

Personally I don't have much of an opinion about which version onionshare uses. I just needed to be able to make an http request over Tor for the `hs.wait_for_hs()` function (https://github.com/micahflee/onionshare/blob/master/onionshare/hs.py#L133), which soon won't even be used by most people, once ephemeral hidden services are stable.

Do you have a preference in which version of socks.py I should bundle? Or, better yet, a simpler way to make an http request over Tor in python without having to bundle either?

**Comment by jvoisin** [comment]
```python
import urllib2

url = "https://check.torproject.org/"

proxy = urllib2.ProxyHandler({'http': '127.0.0.1:8118'})
opener = urllib2.build_opener(proxy)
urllib2.install_opener(opener)
u = urllib2.urlopen(url)
print u.info()
print u.read()
```

Maybe something like this.

**Comment by micahflee** [comment]
I'll give it a try.

**Comment by micahflee** [comment]
Hmm I just noticed this is using port 8118 -- this is the http proxy, not the socks5 proxy right? This may be a problem because as far as I can tell the only two ports Tor Browser open is 9150 (socks5) and 9151 (control port), and there isn't an http proxy that onionshare could connect to.

It's important to make onionshare work with Tor Browser for Windows and OSX users, and I don't want to make people have to edit a torrc or anything.

**Comment by r4v5** [comment]
> I don't remember my reasoning at the time, but after looking into it it appears that I'm using this fork of SocksiPy: https://github.com/Anorov/PySocks

That was me, in https://github.com/micahflee/onionshare/pull/120 -- socksipy was not playing properly with Travis CI's test runners nor my local installation, so it got swapped out for pysocks, and then Micah just included the socks implementation locally for a simpler solution in b830438d.

Are people still using a tor version old enough to need to fall back to the socks method, or have ephemeral hidden services rolled out?

**Comment by jvoisin** [comment]
I think that ephemeral hidden-services are now a thing.

**Comment by micahflee** [comment]
The versions of tor and stem is Debian Jessie are still too old to support ephemeral onion services. I would love to rip out all of the legacy code (#278) and make OnionShare only support ephemeral onion services, but I don't think it's reasonable to until Squeeze is slightly closer to being the new stable. Once Squeeze is stable, I'm happy to abandon support for Jessie.

**Comment by mig5** [comment]
I think ephemeral services are _required_ these days. Maybe we can close this, or do you want to try removing the socks.py in favor of python3-pysocks which seems packaged for Jessie and probably above?

**Comment by mig5** [comment]
We use the socksipy module we ship with, for a couple of other things these days - I don’t see that changing, and the version/source has been clarified here, so I think we can close this.
