### ISSUE TITLE
cp: cannot stat `deb_dist/onionshare_*.deb': No such file or directory

### ISSUE THREAD

**Issue by Very-Newbie** [micahflee/onionshare#211]
Problem in Tails (1.5.1)
I used https://github.com/micahflee/onionshare/tree/master/tails
And all be ok, before  "...then OnionShare will get installed. OnionShare will appear in the menu under Applications > Internet > OnionShare."

After install, i cant find  OnionShare in Applications > Internet.

Logs:

amnesia@amnesia:~$ cd ~/Persistent
amnesia@amnesia:~/Persistent$ git clone https://github.com/micahflee/onionshare.git
fatal: destination path 'onionshare' already exists and is not an empty directory. [This is the second attempt]

amnesia@amnesia:~/Persistent$ sudo onionshare/tails/install_in_persistent_volume.sh

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for amnesia: 
Hit tor+http://ftp.us.debian.org wheezy Release.gpg                            
Hit tor+http://deb.torproject.org obfs4proxy Release.gpg                       
Hit tor+http://ftp.us.debian.org experimental Release.gpg                      
Hit tor+http://deb.tails.boum.org 1.5.1 Release.gpg                            
Hit tor+http://deb.torproject.org wheezy Release.gpg                           
Hit tor+http://ftp.us.debian.org jessie Release.gpg                            
Hit tor+http://deb.torproject.org sid Release.gpg                              
Hit tor+http://deb.tails.boum.org 1.5.1 Release                                
Hit tor+http://ftp.us.debian.org unstable Release.gpg                          
Hit tor+http://deb.torproject.org obfs4proxy Release                           
Hit tor+http://ftp.us.debian.org testing Release.gpg                           
Hit tor+http://deb.tails.boum.org 1.5.1/main i386 Packages                     
Hit tor+http://ftp.us.debian.org wheezy-backports Release.gpg                  
Hit tor+http://deb.torproject.org wheezy Release                               
Hit tor+http://ftp.us.debian.org wheezy Release                                
Hit tor+http://deb.torproject.org sid Release                                  
Hit tor+http://ftp.us.debian.org experimental Release                          
Hit tor+http://deb.torproject.org obfs4proxy/main i386 Packages                
Hit tor+http://ftp.us.debian.org jessie Release                                
Hit tor+http://ftp.us.debian.org unstable Release                              
Hit tor+http://ftp.us.debian.org testing Release                               
Hit tor+http://deb.torproject.org wheezy/main i386 Packages                    
Hit tor+http://ftp.us.debian.org wheezy-backports Release                      
Hit tor+http://ftp.us.debian.org wheezy/main i386 Packages                     
Ign tor+http://deb.tails.boum.org 1.5.1/main Translation-en                    
Hit tor+http://deb.torproject.org sid/main i386 Packages                       
Hit tor+http://ftp.us.debian.org wheezy/contrib i386 Packages                  
Hit tor+http://ftp.us.debian.org wheezy/non-free i386 Packages                 
Hit tor+http://ftp.us.debian.org wheezy/contrib Translation-en                 
Hit tor+http://ftp.us.debian.org wheezy/main Translation-en                    
Hit tor+http://ftp.us.debian.org wheezy/non-free Translation-en                
Hit tor+http://ftp.us.debian.org experimental/main i386 Packages/DiffIndex     
Hit tor+http://ftp.us.debian.org experimental/main Translation-en/DiffIndex    
Hit tor+http://ftp.us.debian.org jessie/main i386 Packages                     
Hit tor+http://ftp.us.debian.org jessie/contrib i386 Packages                  
Hit tor+http://ftp.us.debian.org jessie/non-free i386 Packages                 
Hit tor+http://ftp.us.debian.org jessie/contrib Translation-en                 
Hit tor+http://ftp.us.debian.org jessie/main Translation-en                    
Hit tor+http://ftp.us.debian.org jessie/non-free Translation-en                
Hit tor+http://ftp.us.debian.org unstable/main i386 Packages/DiffIndex         
Hit tor+http://ftp.us.debian.org unstable/contrib i386 Packages/DiffIndex      
Hit tor+http://ftp.us.debian.org unstable/non-free i386 Packages/DiffIndex     
Hit tor+http://ftp.us.debian.org unstable/contrib Translation-en/DiffIndex     
Ign tor+http://deb.torproject.org obfs4proxy/main Translation-en               
Hit tor+http://ftp.us.debian.org unstable/main Translation-en/DiffIndex        
Hit tor+http://ftp.us.debian.org unstable/non-free Translation-en/DiffIndex    
Ign tor+http://deb.torproject.org wheezy/main Translation-en                   
Ign tor+http://deb.torproject.org sid/main Translation-en                      
Hit tor+http://ftp.us.debian.org testing/main i386 Packages/DiffIndex          
Hit tor+http://ftp.us.debian.org testing/contrib i386 Packages/DiffIndex       
Hit tor+http://ftp.us.debian.org testing/non-free i386 Packages/DiffIndex      
Hit tor+http://ftp.us.debian.org testing/contrib Translation-en/DiffIndex      
Hit tor+http://ftp.us.debian.org testing/main Translation-en/DiffIndex         
Hit tor+http://ftp.us.debian.org testing/non-free Translation-en/DiffIndex     
Hit tor+http://ftp.us.debian.org wheezy-backports/main i386 Packages/DiffIndex 
Hit tor+http://ftp.us.debian.org wheezy-backports/contrib i386 Packages/DiffIndex
Hit tor+http://ftp.us.debian.org wheezy-backports/non-free i386 Packages/DiffIndex
Hit tor+http://ftp.us.debian.org wheezy-backports/contrib Translation-en/DiffIndex
Hit tor+http://ftp.us.debian.org wheezy-backports/main Translation-en/DiffIndex
Hit tor+http://ftp.us.debian.org wheezy-backports/non-free Translation-en/DiffIndex
Hit tor+http://security.debian.org wheezy/updates Release.gpg                  
Hit tor+http://security.debian.org jessie/updates Release.gpg                  
Hit tor+http://security.debian.org wheezy/updates Release                      
Hit tor+http://security.debian.org jessie/updates Release                      
Hit tor+http://security.debian.org wheezy/updates/main i386 Packages           
Hit tor+http://security.debian.org wheezy/updates/contrib i386 Packages        
Hit tor+http://security.debian.org wheezy/updates/non-free i386 Packages       
Hit tor+http://security.debian.org wheezy/updates/contrib Translation-en       
Hit tor+http://security.debian.org wheezy/updates/main Translation-en          
Hit tor+http://security.debian.org wheezy/updates/non-free Translation-en      
Hit tor+http://security.debian.org jessie/updates/main i386 Packages           
Hit tor+http://security.debian.org jessie/updates/contrib i386 Packages        
Hit tor+http://security.debian.org jessie/updates/non-free i386 Packages       
Hit tor+http://security.debian.org jessie/updates/contrib Translation-en       
Hit tor+http://security.debian.org jessie/updates/main Translation-en          
Hit tor+http://security.debian.org jessie/updates/non-free Translation-en      
Reading package lists... Done                                                  
W: Ignoring Provides line with DepCompareOp for package php-math-biginteger
W: Ignoring Provides line with DepCompareOp for package python-cffi-backend-api-max
W: Ignoring Provides line with DepCompareOp for package python-cffi-backend-api-min
W: Ignoring Provides line with DepCompareOp for package python3-cffi-backend-api-max
W: Ignoring Provides line with DepCompareOp for package python3-cffi-backend-api-min
W: Ignoring Provides line with DepCompareOp for package libjpeg62
W: Ignoring Provides line with DepCompareOp for package php-psr-http-message-implementation
W: Ignoring Provides line with DepCompareOp for package php-psr-log-implementation
W: Ignoring Provides line with DepCompareOp for package php-math-biginteger
W: Ignoring Provides line with DepCompareOp for package python-cffi-backend-api-max
W: Ignoring Provides line with DepCompareOp for package python-cffi-backend-api-min
W: Ignoring Provides line with DepCompareOp for package python3-cffi-backend-api-max
W: Ignoring Provides line with DepCompareOp for package python3-cffi-backend-api-min
W: You may want to run apt-get update to correct these problems
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-qt4 is already the newest version.
python-qt4 set to manually installed.
python-socksipy is already the newest version.
python-socksipy set to manually installed.
The following extra packages will be installed:
  debhelper dpkg-dev g++ g++-4.7 gcc gcc-4.7 html2text intltool-debian
  libc-dev-bin libc6-dev libitm1 libjs-jquery libstdc++6-4.7-dev
  linux-libc-dev make po-debconf python-jinja2 python-markupsafe
  python-setuptools python-werkzeug python2.6 python2.6-minimal
Suggested packages:
  dh-make debian-keyring g++-multilib g++-4.7-multilib gcc-4.7-doc
  libstdc++6-4.7-dbg gcc-multilib manpages-dev autoconf automake1.9 libtool
  flex bison gdb gcc-doc gcc-4.7-multilib libmudflap0-4.7-dev gcc-4.7-locales
  libgcc1-dbg libgomp1-dbg libitm1-dbg libquadmath0-dbg libmudflap0-dbg
  libcloog-ppl0 libppl-c2 libppl7 binutils-gold glibc-doc libstdc++6-4.7-doc
  make-doc libmail-box-perl python-jinja2-doc python-all-dev ipython
  python-genshi python-memcache libjs-sphinxdoc python2.6-doc binfmt-support
Recommended packages:
  libalgorithm-merge-perl javascript-common libmail-sendmail-perl apt-file
  python-openssl
The following NEW packages will be installed:
  build-essential debhelper dpkg-dev fakeroot g++ g++-4.7 gcc gcc-4.7
  html2text intltool-debian libc-dev-bin libc6-dev libitm1 libjs-jquery
  libstdc++6-4.7-dev linux-libc-dev make po-debconf python-all python-flask
  python-jinja2 python-markupsafe python-setuptools python-stdeb python-stem
  python-werkzeug python2.6 python2.6-minimal
0 upgraded, 28 newly installed, 0 to remove and 20 not upgraded.
Need to get 0 B/33.5 MB of archives.
After this operation, 92.2 MB of additional disk space will be used.
Selecting previously unselected package libitm1:i386.
(Reading database ... 135784 files and directories currently installed.)
Unpacking libitm1:i386 (from .../libitm1_4.7.2-5_i386.deb) ...
Selecting previously unselected package python2.6-minimal.
Unpacking python2.6-minimal (from .../python2.6-minimal_2.6.8-1.1_i386.deb) ...
Selecting previously unselected package libc-dev-bin.
Unpacking libc-dev-bin (from .../libc-dev-bin_2.13-38+deb7u8_i386.deb) ...
Selecting previously unselected package linux-libc-dev:i386.
Unpacking linux-libc-dev:i386 (from .../linux-libc-dev_3.2.68-1+deb7u3_i386.deb) ...
Selecting previously unselected package libc6-dev:i386.
Unpacking libc6-dev:i386 (from .../libc6-dev_2.13-38+deb7u8_i386.deb) ...
Selecting previously unselected package gcc-4.7.
Unpacking gcc-4.7 (from .../gcc-4.7_4.7.2-5_i386.deb) ...
Selecting previously unselected package gcc.
Unpacking gcc (from .../gcc_4%3a4.7.2-1_i386.deb) ...
Selecting previously unselected package libstdc++6-4.7-dev.
Unpacking libstdc++6-4.7-dev (from .../libstdc++6-4.7-dev_4.7.2-5_i386.deb) ...
Selecting previously unselected package g++-4.7.
Unpacking g++-4.7 (from .../g++-4.7_4.7.2-5_i386.deb) ...
Selecting previously unselected package g++.
Unpacking g++ (from .../g++_4%3a4.7.2-1_i386.deb) ...
Selecting previously unselected package make.
Unpacking make (from .../make_3.81-8.2_i386.deb) ...
Selecting previously unselected package dpkg-dev.
Unpacking dpkg-dev (from .../dpkg-dev_1.16.16_all.deb) ...
Selecting previously unselected package build-essential.
Unpacking build-essential (from .../build-essential_11.5_i386.deb) ...
Selecting previously unselected package html2text.
Unpacking html2text (from .../html2text_1.3.2a-15_i386.deb) ...
Selecting previously unselected package intltool-debian.
Unpacking intltool-debian (from .../intltool-debian_0.35.0+20060710.1_all.deb) ...
Selecting previously unselected package po-debconf.
Unpacking po-debconf (from .../po-debconf_1.0.16+nmu2_all.deb) ...
Selecting previously unselected package debhelper.
Unpacking debhelper (from .../debhelper_9.20120909_all.deb) ...
Selecting previously unselected package fakeroot.
Unpacking fakeroot (from .../fakeroot_1.18.4-2_i386.deb) ...
Selecting previously unselected package libjs-jquery.
Unpacking libjs-jquery (from .../libjs-jquery_1.7.2+dfsg-1_all.deb) ...
Selecting previously unselected package python2.6.
Unpacking python2.6 (from .../python2.6_2.6.8-1.1_i386.deb) ...
Selecting previously unselected package python-all.
Unpacking python-all (from .../python-all_2.7.3-4+deb7u1_all.deb) ...
Selecting previously unselected package python-werkzeug.
Unpacking python-werkzeug (from .../python-werkzeug_0.8.3+dfsg-1_all.deb) ...
Selecting previously unselected package python-markupsafe.
Unpacking python-markupsafe (from .../python-markupsafe_0.15-1_i386.deb) ...
Selecting previously unselected package python-jinja2.
Unpacking python-jinja2 (from .../python-jinja2_2.6-1_i386.deb) ...
Selecting previously unselected package python-flask.
Unpacking python-flask (from .../python-flask_0.8-1_all.deb) ...
Selecting previously unselected package python-setuptools.
Unpacking python-setuptools (from .../python-setuptools_0.6.24-1_all.deb) ...
Selecting previously unselected package python-stdeb.
Unpacking python-stdeb (from .../python-stdeb_0.6.0+20100620-2_all.deb) ...
Selecting previously unselected package python-stem.
Unpacking python-stem (from .../python-stem_1.2.2-1~bpo70+1_all.deb) ...
Processing triggers for man-db ...
Processing triggers for mime-support ...
Processing triggers for desktop-file-utils ...
Processing triggers for gnome-menus ...
Processing triggers for menu ...
Setting up libitm1:i386 (4.7.2-5) ...
Setting up python2.6-minimal (2.6.8-1.1) ...
Linking and byte-compiling packages for runtime python2.6...
Setting up libc-dev-bin (2.13-38+deb7u8) ...
Setting up linux-libc-dev:i386 (3.2.68-1+deb7u3) ...
Setting up libc6-dev:i386 (2.13-38+deb7u8) ...
Setting up gcc-4.7 (4.7.2-5) ...
Setting up gcc (4:4.7.2-1) ...
Setting up make (3.81-8.2) ...
Setting up dpkg-dev (1.16.16) ...
Setting up html2text (1.3.2a-15) ...
Setting up intltool-debian (0.35.0+20060710.1) ...
Setting up po-debconf (1.0.16+nmu2) ...
Setting up debhelper (9.20120909) ...
Setting up fakeroot (1.18.4-2) ...
update-alternatives: using /usr/bin/fakeroot-sysv to provide /usr/bin/fakeroot (fakeroot) in auto mode
Setting up libjs-jquery (1.7.2+dfsg-1) ...
Setting up python2.6 (2.6.8-1.1) ...
Setting up python-all (2.7.3-4+deb7u1) ...
Setting up python-werkzeug (0.8.3+dfsg-1) ...
Setting up python-markupsafe (0.15-1) ...
Setting up python-jinja2 (2.6-1) ...
Setting up python-flask (0.8-1) ...
Setting up python-setuptools (0.6.24-1) ...
Setting up python-stdeb (0.6.0+20100620-2) ...
Setting up python-stem (1.2.2-1~bpo70+1) ...
Setting up g++-4.7 (4.7.2-5) ...
Setting up g++ (4:4.7.2-1) ...
update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
Setting up build-essential (11.5) ...
Setting up libstdc++6-4.7-dev (4.7.2-5) ...
Processing triggers for python-support ...
Processing triggers for menu ...
running bdist_deb
running sdist_dsc
running egg_info
writing onionshare.egg-info/PKG-INFO
writing top-level names to onionshare.egg-info/top_level.txt
writing dependency_links to onionshare.egg-info/dependency_links.txt
reading manifest file 'onionshare.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'onionshare/strings.json'
writing manifest file 'onionshare.egg-info/SOURCES.txt'
CALLING dpkg-source -b onionshare-0.7.1 (in dir deb_dist)
dpkg-source: info: using source format `3.0 (quilt)'
dpkg-source: info: building onionshare using existing ./onionshare_0.7.1.orig.tar.gz
dpkg-source: info: building onionshare in onionshare_0.7.1-1.debian.tar.gz
dpkg-source: info: building onionshare in onionshare_0.7.1-1.dsc
dpkg-source: warning: extracting unsigned source package (onionshare_0.7.1-1.dsc)
dpkg-source: info: extracting onionshare in onionshare-0.7.1
dpkg-source: info: unpacking onionshare_0.7.1.orig.tar.gz
dpkg-source: info: unpacking onionshare_0.7.1-1.debian.tar.gz
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: source package onionshare
dpkg-buildpackage: source version 0.7.1-1
dpkg-buildpackage: source changed by Micah Lee <micah@micahflee.com>
dpkg-buildpackage: host architecture i386
 dpkg-source --before-build onionshare-0.7.1
dpkg-checkbuilddeps: Unmet build dependencies: dh-python
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
Traceback (most recent call last):
  File "setup.py", line 91, in <module>
    (os.path.join(sys.prefix, 'share/onionshare/locale'), locale)
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/stdeb/command/bdist_deb.py", line 42, in run
    util.process_command(syscmd,cwd=target_dir)
  File "/usr/lib/python2.7/dist-packages/stdeb/util.py", line 142, in process_command
    check_call(args, cwd=cwd)
  File "/usr/lib/python2.7/dist-packages/stdeb/util.py", line 35, in check_call
    raise CalledProcessError(retcode)
stdeb.util.CalledProcessError: 3

To install, run:
sudo dpkg -i deb_dist/onionshare_0.7.1-1_all.deb
cp: cannot stat `deb_dist/onionshare_*.deb': No such file or directory
cp: cannot stat `tails/onionshare-install.desktop': No such file or directory
amnesia@amnesia:~/Persistent$ 

(p.S. i`m not coder, just a low skill user. How i can run the programm?).
Thx

**Comment by Very-Newbie** [comment]
my friend tell me about 
"dpkg-checkbuilddeps: Unmet build dependencies: dh-python
 dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
 dpkg-buildpackage: warning: (Use -d flag to override.)"

For this need "sudo apt-get install dh-python"

**Comment by micahflee** [comment]
Thanks. dh-python has been added as a build dependency. Although note that onionshare doesn't currently work in Tails, until #220 is resolved.
