### ISSUE TITLE
OnionShare.pkg for mac

### ISSUE THREAD

**Issue by beemill** [micahflee/onionshare#213]
I just downloaded the software from the onionshare.org site and ran it and it seemed like it was installing but it didn't install anything, or at least I couldn't find anything in the Application folder.

**Comment by beemill** [comment]
I'm also getting a warning about revoked keys: 
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.

**Comment by freddymartinez9** [comment]
@beemill did you import micah's GPG signature in your keyring before you installed? That's likely why you're seeing that warning...

**Comment by micahflee** [comment]
Sorry about the revoked key! I signed the latest stable version 0.7.1 with my personal PGP key, but I revoked it when I transitioned to a new key. If the signature verifies it's still good, and the next release will be signed with a new, non-revoked key.

As far as the .pkg file, do you have an onionshare development environment set up on your Mac as well? I've noticed that if I already have a copy of `OnionShare.app` on my computer (like in `~/code/onionshare/dist/OnionShare.app`), the .pkg detects that it's already there and the same version (I think) and doesn't install a new one.
