### ISSUE TITLE
Prefer port 9151 to 9051

### ISSUE THREAD

**Issue by infinity0** [micahflee/onionshare#215]
Hi, until the "ephemeral services" branch is released, onionshare should prefer port 9151 because this is more likely to *actually work*. 9051 is usually the system tor, which does not have read or write access to /tmp/onionshare, and onionshare fails with a cryptic error about "nothing received from stem". I will be making this change in the Debian package.

**Comment by micahflee** [comment]
Good idea. And for that matter, I should also add port 9251 to the mix, in case people want to use Tor Messenger's version of tor.

**Comment by micahflee** [comment]
Actually it looks like Tor Messenger is listening on 9152 and 9153. My guess is 9152 is the SOCKS proxy and 9153 is the control port, but I'm verifying.
