### ISSUE TITLE
amd64 package not found in PPA

### ISSUE THREAD

**Issue by bnvk** [micahflee/onionshare#218]
I'm running Debian 8, but after adding the PPA for OnionShare and installing it, I get the following error on running `sudo apt-get update`

```
W: Failed to fetch http://ppa.launchpad.net/micahflee/ppa/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found
```

**Comment by micahflee** [comment]
It's not that the `amd64` package isn't found, it's that the `jessie` package isn't found. Unfortunately the PPA isn't supported in debian, because launchpad only allows me to support ubuntu versions.
