### ISSUE TITLE
conflicts after adding to Fedora 21

### ISSUE THREAD

**Issue by bnvk** [micahflee/onionshare#219]
Upon building from source and adding to Fedora all seemed to complete just fine. However, then upon running a normal `sudo yum update` I get the following the eror:

```
Transaction check error:
  file /usr/lib/python2.7/site-packages/onionshare-0.7.1-py2.7.egg-info from install of onionshare-0.7.1-1.fc21.noarch conflicts with file from package onionshare-0.7.1-1.noarch
```

**Comment by micahflee** [comment]
Onionshare is already packaged in Fedora. Maybe you have it installed from the official repositories and now you're trying to install it again from an rpm? Maybe try uninstalling it completely before installing the rpm?
