### ISSUE TITLE
Localization is applied to the download page, which is disclosing the locale of the sender

### ISSUE THREAD

**Issue by alexlehm** [micahflee/onionshare#228]
When running OnionShare on a localized OS (e.g. Windows with German, French etc localization), the recipient gets information about locale of sender, giving some indication where sender is (even though only a broad language region).

I would prefer it if the download page is not localized or it is configurable if the page is localized or not.

Some of the language files do not contain the localization keys for the words, so the issue does not apply to all languages, it is currently in de, es, fi, fr and nl

**Comment by micahflee** [comment]
This is an excellent point that I never considered. I think the easiest solution is to not localize the download page at all, and just leave it in English. The second easiest (and maybe better) solution is to remove all language from the download page and replace it with icons.

**Comment by burdges** [comment]
Yeah, this could be problematic in Europe where many people work in countries different from their native one.

Just fyi, it's possible to use the recipient's locale in straight JavaScript.  https://taler.net/ does this.  It doesn't really protect the recipient from leaking their locale to the sender, but kinda.  It'd leak the sender's onionshare version by leaking the locales supported by the sender.
