### ISSUE TITLE
.deb instructions are incorrect

### ISSUE THREAD

**Issue by freddymartinez9** [micahflee/onionshare#233]
The directory deb_dist is created in the folder that onionshare is checkouted in, the build_deb.sh assumes it is in install/ so both the deb cleanup and install instructions fail on debian jessie.

**Comment by freddymartinez9** [comment]
I should mention that I ran this locally on my box and it works as intended

**Comment by micahflee** [comment]
The `build_deb.sh` script starts by cd'ing to the git repo root directory before it does anything else:

```sh
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
cd $DIR
```

So when it runs `rm -r deb_dist >/dev/null 2>&1`, it's doing this from the correct place. At least it seems to work fine for me. Can you try running `build_deb.sh` from the repo root and show me what it does?

**Comment by freddymartinez9** [comment]
Ah yes you're right, I was in the install/ directory when the build instructions are ./install/build_deb.sh so this can be closed and I'll close my PR.
