### ISSUE TITLE
Building OnionShare in Windows 10 crashes in Windows 7

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#235]
https://twitter.com/ChintellaLaw/status/673599534614745088

![cvkbnpnwuaabymn jpg large](https://cloud.githubusercontent.com/assets/156128/11615722/979dbefc-9c1d-11e5-84c5-e0adb96fa5b1.jpeg)

**Comment by micahflee** [comment]
This has something to do with the version of the Microsoft Visual C++ Redistributable Package installed. Specifically, this is the files: `msvcm90.dll`, `msvcp90.dll`, and `msvcr90.dll`. I'm bundling a version built in 2015, but I think I need to be bundling a version built in 2008 to work on Windows 7.

**Comment by micahflee** [comment]
This seems like a similar problem: https://stackoverflow.com/questions/26444318/how-to-point-pyinstaller-to-the-right-versions-of-msvc90-dll

Here's some information about these files: https://support.microsoft.com/en-us/kb/326922

**Comment by micahflee** [comment]
I'm not quite sure what's causing this or how to fix it. I have a feeling that if I do the build in Windows 7 instead of Windows 10 it will just work in both versions of Windows, but that's not elegant. I would way prefer to use Windows 10 as the dev environment, so that's a last resort. Taking a break for awhile on this issue.

**Comment by ChintellaLaw** [comment]
Just fyi, the previous version worked, I'm assuming .7?  So I'd humbly suggest starting any differences between the two?  E.g., if you were "bundling" a version built in 2015 in the prior version, that's prob not the diff...but let me know if you need more info from me.

**Comment by micahflee** [comment]
Yes, 0.7.1 should still work fine in Windows 7 and you can get it here: https://github.com/micahflee/onionshare/releases/tag/0.7.1

**Comment by micahflee** [comment]
This looks like it might be a Windows permissions problem? https://superuser.com/questions/668820/google-drive-error-python27-dll

**Comment by micahflee** [comment]
I'm going to go ahead and make this 0.8.1 release in Windows 7, but leave this issue open. I'd like to be able to make future releases in Windows 10.

**Comment by codewarrior0** [comment]
This is a known issue with PyInstaller, Python 3.5 (or any Python built with Visual C++ 2015 against the UCRT libs), and Windows 10. There is no ETA on a fix.

https://github.com/pyinstaller/pyinstaller/issues/1566

Since you're not using Python 3.5, I'd suggest using the stock Python 2.7 distribution or else building it with a VC version earlier than 2015.

**Comment by mo0feng** [comment]
I also met this problem：

2723 WARNING: lib not found: api-ms-win-core-util-l1-1-0.dll dependency of C:\WINDOWS\system32\ucrtbase.dll
2750 WARNING: lib not found: api-ms-win-core-memory-l1-1-0.dll dependency of C:\WINDOWS\system32\ucrtbase.dll
2775 WARNING: lib not found: api-ms-win-core-heap-l1-1-0.dll dependency of C:\WINDOWS\system32\ucrtbase.dll
2801 WARNING: lib not found: api-ms-win-core-profile-l1-1-0.dll dependency of C:\WINDOWS\system32\ucrtbase.dll
2825 WARNING: lib not found: api-ms-win-core-interlocked-l1-1-0.dll dependency of C:\WINDOWS\system32\ucrtbase.dll
2852 WARNING: lib not found: api-ms-win-core-errorhandling-l1-1-0.dll dependency of C:\WINDOWS\system32\ucrtbase.dll
2878 WARNING: lib not found: api-ms-win-core-libraryloader-l1-1-0.dll dependency of C:\WINDOWS\system32\ucrtbase.dll
2903 WARNING: lib not found: api-ms-win-core-debug-l1-1-0.dll dependency of C:\WINDOWS\system32\ucrtbase.dll
2929 WARNING: lib not found: api-ms-win-core-namedpipe-l1-1-0.dll dependency of C:\WINDOWS\system32\ucrtbase.dll
2954 WARNING: lib not found: api-ms-win-core-processenvironment-l1-1-0.dll dependency of C:\WINDOWS\system32\ucrtbase.dll
2979 WARNING: lib not found: api-ms-win-core-string-l1-1-0.dll dependency of C:\WINDOWS\system32\ucrtbase.dll
3006 WARNING: lib not found: api-ms-win-core-synch-l1-1-0.dll dependency of C:\WINDOWS\system32\ucrtbase.dll
3031 WARNING: lib not found: api-ms-win-core-file-l1-1-0.dll dependency of C:\WINDOWS\system32\ucrtbase.dll
3057 WARNING: lib not found: api-ms-win-core-handle-l1-1-0.dll dependency of C:\WINDOWS\system32\ucrtbase.dll
3083 WARNING: lib not found: api-ms-win-core-processthreads-l1-1-0.dll dependency of C:\WINDOWS\system32\ucrtbase.dll
3108 WARNING: lib not found: api-ms-win-core-console-l1-1-0.dll dependency of C:\WINDOWS\system32\ucrtbase.dll
3133 WARNING: lib not found: api-ms-win-core-datetime-l1-1-0.dll dependency of C:\WINDOWS\system32\ucrtbase.dll
3160 WARNING: lib not found: api-ms-win-core-rtlsupport-l1-1-0.dll dependency of C:\WINDOWS\system32\ucrtbase.dll
3185 WARNING: lib not found: api-ms-win-core-sysinfo-l1-1-0.dll dependency of C:\WINDOWS\system32\ucrtbase.dll
