### ISSUE TITLE
"Stop sharing automatically" appears to become unselected when changing window

### ISSUE THREAD

**Issue by garrettr** [micahflee/onionshare#243]
# STR

On Mac OS 10.9 (may be a problem on other platforms too):

1. Open OnionShare
2. "Stop sharing automatically" is checked by default
3. With the OnionShare window still visible, click another program's window to focus it.

## Expected Behavior

The "Stop sharing automatically" checkbox continues to appear to be checked, even when focus moves to another window.

## Observed Behavior

The "Stop sharing automatically" checkbox appears to become unchecked when changing focus. When focus is returned to the OnionShare window, it appears to become checked again.

The inverse does _not_ happen if the checkbox is unchecked and window focus is changed.

[Video](https://youtu.be/gwPbCEqyV5o).

**Comment by ungenannter** [comment]
Im using Version 0.8.1 on Linux. It seems that the "Stop sharing automatically" checkbox has no effect.

**Comment by micahflee** [comment]
I've refactored OnionShare to use python3 and Qt5 instead of python2 and Qt4. Just checked, and the new GUI no longer looks like this on OSX.
