### ISSUE TITLE
Multiple downloads and status UI

### ISSUE THREAD

**Issue by garrettr** [micahflee/onionshare#248]
OnionShare does not limit the number of allowed simultaneous downloads. Any party that knows the HS address and the slug can connect and download the files as long as the server is running.

My first question is: is this intentional?

On the one hand, this could be useful. You could run a single OnionShare instance and then allow multiple people to receive the files at the same time by sharing the same URL with multiple people.

On the other hand, this potentially further increases the exposure of (especially shortened) slugs to a brute-force attack. The way that the rate limiting is implemented for #238 will make a difference here - there is a trade-off between allowing multiple users to download simultaneously (and potentially making mistakes in entering the URL) vs. increasing exposure to brute-force attack. In addition, we should ensure that if the rate limiting is engaged, it does not interfere any downloads that are already in progress.

If this behavior _is_ intentional, then the status UI needs to be updated to reflect it. The way multiple downloads interact with stopping the server is currently very confusing:

1. If I click "Stop Server", I expect it to cancel all of the currently unfinished downloads. It does not do this - the UI changes to indicate that the server has stopped, but all unfinished downloads continue to completion.
2. The interaction of "Stop sharing automatically" and multiple downloads needs to be carefully considered. If "Stop sharing automatically" is checked, should the server stop after just the first download is completed, or after all ongoing downloads are completed?

The current behavior is surprising and I believe it should be considered a bug. When you have multiple downloads going at once with "Stop sharing automatically" selected, the status UI indicates that the server has "stopped" after the first download is complete. Surprisingly, the other downloads continue to completion (although their progress bars in Onionshare freeze). The other downloads are not truncated and are identical to the first download.

See this [video](https://youtu.be/EP0BblsWDp8) for a demonstration of the bug.

**Comment by micahflee** [comment]
Regarding point 1 above, #262 fixes that. As soon as the server stops, any current downloads get canceled.

Regarding point 2 above, I think that if "Stop sharing automatically" is selected, it should only allow one download. If there is currently a download in progress, the `/[slug]` web design should remove the download link, and `/[slug]/download` should show an error message saying that a download is in progress, rather than starting a second download. If "Stop sharing automatically" is not selected, then it should support multiple downloads.
