### ISSUE TITLE
HTTP/2

### ISSUE THREAD

**Issue by blobgo** [micahflee/onionshare#254]
It would be good if the server would support HTTP/2.

Just faster... :wink:

**Comment by jvoisin** [comment]
Flask doesn't support http2 yet, so this is super-highly unlikely. Also, since major browsers will refuse to use http2 without TLS, this won't work very well for a lot of users.

**Comment by micahflee** [comment]
I don't have any data on this, but I imagine that the vast majority of OnionShare users use Tor Browser to load the web server, and then a tiny minority might use wget or curl. So when all of those browsers support http2 then maybe this makes sense :).

**Comment by blobgo** [comment]
Tor Browser already supports HTTP/2 AFAIK.

**Comment by micahflee** [comment]
Yeah, looks like this doesn't make sense yet.

**Comment by nbraud** [comment]
@blobgo Pure curiosity, since the ticket got closed: why do you expect HTTP/2 to be faster on a single-file download?
