### ISSUE TITLE
Windows installer should include all required DLLs

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#263]
I switched from pyinstaller to py2exe. I just built the installer in Win10 and tested it in Win7. I get the error: `The program can't start because MSVCR100.dll is missing from your computer. Try reinstalling the program to fix this problem.`

I just need to bundle it in the installer.

**Comment by freddymartinez9** [comment]
Microsoft Distribution C++ package is missing according to Google.

**Comment by micahflee** [comment]
This bug is no longer relevant because of the switch from py2exe to PyInstaller
