### ISSUE TITLE
Confirm when user tries to close GUI

### ISSUE THREAD

**Issue by infinity0** [micahflee/onionshare#264]
Some people who use onionshare assume that the sharing still works even when they close onionshare.

In the GUI at least, when the user attempts to close it, it should trigger a confirmation dialog box that makes it clear that sharing stops when onionshare is closed.

**Comment by delaRosa12345** [comment]
Yes!

**Comment by micahflee** [comment]
<img width="576" alt="screen shot 2016-04-10 at 7 27 07 pm" src="https://cloud.githubusercontent.com/assets/156128/14415291/36bf342e-ff52-11e5-89b6-194769922756.png">
