### ISSUE TITLE
Starting Tor hidden service... doesn't start. Failed to configure rendezvous options

### ISSUE THREAD

**Issue by marianoju** [micahflee/onionshare#267]
Using Ubuntu 14.04 I have installed the latest OnionShare and added a file, and I have waited for an hour for Tor hidden service to start. This is possibly due to: 

`Verbinde zum Tor-Kontrollport um den versteckten Dienst auf Port 53923 laufen zu lassen.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/onionshare_gui/onionshare_gui.py", line 151, in start_server
    self.app.start_hidden_service(gui=True)
  File "/usr/lib/python2.7/dist-packages/onionshare/onionshare.py", line 75, in start_hidden_service
    self.onion_host = self.hs.start(self.port)
  File "/usr/lib/python2.7/dist-packages/onionshare/hs.py", line 128, in start
    self.c.set_options(self._hsdic2list(hsdic))
  File "/usr/lib/python2.7/dist-packages/stem/control.py", line 1656, in set_options
    raise stem.InvalidRequest(response.code, response.message)
stem.InvalidRequest: Unacceptable option value: Failed to configure rendezvous options. See logs for details.`

Where can I find the log file?

**Comment by u451f** [comment]
This would probably be the Tor logs. They should live in /var/log/tor.

**Comment by marianoju** [comment]
Thanks, @u451f! 

`Mar 13 11:39:56.000 [notice] Tor 0.2.7.6 (git-605ae665009853bd) opening new log file.`
`Mar 13 13:30:44.000 [notice] New control connection opened from 127.0.0.1.`
`Mar 13 13:30:44.000 [warn] Directory /tmp/onionshare/tmpYT1YSj cannot be read: Permission denied`
`Mar 13 13:30:44.000 [warn] Controller gave us config lines that didn't validate: Failed to configure rendezvous options. See logs for details.`
`Mar 13 13:35:57.000 [notice] New control connection opened from 127.0.0.1.`
`Mar 13 13:35:57.000 [warn] Directory /tmp/onionshare/tmpQuDsxV cannot be read: Permission denied`
`Mar 13 13:35:57.000 [warn] Controller gave us config lines that didn't validate: Failed to configure rendezvous options. See logs for details.`
`Mar 13 13:36:19.000 [notice] New control connection opened from 127.0.0.1.`
`Mar 13 13:36:19.000 [warn] Directory /tmp/onionshare/tmp1Z7vjz cannot be read: Permission denied`
`Mar 13 13:36:19.000 [warn] Controller gave us config lines that didn't validate: Failed to configure rendezvous options. See logs for details.`
`Mar 13 17:01:55.000 [notice] Your system clock just jumped 7257 seconds forward; assuming established circuits no longer work.`
`Mar 13 17:06:11.000 [notice] New control connection opened from 127.0.0.1.`
`Mar 13 17:06:11.000 [warn] Directory /tmp/onionshare/tmp_mM0eg cannot be read: Permission denied`
`Mar 13 17:06:11.000 [warn] Controller gave us config lines that didn't validate: Failed to configure rendezvous options. See logs for details.`

**Comment by micahflee** [comment]
It looks like you're using your system tor and not Tor Browser. Can you try it again with the newest version (0.9) and also with Tor Browser open in the background?

**Comment by marianoju** [comment]
Aha, ok. Yes, starting and running Tor Browser in the background works for me. Is this the way it is intended to work? I find it not to be intuitive.

**Comment by u451f** [comment]
@marianoju Yes, until now that is the way it's supposed to work. Onionshare uses tor from TorBrowser. However, I believe that it's an aim to make onionshare work with system tor too.

**Comment by marianoju** [comment]
Well, thanks for your help @u451f!
