### ISSUE TITLE
Error in Installation

### ISSUE THREAD

**Issue by ravirajbasis** [micahflee/onionshare#268]
I am using Red Hat Enterprise Linux Workstation 7.2, while trying to install onionshare i get following message:
"[root@localhost ~]# sudo sudo yum install -y rpm-build python3-flask python3-stem python3-qt5 ./install/build_rpm.sh
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-
              : manager
Package rpm-build-4.11.3-17.el7.x86_64 already installed and latest version
No package python3-flask available.
No package python3-stem available.
No package python3-qt5 available.
No package ./install/build_rpm.sh available.
Nothing to do"

What to do ?

**Comment by micahflee** [comment]
I haven't tested OnionShare in Red Hat Enterprise Linux Workstation, but I have in Fedora Core 23, and it appears to work fine. It seems like your distribution doesn't have the dependencies that OnionShare needs. It also looks like that version of Linux [isn't freely downloadable](https://www.redhat.com/apps/store/desktop/), so it's not easy to test.

What happens when you run this?

```
yum search flask
```

**Comment by ravirajbasis** [comment]
Hi 

When i run command you have given it yields following output: 

"[root@localhost ~]# yum search flask
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-
              : manager
============================== N/S matched: flask ==============================
python-fedora-flask.noarch : Python modules for flask applications authing to
                           : Fedora Account System
python-flask-admin.noarch : Simple and extensible admin interface framework for
                          : Flask
python-flask-babel.noarch : Adds i18n/l10n support to Flask applications
python-flask-cache.noarch : Adds cache support to your Flask application
python-flask-cache-doc.noarch : Documentation for the Flask-Cache module
python-flask-mako.noarch : Mako templating support for Flask applications
python-flask-openid.noarch : OpenID support for Flask
python-flask-rstpages.noarch : Adds support for reStructuredText to a Flask
                             : application
python-flask-sqlalchemy.noarch : Adds SQLAlchemy support to Flask application
python-flask-whooshalchemy.noarch : Whoosh extension to Flask/SQLAlchemy
python-flask-wtf.noarch : Simple integration of Flask and WTForms
python-flask-xml-rpc.noarch : Adds support for creating XML-RPC APIs to Flask
python2-flask-multistatic.noarch : A simple flask plugin to allow overriding
                                 : static files
python2-mimerender.noarch : RESTful HTTP Content Negotiation for Flask, Bottle,
                          : etc.

  Name and summary matches only, use "search all" for everything."

**Comment by ravirajbasis** [comment]
Hi

When I run the command you have given above, it yields following output:

"[root@localhost ~]# yum search flask
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-
              : manager
============================== N/S matched: flask ==============================
python-fedora-flask.noarch : Python modules for flask applications authing to
                           : Fedora Account System
python-flask-admin.noarch : Simple and extensible admin interface framework for
                          : Flask
python-flask-babel.noarch : Adds i18n/l10n support to Flask applications
python-flask-cache.noarch : Adds cache support to your Flask application
python-flask-cache-doc.noarch : Documentation for the Flask-Cache module
python-flask-mako.noarch : Mako templating support for Flask applications
python-flask-openid.noarch : OpenID support for Flask
python-flask-rstpages.noarch : Adds support for reStructuredText to a Flask
                             : application
python-flask-sqlalchemy.noarch : Adds SQLAlchemy support to Flask application
python-flask-whooshalchemy.noarch : Whoosh extension to Flask/SQLAlchemy
python-flask-wtf.noarch : Simple integration of Flask and WTForms
python-flask-xml-rpc.noarch : Adds support for creating XML-RPC APIs to Flask
python2-flask-multistatic.noarch : A simple flask plugin to allow overriding
                                 : static files
python2-mimerender.noarch : RESTful HTTP Content Negotiation for Flask, Bottle,
                          : etc.

  Name and summary matches only, use "search all" for everything.
"

**Comment by ravirajbasis** [comment]
It got closed acciedently, now i've re-opened it.

**Comment by mig5** [comment]
@micahflee as per recent discussion, it sounds like we can say RHEL 7 is not supported if the dependencies are missing?

**Comment by mig5** [comment]
Updated https://github.com/micahflee/onionshare/wiki/Linux-Distribution-Support to note that other distros can attempt to install Python modules via pip same as macOS, but mileage may vary.
