### ISSUE TITLE
using a pre-configured hidden service by using --ip and --onion

### ISSUE THREAD

**Issue by adrelanos** [micahflee/onionshare#27]
It would be nice if there were `--ip 192.168.0.10:9125` and `--onion v645bzpxmdtclpv3.onion` arguments, so already existing, self, pre, -configured hidden services could be used. That would allow running onionshare in systems such as Whonix, where Tor runs on a different machine.

**Comment by micahflee** [comment]
I'm going to track this issue as part of #220 now.
