### ISSUE TITLE
0.9 instantly crashes upon launch on OS X 10.10.5

### ISSUE THREAD

**Issue by MacLemon** [micahflee/onionshare#274]
Installed OnionShare 0.9 on OS X 10.10.5 and it 100% reproducibly crashes upon launch. This happens whether Tor-Browser is running or not. I've checked the GPG signature which is ok and the Apple Developer Signature shows up ok as well.

Trying to launch `onionshare` from the command line shows
`[1]    2108 illegal hardware instruction  ./onionshare`

```
$ file ./onionshare
./onionshare: Mach-O 64-bit executable x86_64
```

Crash report:
[OnionShare 0.9 crashes on OS X 10.10.5.txt](https://github.com/micahflee/onionshare/files/219390/OnionShare.0.9.crashes.on.OS.X.10.10.5.txt)

**Comment by micahflee** [comment]
This also must be related to the switch to PyInstaller. I'm not sure what's causing it though yet.

**Comment by mrphs** [comment]
I've had the same problem since  #201. Removed everything and tried to reinstall again. didn't work.

**Comment by micahflee** [comment]
If the OSX version is currently not running for you, you can download the previous working version (0.8.1) from https://github.com/micahflee/onionshare/releases

**Comment by gszathmari** [comment]
I am also having this problem but with a different error message:

```
Me-MBP:~ gszathmari$ file /Applications/OnionShare.app/Contents/MacOS/onionshare 
/Applications/OnionShare.app/Contents/MacOS/onionshare: Mach-O 64-bit executable x86_64

Me-MBP:~ gszathmari$ shasum /Applications/OnionShare.app/Contents/MacOS/onionshare 
e6c4cc98884ff2f6fec025ef2f821001940f490b  /Applications/OnionShare.app/Contents/MacOS/onionshare

Me-MBP:~ gszathmari$ /Applications/OnionShare.app/Contents/MacOS/onionshare 
Illegal instruction: 4
```

I have Onionshare 0.9.0 installed on OS X 10.11.4

**Comment by micahflee** [comment]
@MacLemon can you test 0.9.1 to see if it still crashes for you? https://github.com/micahflee/onionshare/releases/tag/v0.9.1

**Comment by BenjaminHCCarr** [comment]
I have 100% success with launch and running, including file transfer with 0.9 on 10.10.5.

**Comment by MacLemon** [comment]
FYI: 0.9.1 GUI claims to require 10.11 now. (Known, see #306). CLI version works fine.

**Comment by magnus919** [comment]
Also experiencing this with 0.9.1 release, MacOS 10.12.1.

**Comment by BenjaminHCCarr** [comment]
I am not having this issue on 10.11.6 (el Capitain)
```
tyr:/Applications/OnionShare.app/Contents/MacOS benc$ ./onionshare
Onionshare 0.9.1 | https://onionshare.org/
usage: onionshare [-h] [--local-only] [--stay-open] [--transparent] [--debug]
                  filename [filename ...]
onionshare: error: the following arguments are required: filename
tyr:/Applications/OnionShare.app/Contents/MacOS benc$ ./onionshare-gui 
Onionshare 0.9.1 | https://onionshare.org/

tyr:/Applications/OnionShare.app/Contents/MacOS benc$ uname -a
Darwin tyr.local 15.6.0 Darwin Kernel Version 15.6.0: Wed Nov  2 20:30:56 PDT 2016; root:xnu-3248.60.11.1.2~2/RELEASE_X86_64 x86_64
```

@magnus919 can you try `/Applications/OnionShare.app/Contents/MacOS/onionshare --debug /System/Library/Keyboard\ Layouts/AppleKeyboardLayouts.bundle`

Here is what I get:
no tor-browser:
```
tyr:/Applications/OnionShare.app/Contents/MacOS benc$ /Applications/OnionShare.app/Contents/MacOS/onionshare --debug /System/Library/Keyboard\ Layouts/AppleKeyboardLayouts.bundle
Onionshare 0.9.1 | https://onionshare.org/
Can't connect to Tor control port on port [9151, 9153, 9051]. OnionShare requires Tor Browser to be running in the background to work. If you don't have it you can get it from https://www.torproject.org/.
```
tor-browser running:
```
tyr:/Applications/OnionShare.app/Contents/MacOS benc$ /Applications/OnionShare.app/Contents/MacOS/onionshare --debug /System/Library/Keyboard\ Layouts/AppleKeyboardLayouts.bundle
Onionshare 0.9.1 | https://onionshare.org/
Connecting to Tor control port to set up onion service on port 17600.
Staring ephemeral Tor onion service and awaiting publication
Preparing files to share.
 * Running on http://127.0.0.1:17600/ (Press CTRL+C to quit)
Give this URL to the person you're sending the file to:
http://lsnzkbb77udcp5er.onion/frank-chert

Press Ctrl-C to stop server
```

**Comment by magnus919** [comment]
@BenjaminHCCarr following your advice:

no tor-browser:
`% /Applications/OnionShare.app/Contents/MacOS/onionshare --debug /System/Library/Keyboard\ Layouts/AppleKeyboardLayouts.bundle
Onionshare 0.9.1 | https://onionshare.org/
Can't connect to Tor control port on port [9151, 9153, 9051]. OnionShare requires Tor Browser to be running in the background to work. If you don't have it you can get it from https://www.torproject.org/.`

tor-browser running:
`% /Applications/OnionShare.app/Contents/MacOS/onionshare --debug /System/Library/Keyboard\ Layouts/AppleKeyboardLayouts.bundle
Onionshare 0.9.1 | https://onionshare.org/
Connecting to Tor control port to set up onion service on port 17601.
Staring ephemeral Tor onion service and awaiting publication
Preparing files to share.
 * Running on http://127.0.0.1:17601/ (Press CTRL+C to quit)
Give this URL to the person you're sending the file to:
http://[REDACTED].onion/clio-role

Press Ctrl-C to stop server`

Having the tor-browser running does nothing, however, to resolve the problems with the GUI crashing immediately on startup.

**Comment by BenjaminHCCarr** [comment]
@magnus919 thanks for checking, was just trying to rule out the subsystem, so we know it's the GUI wrapper, and not the onion-sharing itself, which is good, plus it gives you an 'emergency' way to share if needed.

Can you try:
`$ /Applications/OnionShare.app/Contents/MacOS/onionshare-gui --debug`
and see what happens? For me the GUI just opens, and the terminal logs.

**Comment by magnus919** [comment]
@BenjaminHCCarr 
```
% /Applications/OnionShare.app/Contents/MacOS/onionshare-gui --debug
[1]    11402 illegal hardware instruction  /Applications/OnionShare.app/Contents/MacOS/onionshare-gui --debug
```

**Comment by BenjaminHCCarr** [comment]
@magnus919!!!!!! Well that gives us a place to start!!!!

@magnus919 can you do this `Apple --> About this Mac --> System Report` and post the first bit of your hardware overview? Here is mine, there is nothing confidential in it, it's just the hardware specs:
```
Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,1
  Processor Name:	Intel Core i5
  Processor Speed:	2.6 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	16 GB
  Boot ROM Version:	MBP111.0138.B17
  SMC Version (system):	2.16f68
```

just don't post the last two lines serial & uuid.

@micahflee have you seen this while debugging? Want to check before we go down the DTrace route. hardware instruction?

**Comment by magnus919** [comment]
@BenjaminHCCarr 

```
Hardware Overview:

  Model Name:	Mac mini
  Model Identifier:	Macmini6,2
  Processor Name:	Intel Core i7
  Processor Speed:	2.3 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Boot ROM Version:	MM61.0106.B0A
  SMC Version (system):	2.8f0

```

**Comment by micahflee** [comment]
This is the most frustrating issue that OnionShare has. It's not an OnionShare-specific issue, it also happens with other python apps on OS X that have been turned into binaries using py2app, PyInstaller, or cx_Freeze.

The biggest pattern I've noticed is that the crash doesn't happen on Macs that are newer than ~2012, but does happen on Macs that are ~2012 or older. This likely explains the "Illegal instruction 4" error. Different CPUs have different instruction sets, and "illegal instruction" implies that the machine code that's getting executed is not supported by the CPU. So, probably, post-2012 Macs use CPUs that are similar the older CPUs, but also support some extra instruction that the old ones don't support. And, for some reason, that instruction is included in the binary when building a python app into an OSX app bundle.

Some time ago, I spoke with a guy in a bar about this problem, and he had run into the same thing. He actually solved it by using old Mac hardware to build the binary on. If you build using an old CPU that doesn't support the illegal instruction, then the compiler won't use it.

Soon I'll have a Mac from 2011 which I'll use as a dedicated OS X build machine. I have high hopes that, if I build OnionShare on that computer with its old CPU, the resulting binary will run on any Mac without crashing.

**Comment by crwood** [comment]
@micahflee I wonder if that "guy in a bar" was me -- we spoke about this very issue about 10 or so months ago at a certain event in Europe and I made the same recommendation.. :)

In any case, I'm currently using a late 2009 iMac (model 11,1 running OS X 10.9.5 Mavericks) as a dedicated build machine for my own PyQt5/PyInstaller-based projects and, for whatever it's worth, have not yet experienced this issue with that specific combination (though, granted, I have not yet tested on any new-ish Sierra-era machines..). I would be very interested, however, in learning how you make out both on 2011 hardware and with py2app/py2exe, as I'm presently considering picking up an older (~2011) Mac Mini for the same purposes (and am on the brink of switching away from PyInstaller due to a host of other growing frustrations..).

The state of building standalone python binaries is, to be sure, pretty terrible all around though. :(

**Comment by mrphs** [comment]
@micahflee I've an early 2013 Macbook pro and never managed to get onionshare work on this computer.

**Comment by micahflee** [comment]
Ok, finally, I think I have solved this issue. I just made a pre-release for version 1.0dev1, and built it using my new 2011 Mac build machine. @MacLemon, @mrphs, @gszathmari, and anyone else experiencing it, can you test it out and confirm that it works?

https://github.com/micahflee/onionshare/releases/tag/v1.0dev1

**Comment by mrphs** [comment]
@micahflee It finally worked for me on this computer!!!! Thank you!!!

**Comment by gszathmari** [comment]
It is still crashing on my laptop. I hope this screenshot helps

<img width="897" alt="screen shot 2017-02-23 at 23 49 52" src="https://cloud.githubusercontent.com/assets/4806014/23259770/ca253756-fa22-11e6-9577-3d2e729ebb41.png">

**Comment by gszathmari** [comment]
It's working, thanks a million @micahflee

**Comment by micahflee** [comment]
YAAAY!!!
