### ISSUE TITLE
Make sure tests can find correct paths

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#284]
It looks like tests fail when running from certain places, e.g.

```

I: pybuild base:184: cd
/build/onionshare-0.9/.pybuild/pythonX.Y_3.5/build; python3.5 -m nose test
..EE..
======================================================================
ERROR: load_strings() loads English by default
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File
"/build/onionshare-0.9/.pybuild/pythonX.Y_3.5/build/test/onionshare_strings_test.py",
line 33, in test_load_strings_defaults_to_english
    strings.load_strings()
  File
"/build/onionshare-0.9/.pybuild/pythonX.Y_3.5/build/onionshare/strings.py",
line 40, in load_strings
    for filename in os.listdir(locale_dir):
FileNotFoundError: [Errno 2] No such file or directory:
'/build/onionshare-0.9/.pybuild/pythonX.Y_3.5/build/resources/locale'

======================================================================
ERROR: load_strings() loads other languages in different locales
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File
"/build/onionshare-0.9/.pybuild/pythonX.Y_3.5/build/test/onionshare_strings_test.py",
line 40, in test_load_strings_loads_other_languages
    strings.load_strings("fr")
  File
"/build/onionshare-0.9/.pybuild/pythonX.Y_3.5/build/onionshare/strings.py",
line 40, in load_strings
    for filename in os.listdir(locale_dir):
FileNotFoundError: [Errno 2] No such file or directory:
'/build/onionshare-0.9/.pybuild/pythonX.Y_3.5/build/resources/locale'
```

**Comment by u451f** [comment]
That's what currently prevents us from uploading the new version to Debian, if anybody wants to help :)

**Comment by dballard** [comment]
So I don't seem to have this problem in Debian 8 Jessie. 
```
$ python3 --version
Python 3.4.2
$ python3 -m nose --version
python3 -m nose version 1.3.4
$ dpkg -k python3-stdeb
...
ii python3-stdeb 0.8.2-4
```

For me pybuild works, but seems to report 

```
....
Ran 0 tests in 0.000s

OK
```
and works (obviously, and incorrectly but for different reasons)

I think on an Ubuntu 16.04 system I may have seen the described error however.

Thoughts: seems like it might be new behavior in python3.5 (from 3.4) or new packages of nose and stdeb. Right now it looks like the tests directory simply isn't being copied and run against in the right order or at all.

Secondly, what the above seems to indicate is that in that time and place, the 'tests' directory has been copied into the appropriate build directory, but the 'resources/locale' directory hasn't so when you try and load onionshare and run string tests, the locale resources aren't being loaded.
Some kind of misconfig with stdeb?

**Comment by u451f** [comment]
Hi Dan,

in order to build an official Debian package, I can't use stdeb/pybuild. Instead, I use git-buildpackage. The test path seems to be wrong when building the package like that.

**Comment by dballard** [comment]
```
user@code-deb:~/src/projects/onionshare$ git-buildpackage 
gbp:error: Can't determine package type: Failed to read changelog: [Errno 2] No such file or directory: './debian/changelog'
```

what do you use to populate/create that?

**Comment by u451f** [comment]
See the "Git" field on https://tracker.debian.org/pkg/onionshare
pointing to https://anonscm.debian.org/git/pkg-privacy/packages/onionshare.git.
Building should be done from the debian/sid branch. 0.9 has been imported there but stayed unreleased due to this error.

**Comment by dballard** [comment]
```
onionshare/.pybuild/pythonX.Y_3.4/build$ ls
onionshare  onionshare_gui
```

So again, I'm using older versions than you, but what I'm seeing is that for me neither the 'test' or 'resources' directory are showing up in the pybuild. So for me no tests are then found and no tests are run and things are fine.
I think your slightly newer versions of things are one part smarter and are detecting the 'test' directory and pulling it it, but the problem is the same. The 'test' and 'resources' directory are explicitly stated in your build configs as required so now, tests actually run but are still missing part of the package ('resources') and fail (where mine erroneously were absent and didn't run at all)

What controls how pybuild determines what folders to 'build' and put in '.pybuild/pythonX.Y_3.4/build' in your build system? Adding 'test' and 'resources' to that should fix this.

**Comment by u451f** [comment]
Hi Dan,

thanks I'll try to look into it. But indeed, this problem did not exist in older versions :)

**Comment by dballard** [comment]
Oh, cool, thanks, I forgot about that data. I'll take a look at commits
since then to see what was changed for likely candidates of cause :)

**Comment by micahflee** [comment]
I'm trying to fix this issue, but I'm having trouble reproducing it. @u451f can you write out the exact commands you run to build the debian package from the https://anonscm.debian.org/git/pkg-privacy/packages/onionshare.git repo?

**Comment by micahflee** [comment]
Actually, nevermind. I figured out how to reproduce it. I just change to any directory other than the root and try running the tests, e.g.:

```sh
$ cd screenshots
$ nosetests3 ../test
..EE..
======================================================================
ERROR: load_strings() loads English by default
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/user/code/onionshare/test/onionshare_strings_test.py", line 32, in test_load_strings_defaults_to_english
    strings.load_strings(helpers)
  File "/usr/lib/python3/dist-packages/onionshare/strings.py", line 40, in load_strings
    for filename in os.listdir(locale_dir):
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/resources/locale'

======================================================================
ERROR: load_strings() loads other languages in different locales
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/user/code/onionshare/test/onionshare_strings_test.py", line 39, in test_load_strings_loads_other_languages
    strings.load_strings(helpers, "fr")
TypeError: load_strings() takes from 0 to 1 positional arguments but 2 were given

----------------------------------------------------------------------
Ran 6 tests in 0.315s

FAILED (errors=2)
```

**Comment by micahflee** [comment]
@u451f can you confirm that this issue is fixed and that you can build what's currently in the master branch in debian with the tests passing? If so, I'll make the 0.9.1 release.

**Comment by u451f** [comment]
Hi Micah,

thanks for fixing this. This works now when run with nosetests indeed.
So I'll try to adapt the Debian packaging for that.

Cheers!

**Comment by micahflee** [comment]
:+1:
