### ISSUE TITLE
Notification when download begins

### ISSUE THREAD

**Issue by anseljh** [micahflee/onionshare#285]
Feature suggestion: do a desktop notification when a download begins (and maybe when it finishes). This would be nice when you're waiting for someone to download, and don't want to watch the UI.

**Comment by freddymartinez9** [comment]
Just to clarify @anseljh do you think the person initiating the download should get the notification? If I'm running a long standing .onion that is popular, I wouldn't want to get notifications every single time a user started downloading my file.

**Comment by anseljh** [comment]
The person serving would get a notification. I agree this wouldn't be useful when you leave the share open, but for one-off shares (OnionShare's default), it would be.

**Comment by micahflee** [comment]
I think this is a cool idea.

**Comment by micahflee** [comment]
Implemented!
