### ISSUE TITLE
Firejail Profile

### ISSUE THREAD

**Issue by HulaHoopWhonix** [micahflee/onionshare#291]
Hi Micah. Can you please consider contributing a [Firejail](https://github.com/netblue30/firejail) profile upstream to cover Onionshare? Its a very popular desktop sandboxing program that has a variety of mechanisms to reduce attack surface including cgroups, namespaces and seccomp filters.

PS. Yawning also chose it for TBB containment on Linux.

**Comment by micahflee** [comment]
Yes, I'd be willing to ship a Firejail profile with  OnionShare. Want to make a pull request?

**Comment by HulaHoopWhonix** [comment]
I would if I could but we are still working on supporting it and Ricochet in Whonix :/
