### ISSUE TITLE
Support several different Tor configurations

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#292]

**Comment by micahflee** [comment]
Ephemeral hidden services aren't supported until python3-stem 1.4 (the current version in jessie is 1.2.2) and tor 0.2.7 (the current version in jessie is 0.2.5.12). So this won't work in jessie, but likely in newer versions of linux.

**Comment by not83** [comment]
Would love to see support for this.

**Comment by micahflee** [comment]
I've received a tip: Apparently (at least in debian and I think ubuntu), if the user is in the debian-tor group, control port access should just work with a system tor. I haven't tested yet.

**Comment by micahflee** [comment]
I merged my own PR that basically implements this (#328) but it make you specify Tor variables using `TOR_CONTROL_PORT` and `TOR_AUTHENTICATION_PASSWORD` environment variables. I decided to do it this way because it already keeps an eye out for the `TOR_CONTROL_PORT` environment variable because it's required for Tails support. However, I realized that setting these environment variables actually interferes with opening Tor Browser on a normal (non-Tails) system.

So I think this issue isn't actually done yet. I want to refactor to make an actual OnionShare config file, and a simple GUI preferences dialog to let people change their Tor configuration. For the time-being, I'll support this as well as the `TOR_CONTROL_PORT` environment variable (to avoid interfering with Tails support), but at some point it might make sense to have Tails just ship the appropriate config file, to simplify the code.

**Comment by micahflee** [comment]
It looks like Tor Browser 6.5 no longer listens on port 9151 for the tor control port. Instead, you have to connect to a socket file. And the path to the socket file will be different in Windows, Linux, and OS X.

I've renamed this issue to encompass this as well. OnionShare needs to support connecting to the Tor control port using:

* A configurable port
* A socket file

And with these authentications:

* No authentication
* Password authentication
* Cookie authentication

The default configuration should work with the latest version of Tor Browser.

**Comment by micahflee** [comment]
This is now mostly done! It just needs thorough testing in Windows and OS X.

![screenshot_2016-12-29_13-51-29](https://cloud.githubusercontent.com/assets/156128/21556064/8ead0338-cdd2-11e6-918c-d4ca61724b52.png)

**Comment by BenjaminHCCarr** [comment]
Happy to test. Can you post a zip. I can test against tor, and tor-browser on OSX.

**Comment by guangyue** [comment]
do you know how to use the tor to the https

2017-01-01 11:37 GMT+08:00 Ben <notifications@github.com>:

**Comment by BenjaminHCCarr** [comment]
> do you know how to use the tor to the https

@guangyue well I run multiple tor bridge and exit nodes, as well as tor-browser, orweb, etc; and have control over my local tor proxy on my box with any ports, permission I want.

Or do you have a general tor question about https?

**Comment by micahflee** [comment]
I've done a bunch of testing, and this seems to work great.
