### ISSUE TITLE
gpg encryption - enhancement

### ISSUE THREAD

**Issue by catskillmarina** [micahflee/onionshare#299]
It would be helpful if onionshare had a feature to gpg encrypt the uploaded file to a chosen recipient. If the key was not found on the local gpg keyring onionshare could (after warnings) download the key from
a keyserver.

**Comment by u451f** [comment]
This request seems to be a duplicate of #154.

I personally don't think that every software should be able to brew coffee, sugar it and drink it too. Thus, if you run Debian or Tails I would rather recommend using the seahorse-nautilus extension (https://tracker.debian.org/pkg/seahorse-nautilus) to create an encrypted file/archive first. Or use the OpenPGP-Applet to easily encrypt text files for example: https://tracker.debian.org/pkg/openpgp-applet

**Comment by catskillmarina** [comment]
thanks - i look forward to onionshare in tails !

**Comment by micahflee** [comment]
Agreed
