### ISSUE TITLE
0.9.1 requires 10.11.x

### ISSUE THREAD

**Issue by BenjaminHCCarr** [micahflee/onionshare#306]
It is very odd in standard FOSS numbering to abandon an OS version in a point release, particularly a minor point release. 0.9 runs fine but 0.9.1 requires 10.11. Not everyone who uses this software will have updated, or has reason or concern for upgrading.
![screen shot 2016-09-07 at 11 45 05 pm](https://cloud.githubusercontent.com/assets/8225968/18336472/80c6c89c-7555-11e6-9d67-258671eb713c.png)

**Comment by micahflee** [comment]
Oops, I had no idea that 0.9.1 no longer works in OS X 10.10. This must have been a byproduct of switching from PyInstaller to cx_Freeze.

**Comment by micahflee** [comment]
Did you get that popup while running the `OnionShare.pkg` installer or while running `/Applications/OnionShare.app`?

**Comment by BenjaminHCCarr** [comment]
Sadly it's on first run not on install. Did you move from python 2.7? I know a lot of stuff is breaking as they migrate. There is zero warning in the install, but on first launch you get that error. So people are using ~20+ MB that may be expensive and installing over 0.9 only to find it doesn't run. I tried toggling back and forth. Attaching a slew of logs for you, I don't have time to look at them, but I love the app.

[onionshare_2016-08-25-091422_tyr.crash.txt](https://github.com/micahflee/onionshare/files/462758/onionshare_2016-08-25-091422_tyr.crash.txt)
[onionshare_2016-08-25-091422-1_tyr.crash.txt](https://github.com/micahflee/onionshare/files/462759/onionshare_2016-08-25-091422-1_tyr.crash.txt)
[onionshare_2016-09-07-154226_tyr.spin.txt](https://github.com/micahflee/onionshare/files/462755/onionshare_2016-09-07-154226_tyr.spin.txt)
[onionshare_2016-09-07-154811_tyr.spin.txt](https://github.com/micahflee/onionshare/files/462757/onionshare_2016-09-07-154811_tyr.spin.txt)
[onionshare_2016-09-07-232831_tyr.spin.txt](https://github.com/micahflee/onionshare/files/462754/onionshare_2016-09-07-232831_tyr.spin.txt)
[onionshare.log.txt](https://github.com/micahflee/onionshare/files/462756/onionshare.log.txt)

**Comment by micahflee** [comment]
We switched from python2 to python3 a few releases ago. The major change that I think affected this is switching to cx_Freeze #303.

I'm sure that if you cloned the git repo, install the dependencies, and run `python3 -c "import onionshare_gui; onionshare_gui.main()"` it'll run fine on your computer. But cx_Freeze is the software that takes all of the python code and creates an `OnionShare.app`, including an executable binary.

That executable, or maybe just that .app bundle's `Info.plist`, has something in it that specifies the earliest version of OSX it works on.

**Comment by BenjaminHCCarr** [comment]
I can do that to test. I pulled the binary from releases. Also retweeted you.

**Comment by BenjaminHCCarr** [comment]
It's cx_freeze:
```
sudo pip3 install dist/cx_Freeze-5.0-cp35-cp35m-macosx_10_11_x86_64.whl
Password:
The directory '/Users/benc/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/benc/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement 'dist/cx_Freeze-5.0-cp35-cp35m-macosx_10_11_x86_64.whl' looks like a filename, but the file does not exist
cx_Freeze-5.0-cp35-cp35m-macosx_10_11_x86_64.whl is not a supported wheel on this platform.
```

oddly building from source:
```
tyr:~/Code/anthony_tuininga-cx_freeze-ee863267fe9e benc$ python3 setup.py bdist_wheel
running bdist_wheel
running build
running build_py
creating build
creating build/lib.macosx-10.10-x86_64-3.5
creating build/lib.macosx-10.10-x86_64-3.5/cx_Freeze
<snip>
running install_scripts
creating build/bdist.macosx-10.10-x86_64/wheel/cx_Freeze-5.0.data
creating build/bdist.macosx-10.10-x86_64/wheel/cx_Freeze-5.0.data/scripts
copying build/scripts-3.5/cxfreeze -> build/bdist.macosx-10.10-x86_64/wheel/cx_Freeze-5.0.data/scripts
copying build/scripts-3.5/cxfreeze-quickstart -> build/bdist.macosx-10.10-x86_64/wheel/cx_Freeze-5.0.data/scripts
changing mode of build/bdist.macosx-10.10-x86_64/wheel/cx_Freeze-5.0.data/scripts/cxfreeze to 755
changing mode of build/bdist.macosx-10.10-x86_64/wheel/cx_Freeze-5.0.data/scripts/cxfreeze-quickstart to 755
creating build/bdist.macosx-10.10-x86_64/wheel/cx_Freeze-5.0.dist-info/WHEEL
```

tyr:~/Code/anthony_tuininga-cx_freeze-ee863267fe9e benc$ file cxfreeze*
cxfreeze:             a /usr/bin/python script text executable
cxfreeze-postinstall: ASCII English text
cxfreeze-quickstart:  a /usr/bin/python script text executable

**Comment by micahflee** [comment]
Oooh. I bet it's because I built cx_Freeze on my Mac running 10.11. I bet if I build it on an earlier version of OSX it will work on earlier versions. Good find!

**Comment by BenjaminHCCarr** [comment]
Hmmm, it's a very complicated app to make a homebrew formula for, we made a cask foryour releases, I guess I'll just have to do macos.version >= El_Capitan for 0.9.1

**Comment by micahflee** [comment]
Ok @BenjaminHCCarr can you try this binary for me? It's the exact same code as 0.9.1, but I built it on a machine running OS X 10.9. It's codesigned, so it shouldn't give you a Gatekeeper warning. https://share.riseup.net/#aSOxcIs7T1_grU4psLhuGA

**Comment by micahflee** [comment]
Actually, it looks like I can upload it directly to the github issue if I zip it first.

[OnionShare.pkg.zip](https://github.com/micahflee/onionshare/files/470475/OnionShare.pkg.zip)

**Comment by BenjaminHCCarr** [comment]
Yes, I can try both this evening (EDT) and report back. Thanks for codesigning, I do enough FOSS stuff, that's all disabled anyway, but can turn it on, and report back. Thanks for doing the builds!

**Comment by BenjaminHCCarr** [comment]
> Actually, it looks like I can upload it directly to the github issue if I zip it first.

One of my favorites is when you can upload .txt but not .log........

**Comment by BenjaminHCCarr** [comment]
Neither the riseup nor github pkg's worked, both installed without error; but kicked out useful errorslogs it looks like. Sorry to say this wasn't an easy fix. The Riseup was much faster so I tried it faster but didn't know if they injected, so tried the github zip. The sha256 are the same:

```
CMBB:~/.Trash courtneyblair$ shasum -a 256 OnionShare*.pkg
a29dc817ba6ef69c69d8b15782beedea37417f35175ee1c1e6cd5d62af360d5b  OnionShare 2.pkg
a29dc817ba6ef69c69d8b15782beedea37417f35175ee1c1e6cd5d62af360d5b  OnionShare.pkg
```
Sorry for formatting, but OSX error dump doesn't allow RTF, so breaks formatting, so I dumped to HTML then PDF'ed, at least it will make everythign line up.
[onoionshare_0.9.1_github.pdf](https://github.com/micahflee/onionshare/files/471045/onoionshare_0.9.1_github.pdf)

Thanks for your product, and your continued support with this issue:

```
CMBB:~ courtneyblair$ python3 --version
Python 3.5.2
```

**Comment by MacLemon** [comment]
Launching onionshare from the command line works fine on 10.10.5, only the GUI claims to require 10.11.x.

**Comment by micahflee** [comment]
My new build machine is running macOS X 10.9, so all future binaries will work in that version of macOS and newer.

**Comment by micahflee** [comment]
Before I close this issue, I'd like to test to make sure that my new build system actually works. I just made a pre-release for version 1.0dev1, which should fix this issue. 

@BenjaminHCCarr, @MacLemon can you test it out and confirm that it works?
https://github.com/micahflee/onionshare/releases/tag/v1.0dev1

**Comment by micahflee** [comment]
Actually, I realize that I've tested this myself in macOS X 10.9 and it worked great. Still, please test it, but I'm going to consider this issue solved.
