### ISSUE TITLE
cannot run onionshare from source folder without installation

### ISSUE THREAD

**Issue by adrelanos** [micahflee/onionshare#311]
https://github.com/micahflee/onionshare/blob/master/BUILD.md implies one can run onionshare without actually installing it right form the source folder, right?

> After that you can try both the CLI and the GUI version of OnionShare:

Seems like a great feature during development. However, that does not work.

```
./install/scripts/onionshare
```

```
Traceback (most recent call last):
  File "./install/scripts/onionshare", line 21, in <module>
    import onionshare
ImportError: No module named 'onionshare'
```

**Comment by micahflee** [comment]
The scripts in `./install/scripts` are what actually get installed systemwide as part of the package. Instead, a better solution is to make a new set in scripts in `./dev_scripts` that specifically load the onionshare module and resources from the source tree instead of system-wide.
