### ISSUE TITLE
port from create_hidden_service to create_ephemeral_hidden_service

### ISSUE THREAD

**Issue by adrelanos** [micahflee/onionshare#313]
https://stem.torproject.org/api/control.html#stem.control.Controller.create_hidden_service

As of Tor 0.2.7.1 there's two ways for creating hidden services, and this method is no longer recommended. Rather, try using create_ephemeral_hidden_service() instead.

https://stem.torproject.org/api/control.html#stem.control.Controller.create_ephemeral_hidden_service

Related:
- Support transparent torification #220

**Comment by micahflee** [comment]
OnionShare is already using `create_ephemeral_hidden_service` (in [onion.py](https://github.com/micahflee/onionshare/blob/master/onionshare/onion.py#L133)):

```python
res = self.c.create_ephemeral_hidden_service({ 80: port }, await_publication=True, basic_auth=basic_auth)
```
