### ISSUE TITLE
Onionshare.exe and Onionshare-gui.exe do not work on Win XP (Error msg: "*.exe is not a valid Win32 application.")

### ISSUE THREAD

**Issue by IamLondon** [micahflee/onionshare#317]
Whenever I try to launch Onionshare.exe or Onionshare-gui.exe I get the error message: "C:\Program Files\Onionshare\Onionshare-gui.exe is not a valid Win32 application."

I'm using Windows XP Service Pack 3.

**Comment by micahflee** [comment]
Microsoft [stopped supporting Windows XP](https://www.microsoft.com/en-us/WindowsForBusiness/end-of-xp-support) on April 8, 2014. Since it's an obsolete operating system, I don't want to spend development resources on making sure OnionShare works with it.

**Comment by micahflee** [comment]
(@IamLondon, you should upgrade at least to Windows 7, but probably to Windows 10. Windows XP doesn't receive security updates anymore.)
