### ISSUE TITLE
Recursive repaint crash

### ISSUE THREAD

**Issue by b3sigma** [micahflee/onionshare#334]
Seems to happen intermittently and haven't yet figured out why it only happens sometimes. To repro, I simply drop a file in and click start sharing, it seems to get through creating the tor service but before I see a download progress bar or anything:
 
```
$ ./dev_scripts/onionshare-gui
Onionshare 0.9.2 | https://onionshare.org/
 * Running on http://127.0.0.1:17600/ (Press CTRL+C to quit)
Configuring onion service on port 17600.
Staring ephemeral Tor onion service and awaiting publication
QWidget::repaint: Recursive repaint detected
Segmentation fault (core dumped)
```

The first time it did it I briefly looked at the trace and it looked fairly deep in the C++ callstack. Will investigate and post more info.

**Comment by b3sigma** [comment]
With a bit more investigation, it looks to be a threading issue with the zip progress bar. The most consistent reproduction for me comes with small files, like the project's README.md.

**Comment by micahflee** [comment]
Thanks for figuring this out and fixing it.
