### ISSUE TITLE
xxx.onion website (replicating onionshare.org)

### ISSUE THREAD

**Issue by github-user-1** [micahflee/onionshare#338]
I think it would be great to have the website at onionshare.org also available via a x.onion tor-website (replicated hidden service) - setting up such a hidden-service to offer a .onion site isn't that hard for someone understanding how Tor works.

This is obviously nothing urgent or really important - but nonetheless it's a real nice to have to help spreading the word about Tor's capabilities and to promote Tor through people seeing and using real useful sites 'within' Tor.

**Comment by micahflee** [comment]
This is a great idea. I just opened an issue in the onionshare-website repo https://github.com/micahflee/onionshare-website/issues/16

**Comment by e5f3c2ea895af0f27667** [comment]
@github-user-1 And here it is: http://elx57ue5uyfplgva.onion/

**Comment by github-user-1** [comment]
Wow, that was fast - it works; wonderful and congratulations!
