### ISSUE TITLE
bug, ADD_ONION tries port 0?

### ISSUE THREAD

**Issue by adrelanos** [micahflee/onionshare#343]
Just observed that.

Incoming Tor ControlPort command.

> ADD_ONION NEW:BEST Port=80,0

This is predestined to fail.

> 512 Invalid VIRTPORT/TARGET

Is this something caused by my Whonix setup or could you check please if there can be a condition under which the VIRTPORT will be zero?

**Comment by mig5** [comment]
I'm going to close this as I can't see anywhere in the code that it could possibly use port 0 anymore. 

Moreover, there are now additional sanity checks that will throw an alert if somehow a proper random port couldn't be obtained, so it should never get that far again. (https://github.com/micahflee/onionshare/pull/484)
