### ISSUE TITLE
show error message rather than python exception on restricted Tor control access

### ISSUE THREAD

**Issue by adrelanos** [micahflee/onionshare#344]
This is what will happen in Whonix 14, because one has to drop a control port filter configuration snippet first to whitelist the Tor control protocol command required by onionshare.

Currently only a python exception is logged to the console which is not visible within the gui.

```
Onionshare 0.9.2 | https://onionshare.org/
 * Running on http://127.0.0.1:17600/
Configuring onion service on port 17600.
Staring ephemeral Tor onion service and awaiting publication
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/onionshare_gui/__init__.py", line 177, in start_onion_service
    self.app.start_onion_service()
  File "/usr/lib/python3/dist-packages/onionshare/__init__.py", line 89, in start_onion_service
    self.onion_host = self.onion.start(self.port)
  File "/usr/lib/python3/dist-packages/onionshare/onion.py", line 252, in start
    res = self.c.create_ephemeral_hidden_service({ 80: port }, await_publication=True)
  File "/usr/lib/python3/dist-packages/stem/control.py", line 2860, in create_ephemeral_hidden_service
    self.add_event_listener(hs_desc_listener, EventType.HS_DESC)
  File "/usr/lib/python3/dist-packages/stem/control.py", line 3010, in add_event_listener
    raise stem.ProtocolError('SETEVENTS rejected %s' % ', '.join(failed_events))
stem.ProtocolError: SETEVENTS rejected HS_DESC
```

If that happens and if Whonix is detected (check for existence of file /usr/share/anon-ws-base-files/workstation), could you please make onionshare an error popup such as the following?

```
ERROR

To make onionshare work in Whonix, please have a look at the Whonix onionshare documentation.
https://www.whonix.org/wiki/onionshare
```

More user-friendly wording suggestions very much welcome.

**Comment by micahflee** [comment]
Hey @adrelanos. I can definitely make OnionShare display an error message like that if that exception is thrown.

I'd love to have better support in OnionShare, but I don't currently have a Whonix development environment set up. Is there anything else that needs to get changed in OnionShare to make this happen, besides properly handling that exception and displaying that note? Will that wiki page include instructions on things that the user has to manually do that will then just make OnionShare work inside the whonix workstation?

**Comment by adrelanos** [comment]
> Hey @adrelanos. I can definitely make OnionShare display an error message like that if that exception is thrown.

That would be awesome!

> Is there anything else that needs to get changed in OnionShare to make this happen, besides properly handling that exception and displaying that note?

No.

> Will that wiki page include instructions on things that the user has to manually do that will then just make OnionShare work inside the whonix workstation?

Yes.

(Btw instructions will look like this: https://www.whonix.org/wiki/Next#onionshare)

After applying these instructions, onionshare will work once Whonix 14 has been released.

There is nothing that onionshare could do to improve Whonix support. I have some ideas how to improve usability, to have a better point and click experience. (Using a wrapper, that uses a qrexec call, that asks to enable the onionshare profile on the gateway, and setting up the workstation.) However, that is nothing, that should be done directly by onionshare.

**Comment by adrelanos** [comment]
> Is there anything else that needs to get changed in OnionShare to make this happen, besides properly handling that exception and displaying that note?

Well, there is this ticket here:
https://github.com/micahflee/onionshare/issues/220#issuecomment-271536830

**Comment by adrelanos** [comment]
This broke in Whonix 15 (Debian buster based) with onionshare Debian buster version.

```
onionshare some-file
Onionshare 1.3.2 | https://onionshare.org/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/stem/socket.py", line 574, in _make_socket
    control_socket.connect(self.path)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/onionshare/onion.py", line 252, in connect
    self.c = Controller.from_socket_file(path=self.tor_control_socket)
  File "/usr/lib/python3/dist-packages/stem/control.py", line 1037, in from_socket_file
    control_socket = stem.socket.ControlSocketFile(path)
  File "/usr/lib/python3/dist-packages/stem/socket.py", line 554, in __init__
    self.connect()
  File "/usr/lib/python3/dist-packages/stem/socket.py", line 176, in connect
    self._socket = self._make_socket()
  File "/usr/lib/python3/dist-packages/stem/socket.py", line 577, in _make_socket
    raise stem.SocketError(exc)
stem.SocketError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/onionshare.anondist-orig", line 22, in <module>
    onionshare.main()
  File "/usr/lib/python3/dist-packages/onionshare/__init__.py", line 86, in main
    onion.connect(settings=False, config=config)
  File "/usr/lib/python3/dist-packages/onionshare/onion.py", line 255, in connect
    raise BundledTorBroken(strings._('settings_error_bundled_tor_broken', True).format(e.args[0]))
onionshare.onion.BundledTorBroken: Something is wrong with OnionShare connecting to Tor in the background:
[Errno 2] No such file or directory
```

Could you please reopen?

**Comment by mig5** [comment]
I don't see us making changes to OnionShare 1.3.x since OnionShare 2.0 has superseded it since February, but I'll re-open for discussion..

Note that the official Whonix wiki docs (which I contributed to) recommend to install via git rather than rely on official Debian packages.

**Comment by adrelanos** [comment]
Wasn't aware of 1.3 vs 2.0.

> Note that the official Whonix wiki docs (which I contributed to) recommend to install via git rather than rely on official Debian packages.

I see. I was hoping that in Whonix 15 (buster based) we could acquire onionshare from packages.debian.org and install onionshare by default.

> Because of the Buster freeze, not sure it will really be fixable.

Indeed.

> Does the bug still occur in OnionShare 2 on Whonix 15, when installed via git?

```
./dev_scripts/onionshare setup.cfg 
OnionShare 2.0 | https://onionshare.org/
Setting up onion service on port 17638.

There was an error with Tor: SETEVENTS rejected HS_DESC
```

**Comment by mig5** [comment]
Commit that caused this regression

cc265491

Since what we wanted was a Whonix-specific error, maybe instead we should just add to the Whonix wiki documentation for OnionShare (or the official OnionShare wiki), 'If you see an error SETEVENTS rejected HS_DESC, you need to follow [...] these instructions to make it work'.
