### ISSUE TITLE
Trying to share unreadable files results in silently ignoring them

### ISSUE THREAD

**Issue by intrigeri** [micahflee/onionshare#345]
As a user, I've experienced a UX problem, that's especially important when onionshare is run under some sandbox or confinement: if I add, in the GUI, files that onionshare is not allowed to read, then onionshare will simply share an empty archive. Arguably there's already indirect feedback about it to the user: the total size of the to-be-shared files is displayed. Still, it's suboptimal: first, it's _indirect_ feedback (one has to look for it and reason about it to notice there's a problem); second, when sharing a folder that contains both readable and unreadable files, it's hard to notice that the total size is not what it should be.

I'm not a UX expert, so I won't bother suggesting solutions, and will stick to my user hat for today :)

**Comment by micahflee** [comment]
Heh, thanks for reporting. This is definitely a bug.
