### ISSUE TITLE
OnionShare will fail if a non-ControlPort service runs on the TCP port it tries

### ISSUE THREAD

**Issue by fred-a-kemp** [micahflee/onionshare#346]
OnionShare 0.9.1 will attempt to establish control connections on TCP ports 9151, 9153, 9051, in that order. If something else listens on the TCP port, we'll get a `stem.ProtocolError: Badly formatted reply line: beginning is malformed` thrown, and then `stem.connection.IncorrectSocketType: unable to use the control socket`. OnionShare only expects a `SocketError` here, but apparently there are more exceptions that it should ignore, so it can proceed with the next port. E.g. in my case, I have the `ControlPort` on 9051 but I had a `SocksPort` 9151 as well, and that was enough to make OnionShare fail without ever trying 9051.

I see this code has changed post-0.9.1, and I think for the worse vs this bug -- now it will not even try to authenticate during the port testing, so it's not just a matter of ignoring more exceptions to make OnionShare proceed to test the other ports.

**Comment by micahflee** [comment]
Actually, I think the recent changes solve this issue. I just started a web server on 9151 and then used the new OnionShare UI to say the control port is 127.0.0.1:9151, and here's the error:

![screenshot_2017-01-30_17-16-33](https://cloud.githubusercontent.com/assets/156128/22448695/0021a5b8-e710-11e6-9cc3-381e9c52311e.png)

OnionShare is indeed trying to connect to the web server as a Tor controller:

```
$ python -m SimpleHTTPServer 9151
Serving HTTP on 0.0.0.0 port 9151 ...
127.0.0.1 - - [30/Jan/2017 17:15:42] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2017 17:15:58] code 400, message Bad HTTP/0.9 request type ('PROTOCOLINFO')
127.0.0.1 - - [30/Jan/2017 17:15:58] "PROTOCOLINFO 1" 400 -
127.0.0.1 - - [30/Jan/2017 17:15:58] code 400, message Bad HTTP/0.9 request type ('PROTOCOLINFO')
127.0.0.1 - - [30/Jan/2017 17:15:58] "PROTOCOLINFO 1" 400 -
127.0.0.1 - - [30/Jan/2017 17:16:07] code 400, message Bad HTTP/0.9 request type ('PROTOCOLINFO')
127.0.0.1 - - [30/Jan/2017 17:16:07] "PROTOCOLINFO 1" 400 -
127.0.0.1 - - [30/Jan/2017 17:16:07] code 400, message Bad HTTP/0.9 request type ('PROTOCOLINFO')
127.0.0.1 - - [30/Jan/2017 17:16:07] "PROTOCOLINFO 1" 400 -
127.0.0.1 - - [30/Jan/2017 17:16:14] code 400, message Bad HTTP/0.9 request type ('PROTOCOLINFO')
127.0.0.1 - - [30/Jan/2017 17:16:14] "PROTOCOLINFO 1" 400 -
127.0.0.1 - - [30/Jan/2017 17:16:14] code 400, message Bad HTTP/0.9 request type ('PROTOCOLINFO')
127.0.0.1 - - [30/Jan/2017 17:16:14] "PROTOCOLINFO 1" 400 -
```

So I actually think this will no longer be an issue in the 1.0 release.
