### ISSUE TITLE
"Can't connect to Tor controller"

### ISSUE THREAD

**Issue by github-user-1** [micahflee/onionshare#347]
I get the following on my server (debian):
```
admin@xxx:~ $ onionshare --transparent text.txt
Onionshare 0.9.2 | https://onionshare.org/
Can't connect to Tor controller. Is Tor Browser running in the background? If you don't have it you can get it from: https://www.torproject.org/.
```
I have tor setup and running perfectly fine on the server itself, e.g:
```
admin@xxx:~ $ curl https://check.torproject.org/api/ip ; echo
{"IsTor":true,"IP":"89.234.157.254"}
```
Extract from torrc:
```
ControlPort 9051
CookieAuthentication 1
HashedControlPassword 16:9080CE708866632xxxxxxxxxx
```

**Comment by micahflee** [comment]
OnionShare 0.9.1 doesn't support a system Tor, and it doesn't support cookie authentication like this. But the next release, 1.0, will indeed support this, and the code is already in master. You'll then be able to configure OnionShare's connection to the Tor controller to your heart's content.

I've already written the wiki page explaining how it all works: https://github.com/micahflee/onionshare/wiki/Connecting-to-Tor
