### ISSUE TITLE
"Stop sharing automatically" is a confusing option

### ISSUE THREAD

**Issue by georgeowell** [micahflee/onionshare#349]
When deploying Onionshare, I noticed users are confused by the "Stop sharing automatically" tickbox. This isn't a term that's self explanatory and doesn't accurately relate to verbose intended behaviour which is to allow sharing of the file(s) more than one time. 

I suggest that it is replaced by the term:
"Stop After First Download"

Or even:
"Stop Sharing After First Download"

Or to make it as verbose as possible:
"Stop Sharing After One Download"

**Mockup:**
![onionshare stop sharing](https://cloud.githubusercontent.com/assets/18296993/22120529/fac046b0-de77-11e6-97b0-d6548f19d5d0.png)

It's a small change that I think would improve usability, especially noticeable for non-english speakers using the app in English. 

I also propose the first letter of each word should be capitalised for consistency ^.^

**Comment by e5f3c2ea895af0f27667** [comment]
@georgeowell What about "Automatically stop sharing after download"?

**Comment by georgeowell** [comment]
I think it's still not clear enough...

"Automatically" just doesn't really mean anything. It's not really an fully automatic process if it's a tick box that requires a user choice/interaction.

I think "Download" on it's own leaves some ambiguity about whether it refers to a single person downloading the files or multiple people who each "Download" the file separately, which "Stop Sharing After First Download" avoids.

**Comment by micahflee** [comment]
@georgeowell thank you, I think this is an excellent suggestion.
