### ISSUE TITLE
feat request: automatically strip exif data

### ISSUE THREAD

**Issue by kristovatlas** [micahflee/onionshare#351]
In order to prevent people from accidentally leaking confidential data, it would be nice if this stripped EXIF data from files before making them available.

**Comment by github-user-1** [comment]
I would strongly vote against this for three reasons:

- This is messing around with user data; if someone wants to share something then the expectation is that the receiving party gets what was sent.

And even more important:

- Exif is just one of probably thousands of possible leaks. It will never be possible to remove any personal data like exif in an automated way. There could be all kind of thinks stored in any kind of files. It is always the responsibility of the user to define what he/she wants to share.

And overall:
- Isn't onionshare about sharing something (files) in a private, encrypted manner with people one trusts? This is not about public data and sending is over Tor...

**Comment by adrelanos** [comment]
Kristov Atlas:
> In order to prevent people from accidentally leaking confidential data, it would be nice if this stripped EXIF data from files before making them available.
> 

The user might actually want to share it in some cases.

This should be opt-in or opt-out. Certainly not a non-configurable default.

UX can be difficult. Perhaps there should be an explanation and prompt
for that.

**Comment by micahflee** [comment]
I agree, trying to strip metadata or hidden identification info is a really hard (and I don't foresee solving it for all file types), and not really what OnionShare is designed for. There are also situations where you wouldn't want OnionShare to modify anything at all. I think if you want to strip metadata, it's better to just use a separate tool for that, like Metadata Anonymization Toolkit, before sending files with OnionShare.
