### ISSUE TITLE
Disabling 'stop after 1 download' and having a lot of users download the hosted file will cause the apps size to go off the screen

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#352]
Disabling 'stop after 1 download' and having around 18 or more users download the hosted file will cause the apps size to go off the screen. Here is a photo showing the issue.
![bug](https://cloud.githubusercontent.com/assets/10781882/22584553/dea8c87c-e9a7-11e6-9315-6eb2a6f8cdd6.jpeg)

**Comment by mig5** [comment]
This doesn't occur for me on the current master branch, there is a scroll bar.

**Comment by mig5** [comment]
@Baccount is this still an issue for you in latest stable release, otherwise maybe it can be closed?

**Comment by Baccount** [comment]
This can be closed, do you think onionshare sure will Support tor prop 224 by the time the stable of Tor is released On December 15?
