### ISSUE TITLE
[UX] OnionShare Server - Automatic Sharing Checkbox and Messaging

### ISSUE THREAD

**Issue by huertanix** [micahflee/onionshare#369]
_Adding [UX] to the title since there's no tag for it--I can change the title and add tag if one is created_

**Current design**

Checkbox for automatic sharing is a negation:

> Stop sharing automatically

(default unchecked)

No explanation of what automatic sharing means.

**Requested design**

In most UX schools of thought, checkboxes should indicate an “on/off” paradigm, like a light switch, so the activate state of something means it is checked, and otherwise unchecked. Apple, Microsoft HIGs I think have a similar best practice. This thread is a good read on the issue:

http://ux.stackexchange.com/questions/5748/checkbox-label-negating

Recommending change to:

> Share automatically

 (default checked)

Recommending the addition of a short explanation of what sharing automatically means. Most HIGs may recommend a short footnote under the control.

**Comment by georgeowell** [comment]
Have you seen this issue? https://github.com/micahflee/onionshare/issues/349

This is what it's currently looking like in git master:
![onion](https://cloud.githubusercontent.com/assets/18296993/24084881/0bc13410-0cea-11e7-969b-b7c2e4b3e0d0.png)

**Comment by huertanix** [comment]
@georgeowell I like the "Stop after first download" wording, makes it self-explainatory.

On the Advanced options checkbox, I also agree with you on moving it into a settings area as per #373 and in general a checkbox should not be used to toggle a display a UI element... it's not a familiar design pattern in any HIG I'm familiar with, and leaves some ambiguity on whether the checkbox is just toggling UI or changing the state of settings within Advanced Options.
