### ISSUE TITLE
Advanced Options checkbox UI should be moved to settings menu

### ISSUE THREAD

**Issue by georgeowell** [micahflee/onionshare#373]
Sorry, another one of my UI bugbears. I think we're exposing unnecessary options to the user here with the Advanced Options and Stealth Onion Service check boxes. 

The vast majority of users aren't going to understand what stealth onion services are or how to edit their tor config (and probably shouldn't risk doing that). 

Though the process is well documented [https://github.com/micahflee/onionshare/wiki/Stealth-Onion-Services](https://github.com/micahflee/onionshare/wiki/Stealth-Onion-Services), I think the average user won't even comprehend how onion services work and therefore cannot understand this attack vector. 

We should consider moving this feature to the settings menu to keep the UI clear and unambiguous.

**Comment by Outermarker** [comment]
Where did you move the Advanced Options and Stealth Onion Service checkbox? I cant't find them neither on the configuration menu nor on the interface. I'm using OnionShare2.0

**Comment by mig5** [comment]
Hi @Outermarker, sorry for the confusion.

In OnionShare 2.0, Stealth Auth is only possible with the legacy 'v2' (shorter) style .onion addresses, not with the new v3 (longer) .onion addresses.

To access Stealth Mode, you need to check the box 'Use legacy addresses'. Once you check that box, the Stealth checkbox will automatically appear, and you can check that too.

Stealth auth for v3 onions will be possible in a future release, at which point 'Stealth' will always be visible in the settings.

Hope that helps!
