### ISSUE TITLE
i2p support?

### ISSUE THREAD

**Issue by SmallerThanUsualShark** [micahflee/onionshare#377]
Maybe OnionShare can be modified to support i2p (maybe under a different program and a different name... EepShare?)

**Comment by Baccount** [comment]
The developer needs to focus on improving and getting it ready for TorProjects next generation onion service. Tor is expected to start the rollout around December 15 and the version number of the next generation onion service is 0.3.2
Tor is developing many important features.
Here is the design document for Tor 0.3.2 https://gitweb.torproject.org/torspec.git/tree/proposals/224-rend-spec-ng.txt

**Comment by micahflee** [comment]
I don't think that makes sense for this project. I've only briefly dabbled in I2P. It's not nearly as user friendly as Tor, and also has a much smaller network, so I don't want to have to add a bunch of dependencies and stuff that will likely rarely be used. OnionShare also has a lot of Tor-specific features which I think just don't apply to I2P.

However, I encourage anyone that wants to fork OnionShare and create EepShare.
