### ISSUE TITLE
cli setup onionshare

### ISSUE THREAD

**Issue by luckymedog** [micahflee/onionshare#382]
How do I setup onionshare to use system tor (-debian) via cli (no gui). 
When I type onionshare, it keeps quitting due to no tor-browser being present. I do not wish to use and/or install tor-browser, and I do not have a gui to run the gui-setup of onionshare. i.e. rpi3

**Comment by micahflee** [comment]
At the moment, OnionShare doesn't come with it's own tor process (this is changing soon! #376). The way most people use it by opening Tor Browser in the background so it can connect to its tor process. But you can use a system tor, too. Check out this page on the wiki:
https://github.com/micahflee/onionshare/wiki/Connecting-to-Tor#using-a-system-tor-in-linux

For a Raspberry Pi, you'll basically just need to install the `tor` package, then run `sudo usermod -a -G debian-tor pi`, then log out and log back in. OnionShare should just work after that, I believe.

**Comment by luckymedog** [comment]
Yes, I had already added my rpi user to debian-tor  group before I wrote the comment, because I already had system tor installed. I would like to kmow how  setup onionshare at the cli "to connect to [my] system tor's control socket file."

**Comment by micahflee** [comment]
Oh! I understand. The onionshare settings are stored in `~/.config/onionshare/onionshare.json`. The only interface to help edit that file is in onionshare-gui, but it's just json.

Put this in it:

```json
{"connection_type": "socket_file", "control_port_port": 9051, "control_port_address": "127.0.0.1", "socket_file_path": "/var/run/tor/control", "auth_type": "no_auth", "version": "1.0", "auth_password": ""}
```

If you want these settings:

![screenshot_2017-04-19_19-13-00](https://cloud.githubusercontent.com/assets/156128/25210369/4062c686-2534-11e7-8ea2-af8687b8d3d1.png)

**Comment by luckymedog** [comment]
Great, thanks. Now I just have to figure out my firewall? As I cannot access file from internet.

**Comment by luckymedog** [comment]
Great, thanks. Working well now.
