### ISSUE TITLE
Bundled Tor sometimes crashes with "dyld: Library not loaded: @executable_path/libevent-2.0.5.dylib"

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#385]
I'd like OnionShare to support macOS 10.9 and newer. However, when I try running OnionShare on a 10.9 computer using the bundle Tor setting, it fails with the error:

> [Errno 2] No such file or directory

When I manually run the `tor` binary that OnionShare ships with, it immediately crashes:

```sh
$ /Applications/OnionShare.app/Contents/MacOS/tor 
dyld: Library not loaded: @executable_path/libevent-2.0.5.dylib
  Referenced from: /Applications/OnionShare.app/Contents/MacOS/tor
  Reason: image not found
Trace/BPT trap: 5
```
However, when I run the same binary on a Mac with a newer OS, it doesn't crash (the error messages are expected since I'm not providing a special `torrc` here, and I'm running a tor service in the background):

```sh
$ /Applications/OnionShare.app/Contents/MacOS/tor 
May 17 09:30:51.831 [notice] Tor 0.3.0.6 (git-47d2e4f06ec26a79) running on Darwin with Libevent 2.0.22-stable, OpenSSL 1.0.2k and Zlib 1.2.8.
May 17 09:30:51.832 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
May 17 09:30:51.893 [notice] Configuration file "/home/debian/install/etc/tor/torrc" not present, using reasonable defaults.
May 17 09:30:51.897 [notice] Opening Socks listener on 127.0.0.1:9050
May 17 09:30:51.897 [warn] Could not bind to 127.0.0.1:9050: Address already in use. Is Tor already running?
May 17 09:30:51.897 [warn] Failed to parse/validate config: Failed to bind one of the listener ports.
May 17 09:30:51.897 [err] Reading config failed--see warnings above.
```

This is what the command line version in macOS 10.9 looks like:

```sh
$ /Applications/OnionShare.app/Contents/MacOS/onionshare --debug code/onionshare/README.md 
Onionshare 1.1.dev1 | https://onionshare.org/
[May 17 2017 09:39:27] Onion.__init__
[May 17 2017 09:39:27] Onion.connect
[May 17 2017 09:39:27] Settings.__init__
[May 17 2017 09:39:27] Settings.load
Traceback (most recent call last):
  File "site-packages/stem/socket.py", line 442, in _make_socket
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "onionshare-pyinstaller", line 30, in <module>
  File "onionshare/__init__.py", line 76, in main
  File "onionshare/onion.py", line 209, in connect
  File "site-packages/stem/control.py", line 1014, in from_socket_file
  File "site-packages/stem/socket.py", line 425, in __init__
  File "site-packages/stem/socket.py", line 243, in connect
  File "site-packages/stem/socket.py", line 445, in _make_socket
stem.SocketError: [Errno 2] No such file or directory
Failed to execute script onionshare-pyinstaller
```

So it basically just appears that the tor binary is crashing immediately, and therefore stem can't connect to the new tor socket file, because tor never actually makes it that far.

Also, I need to catch these exceptions.

**Comment by mig5** [comment]
I reproduce this issue with macOS Sierra 10.12.5 - popup immediately opening the app with [Errno 2] No such file or directory and the same exception you saw.

In addition, when I go the settings and leave the 'Use Tor that is bundled with Onionshare' option checked, and then click 'Test Tor Settings', the app crashes completely (probably the same crash)

**Comment by mig5** [comment]
Running the tor binary on 10.12.5:

```
Miguels-MacBook-Pro:~ miguel$ /Applications/OnionShare.localized/OnionShare.app/Contents/MacOS/tor
dyld: Library not loaded: @executable_path/libevent-2.0.5.dylib
  Referenced from: /Applications/OnionShare.localized/OnionShare.app/Contents/MacOS/tor
  Reason: image not found
Abort trap: 6
```

**Comment by micahflee** [comment]
I think I figured out what's wrong. I'm grabbing the pre-built tor binary from the Mac Tor Browser dmg, and I realize I was only getting `tor`, without `libevent-2.0.5.dylib`, which will cause it to break on any system where `tor` can't find this.

I just refactored `get-tor-osx.py` to copy all of the correct files from the Tor Browser app bundle into the OnionShare app bundle, including libevent.

@mig5, can you test this branch and let me know if it fixes the problem on your computer? https://github.com/micahflee/onionshare/tree/bundled-tor-error

In this new branch, to try running tor from the terminal, run:
`./dist/OnionShare.app/Contents/Resources/Tor/tor`

And also FYI, you can test OnionShare with debug output using:
`./dist/OnionShare.app/MacOS/onionshare-gui --debug`

**Comment by mig5** [comment]
@micahflee, that seems to have made progress

```
Miguels-MacBook-Pro:onionshare miguel$ ./dist/OnionShare.app/Contents/Resources/Tor/tor
May 19 08:39:28.098 [notice] Tor 0.2.9.10 (git-1f6c8eda0073f464) running on Darwin with Libevent 2.0.22-stable, OpenSSL 1.0.2k and Zlib 1.2.8.
May 19 08:39:28.099 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
May 19 08:39:28.516 [notice] Configuration file "/home/debian/install/etc/tor/torrc" not present, using reasonable defaults.
May 19 08:39:28.519 [notice] Opening Socks listener on 127.0.0.1:9050
May 19 08:39:28.000 [notice] Bootstrapped 0%: Starting
May 19 08:39:29.000 [notice] Bootstrapped 5%: Connecting to directory server
May 19 08:39:30.000 [notice] Bootstrapped 10%: Finishing handshake with directory server
May 19 08:39:31.000 [notice] Bootstrapped 15%: Establishing an encrypted directory connection
May 19 08:39:31.000 [notice] Bootstrapped 20%: Asking for networkstatus consensus
May 19 08:39:32.000 [notice] Bootstrapped 25%: Loading networkstatus consensus
May 19 08:39:37.000 [notice] I learned some more directory information, but not enough to build a circuit: We have no usable consensus.
May 19 08:39:37.000 [notice] Bootstrapped 40%: Loading authority key certs
May 19 08:39:38.000 [notice] Bootstrapped 45%: Asking for relay descriptors
May 19 08:39:38.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 0/7173, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of exit bw = 0% of path bw.)
May 19 08:39:41.000 [notice] Bootstrapped 50%: Loading relay descriptors
May 19 08:39:47.000 [notice] Bootstrapped 55%: Loading relay descriptors
May 19 08:39:47.000 [notice] Bootstrapped 62%: Loading relay descriptors
May 19 08:39:47.000 [notice] Bootstrapped 67%: Loading relay descriptors
May 19 08:39:47.000 [notice] Bootstrapped 73%: Loading relay descriptors
May 19 08:39:48.000 [notice] Bootstrapped 80%: Connecting to the Tor network
May 19 08:39:48.000 [notice] Bootstrapped 90%: Establishing a Tor circuit
May 19 08:39:51.000 [notice] Tor has successfully opened a circuit. Looks like client functionality is working.
May 19 08:39:51.000 [notice] Bootstrapped 100%: Done
```

However,starting the GUI still throws an error "Something is wrong with OnionShare connecting to Tor in the background:
[Errno 2] No such file or directory

Try adjusting how OnionShare connects to the Tor network in Settings"

```
Miguels-MacBook-Pro:onionshare miguel$ ./dist/OnionShare.app/Contents/MacOS/onionshare-gui --debug
Onionshare 1.1.dev1 | https://onionshare.org/
[May 19 2017 08:41:14] Onion.__init__
[May 19 2017 08:41:14] OnionShare.__init__
[May 19 2017 08:41:14] OnionShareGui.__init__
[May 19 2017 08:41:14] Settings.__init__
[May 19 2017 08:41:14] Settings.load
[May 19 2017 08:41:15] TorConnectionDialog.__init__
[May 19 2017 08:41:15] TorConnectionDialog.start
[May 19 2017 08:41:15] TorConnectionThread.__init__
[May 19 2017 08:41:15] TorConnectionThread.run
[May 19 2017 08:41:15] Onion.connect
[May 19 2017 08:41:15] TorConnectionThread.run: caught exception: Something is wrong with OnionShare connecting to Tor in the background:
[Errno 2] No such file or directory
[May 19 2017 08:41:15] TorConnectionDialog._error_connecting_to_tor
[May 19 2017 08:41:15] Alert.__init__
```

That error occurs whether or not I start the tor process separately.

**Comment by mig5** [comment]
Interesting - I just hacked my way into using ports instead of sockets, as well as allowing me to try using bundled Tor via dev mode. It still failed but with 'connection refused'.

After about 1 minute of doing other stuff, I decided to look at the tmp dir that contained the torrc etc. (I had done this a few times before during trial and error, and was seeing just the torrc and the cookie and state files in those tmp dirs).

But this time, I noticed I had these files like cached-microdesc-consensus, cached-microdescs.new etc. Suggesting that something had happened after the UI had dropped out with its error.

On a hunch, I wondered if your time.sleep(0.2) was just too short to obtain a connection. I raised it to 15 seconds (!) and sure enough, it connected.

Backing out my ports change, and back to sockets, I leave in the same sleep delay and it connects fine using sockets too. So nothing wrong there, it's just some sort of race condition.

A time.sleep(0.3) worked fine, as does anything longer, but 0.2 seems consistently just too short, on my Mac.

Then I rebuilt the package with time.sleep(0.3) and I got a 'no such file or directory' again. I raised it to time.sleep(1), rebuilt again, and it has been consistently happy every time since. 

It would be interesting to hear if that's the same for others, or maybe you want to play it safe and keep it a bit longer to cover corner cases of slow computers?

Hope it helps!

**Comment by micahflee** [comment]
Oh nice, good catch!

Yeah, so what's going on here is that OnionShare starts a background `tor` process, then waits a bit for it to start listening on its socket file before connecting -- it starts listening for controller connections before actually connecting to the Tor network. But apparently on some computers, it takes longer to start listening on the socket file than on others.

**Comment by micahflee** [comment]
Merged! I think this issue is probably fixed now, but before I close the bug I want to make another 1.1 dev release and ask someone else who was running into it to test it. I'll try to make that dev release in the next few days.

**Comment by micahflee** [comment]
Confirmed that it's fixed.
