### ISSUE TITLE
Onionshare 1.1 dev 1, downloading does not work with TBB 7.0 alpha 4

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#396]
When you enter the link that onionshare provides you into Tor Browser 7.0 alpha 4 and click download and then confirm the download it fails in Tor browser. This issue occurs every time.

**Comment by mig5** [comment]
It's a Tor Browser bug https://trac.torproject.org/projects/tor/ticket/21766 and nothing OnionShare specific. 

It's even mentioned in the release notes: https://blog.torproject.org/blog/tor-browser-70a4-released "the browser is crashing (with e10s enabled) or the download is stalling (with e10s disabled) when opening/downloading files that need an external application to handle them"

Verifiable that it crashes in the same way downloading any attachment from anywhere (e.g the TorBrowser 7.0 alpha4 packages themselves, from https://www.torproject.org/projects/torbrowser.html.en#downloads-alpha)
