### ISSUE TITLE
Update wiki for version 1.1

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#407]
There are many new things in version 1.1, and probably all the screenshots need to be retaken

**Comment by micahflee** [comment]
This should also include a "Developing OnionShare" section that includes info on writing tests, running tests, `./dev_scripts`, and what `--debug` does in terms of stdout and also web error logs.

**Comment by mig5** [comment]
Added an initial Development page at https://github.com/micahflee/onionshare/wiki/Developing-Onionshare

**Comment by mig5** [comment]
Created a new page 'Configuring Onionshare' at https://github.com/micahflee/onionshare/wiki/Configuring-Onionshare . I appreciate a proof read.

I could not figure out how to upload images :/

**Comment by mig5** [comment]
Also created a 'Getting Help' page but it is pretty bare: https://github.com/micahflee/onionshare/wiki/Getting-Help

Might it be worth:

1) Creating a Google Group/mailing list
2) Creating #onionshare on Freenode?
3) Creating an @Onionshare Twitter account?

Of course it comes down to how much you wish to administer.

Let me know if you want any help with the above.

**Comment by delirious-lettuce** [comment]
@mig5 ,

> Creating #onionshare on Freenode?

Any thoughts about using [Gitter](https://gitter.im/) for an `onionshare` chat? I know it's not very private but it's very easy to setup and use for GitHub repos. Also, it should be [open-source fairly soon](https://about.gitlab.com/2017/03/15/gitter-acquisition/) (for whatever that's worth!).

**Comment by micahflee** [comment]
FYI @mig5 @delirious-lettuce I just tagged `v1.1` and made a [release](https://github.com/micahflee/onionshare/releases/tag/v1.1)! I'm still working on a few final parts of the release, like getting OnionShare into the Ubuntu PPA, and finally updating the website.

Also, I just read through everything on the wiki and updated it a bunch. So now the wiki is ready for version 1.1!

And by the way, uploading images to the wiki is tricky. You can git clone `https://github.com/micahflee/onionshare.wiki.git` and make commits to it, including images, though I guess there's no simple way for either of you to actually push your changes. Instead you'll have to manually ask me (or open an issue here) and I can pull changes in from your fork.

I've thought about creating an OnionShare mailing list, IRC channel, Slack, Twitter account, etc. in the past. It's probably still a good idea... but the main thing that I worry about it actually being responsive, and answering people's questions. I tend to work on OnionShare in bursts when I have time -- so there are months-long periods where I'm just not paying attention to it, and I would hate for people to contact me through official channels and just get ignored.

But that said, it's nice that you're both volunteering so much lately. Do you think it's worthwhile to start a mailing list? Also, I just checked, https://twitter.com/onionshare redirects to https://twitter.com/account/suspended -- so I guess it's a suspended account. I can try to contact twitter to take it over. I use twitter a lot, maybe it'd be reasonable to run the OnionShare twitter account.

But anyway, now that OnionShare 1.1 has been released, I'm going to close this issue, but feel free to continue to post comments (since we don't have a mailing list yet).

**Comment by mig5** [comment]
Nice one @micahflee. I agree with you that opening up support channels means more responsibility than you might be able to afford.

Perhaps just a mailing list on its own is totally enough. E-mail, in its nature, doesn't really demand an immediate response (from reasonable people anyway!) in the same way that IRC or social media etc might. Likewise it might get responses from other people (me? @delicious-lettuce? or anyone) so it might be a good middle ground.

On the other hand as you say, if you are more likely to use Twitter than read email, maybe that's more reliable, but it does limit the 'interaction' to the person controlling the account (e.g you) unlike e-mail.

Maybe really you don't need to do anything, and wait to see if there is a demand for it. There obviously hasn't been to date (or people have opened tickets).

Congratulations on the release!
