### ISSUE TITLE
MacOS - runModalSession warning when bundled Tor connection slow to connect

### ISSUE THREAD

**Issue by mig5** [micahflee/onionshare#417]
Sometimes on a Mac, when using a self-built package (via build/install_osx.sh), I get the following warning in the Terminal when bundled Tor has taken too long to connect, and I am taken to the Settings dialog:

```
Miguels-MacBook-Pro:onionshare miguel$ ./dist/OnionShare.app/Contents/MacOS/onionshare-gui
Onionshare 1.1.dev2 | https://onionshare.org/
Connecting to the Tor network: 25% - Loading networkstatus consensus
2017-05-26 16:45:03.276 onionshare-gui[12339:294731] -[NSApplication runModalSession:]: Use of freed session detected. Do not call runModalSession: after calling endModalSesion:.
```

On at least one occasion, rather than get the Settings Dialog after the warning message, the app crashed with the subsequent message:

```
Miguels-MacBook-Pro:onionshare miguel$ ./dist/OnionShare.app/Contents/MacOS/onionshare-gui
Onionshare 1.1.dev2 | https://onionshare.org/
Connecting to the Tor network: 25% - Loading networkstatus consensus
2017-05-26 16:45:03.276 onionshare-gui[12339:294731] -[NSApplication runModalSession:]: Use of freed session detected. Do not call runModalSession: after calling endModalSesion:.
Trace/BPT trap: 5
```

Not sure how severe this is, I can't reliably reproduce the crash, but the warning regularly appears if I have a slow Tor connection (which I can force by stopping my Wifi mid-connection and then re-enabling)

**Comment by mig5** [comment]
I'm not sure this is your bug but one in Qt, so it may not really be that simple to solve (unless you want to patch Qt) https://bugreports.qt.io/browse/QTBUG-40585

**Comment by micahflee** [comment]
Hey @mig5 is this still an issue?

**Comment by mig5** [comment]
I've seen the ModalSession warning once or twice - it triggers when modal qDialog widgets appear in certain scenarios, I think - but I've never reproduced the Trap crash entirely.

I'd bet money on it being a bug in the Qt version we're using in macOS, so might go away if we upgrade like you're doing with Windows. We can probably close this as I don't think it's really 'our' bug.
