### ISSUE TITLE
Scroll bars disappear

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#431]
The scroll bar disappears after I drag 5 rtf files in the app and resize it to a smaller size.

![issue](https://cloud.githubusercontent.com/assets/10781882/26609351/803e83bc-4555-11e7-9e2b-be224ff1ee44.png)

[rtf files.zip](https://github.com/micahflee/onionshare/files/1039917/rtf.files.zip)

video showing bug. https://expirebox.com/download/4a34c768cb60f1115a7ce289e2c77248.html

**Comment by micahflee** [comment]
@Baccount can you test if #480 fixes this issue for you before I close the issue? It has been merged into master (because there's nothing wrong with setting a min height).

**Comment by mig5** [comment]
@Baccount do the scroll bars seem fine to you in current master branch (it all seems fine to me on macOS as well as on Linux)

**Comment by Baccount** [comment]
Sorry @micahflee and @mig5 I did not get the notification on your new question. The latest master seams to fix the bug.
