### ISSUE TITLE
Bundled Tor should support bridges

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#435]
If you choose bundled Tor, OnionShare connects directly to the Tor network, which means it's incompatible with users who need to use bridges to connect to the Tor network. There should be bridge options for bundled Tor.

I think looking at Tor Browser's bridge connection UI, and its torrc, would be a good place to look for how this should be done.

**Comment by micahflee** [comment]
Your analysis looks good to me. I didn't realize meek was so expensive! I agree, OnionShare should support vanilla bridges and also `obfs4` pluggable transports.

**Comment by Baccount** [comment]
It may be possible to integrate snowflake bridges, Currently they are only supported on the alpha tor browser on macOS , I'm not sure about Linux.
 https://trac.torproject.org/projects/tor/ticket/19001

**Comment by micahflee** [comment]
This feature is now merged with #496. If we want to extend support for different pluggable transports, let's open separate issues for those.
