### ISSUE TITLE
Flask version check is incorrect

### ISSUE THREAD

**Issue by davidism** [micahflee/onionshare#442]
`StrictVersion` is not PEP 440 compliant, and fails with our dev tags (`'0.13-dev'`). Arch's onionshare package allows python-flask-git as the flask dep, which has a `-dev` tagged version string.

Use `pkg_resources.parse_version`, which is what pip uses.

~~~python
import flask
import pkg_resources
pkg_resources.parse_version(flask.__version__)

# or by resolving the distribution
pkg_resources.get_distribution('flask').version
~~~

Or if you don't want to depend on setuptools, use `distutils.version.LooseVersion`, which is less correct but still works.

**Comment by georgeowell** [comment]
This is still causing Onionshare AUR package to fail to build.

https://github.com/pallets/flask/issues/2355
https://bugs.archlinux.org/task/54288

Seems it is an Arch upstream issue. Not sure if there is a way we can bump this up their priority list. Quite frustrating.

**Comment by davidism** [comment]
The quick fix is installing `python-flask` instead, which was repackaged with a correct version in Arch recently. It doesn't really make sense to install `python-flask-git` system-wide. But this should still be fixed anyway.

**Comment by georgeowell** [comment]
This still hasn't been fixed or at least it's not building for me even with `python-flask` install.

**Comment by lothar-mar** [comment]
For me neither. Is there any other way to fix this? Also using arch...

**Comment by livmackintosh** [comment]
You can find a patched PKGBUILD over at https://github.com/livmackintosh/onionshare-pkgbuild . More of a quick fix but will make a prospective PR shortly.

**Comment by georgeowell** [comment]
This pull requests will fix this issue for now:
https://github.com/micahflee/onionshare/pull/465

Tested and working with this PKGBUILD:
https://github.com/livmackintosh/onionshare-pkgbuild/blob/master/PKGBUILD
