### ISSUE TITLE
launch error OnionShare - 1.1

### ISSUE THREAD

**Issue by donpdw** [micahflee/onionshare#445]
launch error OnionShare - 1.1
winXP sp3
onionshare-gui.exe - Entry Point Not Found
The procedure entry point GetFinalPathByHandleW could not be located in the dynamic link library KERNEL32.dll.

**Comment by micahflee** [comment]
OnionShare doesn't support Windows XP.

(And [neither does Microsoft](https://www.microsoft.com/en-us/windowsforbusiness/end-of-xp-support), for over 3 years now -- you really should stop using it.)
