### ISSUE TITLE
 Cancel Tor bootstrap bug

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#447]
When you cancel the tor bootstrap and click open settings then click cancel, the app will allow you to add file and start sharing. but nothing will happen. Here is a video showing the issue.
https://filenurse.com/download/2b2e90d78a8dc2cf2e49c8361bac5f6d.html

**Comment by mig5** [comment]
@micahflee I am happy to work on this (seems quite clear in the code how to react to both events being canceled) but what do you think should happen instead? 

Should we try and:

1) force reboot the Tor connection, or 
2) just disable the add/remove buttons until the matter is dealt with (user opens settings again), or 
3) quit the app entirely?
