### ISSUE TITLE
Windows version hangs when the local disk gets full during crunch

### ISSUE THREAD

**Issue by ralfmuschall** [micahflee/onionshare#453]
Version 1.1 for Windows, downloaded 2017-06-26

If the disk fils up during (and because of) the "crunching files" step, the program simply stops progressing. Even if one frees diskspace from another window (e.g. using cmd or explorer), the program does not continue. An error message should be displayed instead.

**Comment by micahflee** [comment]
This is quite the edge case, but still a good exception to catch.
