### ISSUE TITLE
Unable to Install Onionshare

### ISSUE THREAD

**Issue by ravirajbasis** [micahflee/onionshare#464]
Hi

I am trying to install Onionshare on RHEL Workstation 7.4, on an x86_64. I get message installing not available when i try to install via Application Installer. 

What to do?

Thanks
Ravi

**Comment by amuuza** [comment]
Hi,

Same here. I cannot install it.

```
me@mycomputer:~$ sudo apt-get install onionshare
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package onionshare
me@mycomputer:~$
```

**Comment by Baccount** [comment]
@amuuza 
For Linux, build from source. https://github.com/micahflee/onionshare/blob/master/BUILD.md

**Comment by freddymartinez9** [comment]
@amuuza That are the Ubuntu install instructions, you need to follow the instructions for Fedora-like installer (RedHat uses `.rpm` and `yum`, you are using the `.deb` and `apt` instructions)

**Comment by micahflee** [comment]
Also, onionshare is packaged for Fedora: https://src.fedoraproject.org/rpms/onionshare

I'm not sure if RHEL uses the same repositories as Fedora, but you might be able to `sudo dnf install onionshare`.
