### ISSUE TITLE
After download is canceled the progress bar is not canceled

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#468]
1. Add a large file “500Mb” and start sharing, after the hidden service is created copy the onion link and paste it into TorBrowser.
2. Click the download button on the onion website.
3. When the download starts "click download file" in TorBrowser.
4. Choose to save the file to downloads "or into any directory".
5 .After you save it, the file should still be downloading, click the “stop sharing button and the progress bar still says the ETA and other info”

**Comment by micahflee** [comment]
Resolved
