### ISSUE TITLE
Support self-signed HTTPS

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#479]
As mentioned in #450:

> Each time you start the server, OnionShare could generate a new key and self-signed certificate, and use a strong ciphersuite. The only problem is that it will throw a certificate warning that the user must click through, which is why I haven't implemented this in the past already. Although, I'd be into including HTTPS as a setting that's disabled by default. I'd use it.

I think this would be a good disabled-by-default feature, which can be enabled in the settings.

It will involve generating TLS keys, and doing TLS termination with strong ciphersuites, directly in python. This is well documented using web servers like nginx or apache2, but I definitely don't want to add a full web server as a dependency.

**Comment by Baccount** [comment]
Would a self signed certificate be necessary with the next generation onion service largely improved crypto, I think it would just be more complicated for the end-user.
```
1.Better crypto (replaced SHA1/DH/RSA1024 with SHA3/ed25519/curve25519)
2.Improved directory protocol, leaking much less information to directory servers.
```
https://trac.torproject.org/projects/tor/wiki/doc/NextGenOnions#Howtoconnecttothetesthubfornextgenonionservices

**Comment by micahflee** [comment]
This is a good point. With better crypto coming soon, it seems like there will be no advantage to adding a layer of HTTPS.
