### ISSUE TITLE
The files on the download page should be sorted by size

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#491]
The files on the download page should be sorted by size, where the larger files will be onto and the smallest files at the bottom of the list.
<img width="1000" alt="issue" src="https://user-images.githubusercontent.com/10781882/33747381-8ba478d4-db77-11e7-84b4-f0fdb804e6ba.png">

**Comment by mig5** [comment]
Personally I prefer the alphabetical order (since the FileList UI in the app is also alphabetical). 

Why does it need to be in order of size?

The table could be made sortable, but that might mean requiring JavaScript on the page (which many Tor Browsers might block)

**Comment by Baccount** [comment]
Would it be possible to sort the files from within the OnionShare GUI and they would show up in that order on the onion webpage? Possibly something similar to the sort options shown in the photo of macOS finder.
<img width="633" alt="options" src="https://user-images.githubusercontent.com/10781882/33799207-1e5ecaa2-dcdc-11e7-8942-4d86b28e865c.png">

**Comment by mig5** [comment]
If you were to mess about with sorting, you run the risk of re-introducing bugs like #428 (which you reported, and was fixed in #447). Also seems odd UX to force the receiving user to accept the sorting that was chosen by the sender.

I'll pipe down and let @micahflee decide :)
