### ISSUE TITLE
Host https://onionshare.org/ on a V3 Onion service

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#507]
Host https://onionshare.org/ on a V3 Onion service, Torproject **did** release 0.3.2 final and your website should host a V3 onion service to protect users from know attacks on the V2 onion services.
https://trac.torproject.org/projects/tor/wiki/doc/NextGenOnions#Howtosetupyourownprop224service
_Just add_
```
HiddenServiceDir /home/user/tmp/hsv3
HiddenServiceVersion 3
HiddenServicePort 2222 127.0.0.1:2222
```
_To your hidden service torrc and restart the Tor service._ "after you updated Tor to 0.3.2.x +.

**Comment by micahflee** [comment]
Done! http://lldan5gahapx5k7iafb3s4ikijc4ni7gx5iywdflkba5y2ezyg6sjgyd.onion/

**Comment by Baccount** [comment]
Thank you @micahflee !
