### ISSUE TITLE
I have had the error "Connecting to Tor is taking too long." when using the bundled Tor 

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#508]
I have had the error "Connecting to Tor is taking too long." multiple times when using the bundled Tor.
I opened a bug report on [Trac ](https://trac.torproject.org/projects/tor/ticket/24511#comment:16) that is related to the long bootstrap times and teor said.

["This is normal behaviour. Our target bootstrap time is under 30 seconds, but the network is a bit overloaded right now."](https://trac.torproject.org/projects/tor/ticket/24511#comment:14)

Increasing the timeout should fix the issue. 
https://github.com/micahflee/onionshare/commit/022bc57b353de4956c1e7db352955cb00f702ed2

**Comment by leonardoporpora** [comment]
I have got the same problem.

**Comment by Baccount** [comment]
#leonardoporpora  In the meantime change Onionshare setting `Attempt to automatically configure with TorBrowser` and make sure Torbrowser is open when onionshare is open.

**Comment by Baccount** [comment]
https://github.com/micahflee/onionshare/pull/517/commits/c324cd55da7d40008039462f2a77dfb93776bb0b
