### ISSUE TITLE
Click the link "More information" in settings does not do anything

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#520]
Click the link "More information" in settings does not do anything.
https://github.com/micahflee/onionshare/blob/5c390f1bd99a756682801375cc8c0a1418060f65/onionshare_gui/settings_dialog.py#L81
<img width="684" alt="bug" src="https://user-images.githubusercontent.com/10781882/34375695-9ee37cb8-ea9c-11e7-99af-ca3d40efc36b.png">
Tested on macOS 10.13.2 (17C88)

**Comment by mig5** [comment]
Line 519/520 is actually for the 'Help' button in the bottom left corner of your screenshot. That one still works for me, but the 'More Information' link indeed doesn't do anything for me even on MacOS 10.12.6.

Does the Help button work for you, @Baccount?

If so it looks like hyperlinks in the QLabel widget doesn't do anything in newer version of macOS, which is unfortunate, but might be a Qt bug not OnionShare... looking into it.

**Comment by Baccount** [comment]
Yes you are correct, I was looking at the code for the help button.

**Comment by mig5** [comment]
I have a fix, I will push a branch shortly

**Comment by micahflee** [comment]
I can confirm that Linux has the same issue.
