### ISSUE TITLE
TypeError on start_server_finished

### ISSUE THREAD

**Issue by mig5** [micahflee/onionshare#525]
Somehow I triggered this after clicking Start Sharing - right at the moment where you'd expect the share to become ready after the usual momentary delay e.g the Onion Service finishing its negotiation:

```
Onionshare 1.1 | https://onionshare.org/
Connecting to the Tor network: 100% - Done
Configuring onion service on port 17606.
Starting ephemeral Tor onion service and awaiting publication
Traceback (most recent call last):
  File "/home/user/onionshare/onionshare_gui/server_status.py", line 214, in start_server_finished
    self.copy_url()
  File "/home/user/onionshare/onionshare_gui/server_status.py", line 237, in copy_url
    url = 'http://{0:s}/{1:s}'.format(self.app.onion_host, self.web.slug)
TypeError: unsupported format string passed to NoneType.__format__
Aborted (core dumped)
```

I haven't been able to reproduce. Obviously my Tor connection was working in order to even start the share, but it seems like somehow the Onion Service failed to obtain somehow.

I don't know how to reliably reproduce, but wondering if we just need to wrap self.app.onion_host and self.web.slug in some conditionals there to make sure they are valid and if not, fail the share gracefully?

An unrelated note, it seems that start_server_finished is emitted in start_server_step2 but should maybe be done in start_server_step3, don't think that was the cause though.

**Comment by mig5** [comment]
So somehow, parsing a service_id out of the Stem Controller response must've failed:

```
self.service_id = res.content()[0][2].split('=')[1]
```

(not sure why we do all that splitting since I think you can get it straight from res.service_id because Stem API sends that attribute back explicitly)

In any case, the start_onion_service function simply returns the onion_host back, but if that's not a valid string, this isn't really 'caught' by anything, so I wrap it in a try/catch with TorProtocolError exception, which means that the GUI will flag that as an error, display an appropriate Alert and stop server.

I think it's a pretty rare error, but it's conceivable that some underlying Tor infrastructure/network issue might mean that the res object might not return the expected data, so good to catch.

**Comment by micahflee** [comment]
`res.service_id` might not have been available when I first implemented this, but more likely I just didn't realize it existed. In any case, `res.service_id` is better. I will make that change.
