### ISSUE TITLE
When I start a share, one of the 2 Onionshare processes becomes unresponsive

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#533]
When I start a share, one of the 2 Onionshare processes becomes unresponsive in Activity monitor. I captured a photo and a spindump of the process that is hanging.
[photo and spindump.zip](https://github.com/micahflee/onionshare/files/1630067/photo.and.spindump.zip)
1. Start onion share and add any file to share, start the share.
2. Open activity monitor and search for Onionshare and  you should see that one of the processes will hang non stop.
3. As long as the share is occurring the process will hang.
And here is a sample of the frozen process.
[Sample of OnionShare.txt](https://github.com/micahflee/onionshare/files/1630074/Sample.of.OnionShare.txt)

**Comment by mig5** [comment]
I bet you this is related to #451 e.g just a quirk of pyinstaller being the 'main' process and it executes onionshare-gui as a subprocess

Just my theory

https://github.com/pyinstaller/pyinstaller/issues/2616

**Comment by Baccount** [comment]
If I install the latest dev build of pyinstaller 
`pip install https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz` then build onionshare with `install/build_osx.sh`there is only one process and it does not become unresponsive when sharing.

**Comment by mig5** [comment]
@Baccount would you like to make a PR that uses a newer version of pyinstaller in the install scripts?

I think the files in question are install/requirements.txt and install/requirements-windows.txt where the Pyinstaller version is set.

Which version did you use?

**Comment by Baccount** [comment]
I will make a PR.

**Comment by micahflee** [comment]
@Baccount did #540 resolve this for you?

**Comment by Baccount** [comment]
Yes, both #451 and #533 are fixed. Thank you
