### ISSUE TITLE
Drop support for macOS 10.9, bump to something newer

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#554]
When I build OnionShare releases for Mac, I must use a build machine running the earliest version of macOS we'd like to support. At the moment, my build machine is running macOS 10.9.5, which means anyone running that version of macOS or later will be able to run the pre-built binary.

In OnionShare 1.2, we bumped the version of Qt5 from 5.7.1 to 5.10.0. I just discovered that the latest Qt5 installer requires 10.10 or later.

According to wikipedia:

- Apple dropped support for macOS 10.9 in September 2016
- Apple dropped support for macOS 10.10 in September 2017

macOS 10.11 is still supported. Should the oldest version of macOS that OnionShare supports get bumped to 10.10, or should we jump straight to 10.11 and follow Apple's lead on what OS to support?

**Comment by mig5** [comment]
I think we should support the minimum level still supported by the OS - in the same way you don't package for Ubuntu 12.04 or Debian Squeeze (5) for example

You can't package on (say) macOS 10.13.2 and have the package work on 10.11 ?

**Comment by micahflee** [comment]
Yeah I think I agree. Same with Microsoft -- we shouldn't waste any time supporting Windows XP, for example. I'm going to bump it to 10.11.

Unfortunately this seems to be an issue with PyInstaller for Mac. Whatever version of OSX you build on is the earliest version the binary will run on. PyInstaller for Windows doesn't have this problem -- binaries build in Windows 10 work fine in Windows 8.

FYI I've signed the v1.2 release tag. Right now I'm upgrading my Mac build machine to 10.11, and the release will hopefully be done pretty soon!

**Comment by mig5** [comment]
This might also mean you can post the SHA-256 per #452 (perhaps alongside the packages and their SHA256SUMs if you intend on putting 1.2 packages on the onionshare.org website as per #523 )

**Comment by Baccount** [comment]
@mig5 #555 should replace the need for a Sha-256 hash on the V3 onion site.
