### ISSUE TITLE
[Feature request] Add start sharing timer

### ISSUE THREAD

**Issue by maqp** [micahflee/onionshare#571]
I really like the new feature that kills sharing at certain time as well as persistent URLs. If OnionShare could also start sharing data at specific time under static URL announced beforehand, it could be used as a dead man's switch for releasing documents.

**Comment by mig5** [comment]
This should be do-able, I’ll work on it. Maybe we can group the auto-start and auto-stop timers under a ‘use timers?’ checkbox so as not to clutter the UI too much, which is my main/only concern.

**Comment by mig5** [comment]
I've made an implementation in #572. If you are in a position to test it, please try and build against this branch and let me know how it goes!

**Comment by mig5** [comment]
@maqp in case you were interested, a new implementation ready for testing in #934, which shows the onion address/slug 'early' as desired \o/

**Comment by maqp** [comment]
@mig5 I'm more than excited about this! I'll get to this as soon as I have cleared my schedule.
