### ISSUE TITLE
Protect against guard discovery attacks, Vanguards

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#574]
Pin the middle node to protect against guard discovery attacks. Tor 0.3.3 supports this feature.

```
You can use it by adding a line like this in your torrc:
"""
HSRendezvousMiddleNodes TorLand1
"""
```
https://lists.torproject.org/pipermail/tor-dev/2014-November/007730.html

## Major features (onion services):
Provide torrc options to pin the second and third hops of onion service circuits to a list of nodes.                                 The option HSLayer2Guards pins the second hop, and the option HSLayer3Guards pins the third hop. These options are for use **in conjunction with experiments with "vanguards"** for preventing guard enumeration attacks. Closes ticket [13837](https://trac.torproject.org/projects/tor/ticket/13837).

**Comment by mig5** [comment]
I wouldn't want to hardcode any relays into the torrc template, sice *every* OnionShare user would therefore have the same relay pinned? Or have I misunderstood?

**Comment by Baccount** [comment]
Maybe giving the user the ability to choose their own node as the pinned not could be a solution, onionshare does need to protect against car discovery attacks and it looks like this would be a temporary solution while Torproject works on a proper solution.

inspired by the recent discussions on guard discovery, I went ahead
and implemented a small patch for Tor that tries to help defend
against Hidden Service guard discovery attacks.

```
It basically allows the operator to specify a set of nodes that will
be pinned as middle nodes in Hidden Service rendezvous circuits. The
option only affects HS rendezvous circuits and nothing else.

Of course, it doesn't fix guard discovery, it just pushes guard
discovery to the next hop, so that they need to compromise two boxes
to win.

```

**Comment by mig5** [comment]
I think it would be a bad idea to start adding setting options for various torrc options - Onionshare shouldn't become a GUI for the torrc to satisfy various whims. The more 'features' we add, actually is detrimental to the usefulness of the app as it will become overwhelming even to look at the myriad of options available.

But maybe there's a more general idea to allow 'including' a custom torrc that doesn't break the existing bare torrc requirements for Onionshare. Perhaps a (documented) command-line flag for such an '```--extra-torrc-config <file>```' option so regular users don't even see it.

**Comment by Baccount** [comment]
I agree that a  [command line flag](https://oniongit.eu/mikeperry/tor/blob/bug13837-mergeready/doc/tor.1.txt#L1541) may be the best option. 
Vanguard should also help slow this attack. Here's the source code for vanguards.
https://github.com/mikeperry-tor/vanguards

**Comment by leonardoporpora** [comment]
What about see which protection uses Tails to tackle this problem than maybe we could implement that algorithm? Am I wrong?

**Comment by Baccount** [comment]
Vangards are only used for onion servers. @leonardoporpora

**Comment by leonardoporpora** [comment]
![537febd4-73c9-410a-a164-9d525ce46cbc](https://user-images.githubusercontent.com/34192761/36248605-5fb1cfd6-1238-11e8-8547-25cfb031caed.jpeg)
This is what is written in the link you sent above.  There is written tor client and/or tor onion service

**Comment by Baccount** [comment]
@leonardoporpora Onionsahre only host onion services, the client is the other users using TorBrowser to connect to the onion service that Onionshare hosts. So onionshare is only concerned about hosting Onion services.

**Comment by mig5** [comment]
Good new reading: https://blog.torproject.org/announcing-vanguards-add-onion-services
