### ISSUE TITLE
local variable 'prefix' isn't defined

### ISSUE THREAD

**Issue by yurivict** [micahflee/onionshare#576]
It should print something more meaningful instead of this:

```
Traceback (most recent call last):
  File "/usr/local/bin/onionshare", line 22, in <module>
    onionshare.main()
  File "/usr/local/lib/python3.6/site-packages/onionshare/__init__.py", line 33, in main
    strings.load_strings(common)
  File "/usr/local/lib/python3.6/site-packages/onionshare/strings.py", line 35, in load_strings
    locale_dir = common.get_resource_path('locale')
  File "/usr/local/lib/python3.6/site-packages/onionshare/common.py", line 88, in get_resource_path
    return os.path.join(prefix, filename)
UnboundLocalError: local variable 'prefix' referenced before assignment
```

Yes, p was equal to 'FreeBSD' and not 'Linux', but it should't use the uninitialized 'prefix' variable anyway.

**Comment by mig5** [comment]
None of the developers are using FreeBSD to my knowledge so am not too surprised these bugs have slipped into 1.2, we've relied on community patches from BSD users

@yurivict, do you know what would be the correct path to the resources found in the 'share' folder of onionshare? (Where files such as 'wordlist.txt' and 'version.txt' are located). 

It looks like your CLI files for Onionshare are at /usr/local/lib/python3.6/site-packages/onionshare/ but the 'share' dir would be one level up from that, and I don't believe they'd be in /usr/local/lib/python3.6/site-packages/..

**Comment by yurivict** [comment]
> do you know what would be the correct path to the resources found in the 'share' folder

The correct location is the same as on Linux. I patched it in the port. It would be great if you do this in your repo.

I was mostly concerned with this code using a variable that could be obviously uninitialized.

**Comment by mig5** [comment]
@yurivict are you able to create a PR here? as we would happily merge your fix if you've solved it in your port.

In this specific case, it's just that the variable prefix is defined per OS but there was no case for BSD. But you're right, we should at least set it to a default first just in case.

**Comment by mig5** [comment]
This was fixed via https://github.com/micahflee/onionshare/pull/585
