### ISSUE TITLE
Error message not saying anything. It only displays the text "2".

### ISSUE THREAD

**Issue by yurivict** [micahflee/onionshare#577]
![image](https://user-images.githubusercontent.com/271906/35533033-1ad8d37c-04f1-11e8-986e-369d689f8ca3.png)

**Comment by mig5** [comment]
This error indicates that Tor could not start - usually this is due to a syntax error with the torrc that is generated. So maybe we need a torrc that is somehow BSD friendly.

Is your Tor located at /usr/local/bin/tor and your geoip files in /usr/local/share/tor ?

You could look at using the 'attempt automatic configuration with Tor Browser' method (via the Settings Dialog), if you have Tor Browser installed and running, until we resolve whatever causes this issue on BSD.

**Comment by yurivict** [comment]
> Tor could not start

What does it mean? Tor already runs.

**Comment by mig5** [comment]
OnionShare creates a custom torrc config [from a template](https://github.com/micahflee/onionshare/blob/master/share/torrc_template) each time you connect with the 'bundled tor' method. 

Previous patches we received from the BSD community, hardcode the location of Tor to be at /usr/local/bin/tor and some auxiliary files in /usr/local/share/tor, so we assume that's correct for all FreeBSD users (that's my question - is that definitely the case? Where is your Tor binary located on your filesystem?)

If the path to the Tor binary is not found at that location, or there is some other setting in torrc based on our template that FreeBSD doesn't like, then that might be why you get the error above.

**Comment by yurivict** [comment]
> Previous patches we received from the BSD community, hardcode the location of Tor to be at /usr/local/bin/tor and some auxiliary files in /usr/local/share/tor, so we assume that's correct for all FreeBSD users 

This can't be true in all cases. In general, path can change depending on system settings. IN most cases, /usr/local/bin/tor should be good.

> I assume you are using the 'Bundled Tor' method in the settings.

I didn't touch settings. When I ran it the first time, it popped this error message.

**Comment by yurivict** [comment]
You should default to pre-existing Tor instance when stem succeeds, and to custom instance when stem isn't successful.

Then, you should derive Tor executable path from your stating path. Tor executable should be in the same directory that onionshare executable is run from.

The reason being that 99.9% of FreeBSD users run both using ports, and ports system always places them into the same location. Standard location is /usr/local/bin/. Only people who choose to install things manually will have different paths. (There is no benefit in not using ports, whatsoever, but people still do this.)

**Comment by mig5** [comment]
We do default to a pre-existing Tor instance - on Linux and BSD it expects to find a system-installed Tor, and if not found, the user is taken to the SettingsDialog to configure an alternative method (e.g connect via control or socket ports, or via a running Tor Browser). I don't think we'll change that for BSD.

I'm going to hazard a guess that the cause of the '2' here was a side-effect of not finding the Tor binary or some issue with that Tor binary not understanding the torrc that OnionShare generates.

I just tested #585 on FreeBSD with a 'pkg install tor'-installed Tor and I didn't experience the issue at all, so I think it's somehow fixed..
