### ISSUE TITLE
The status bar should be cleared when a share is stopped

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#598]
After a user stops a share by clicking the Stop sharing button the status bar should be cleared. Sometimes status messages like `Download page loaded ` are left after I click the stop sharing button. Tested with the ux-update branch

**Comment by mig5** [comment]
Pretty much that message is the only one that should be temporary or cleared. Most others need to stay to provide important feedback to the user as to why the share stopped (as recently discussed in #592)

**Comment by mig5** [comment]
Although maybe there is a way to clear all of it was the *user* clicking stop, indeed. Will try and factor this in with the #592 work.
