### ISSUE TITLE
Add password to web page

### ISSUE THREAD

**Issue by leonardoporpora** [micahflee/onionshare#611]
Why don’t you make possible to add a password on the .onion of the download page?

**Comment by Baccount** [comment]
Currently OnionShare requires the slugs to be correct and if they're not correct after 20 try's then it will cancel the share.
When V3 onions are supported It should not be possible to discover the onion address. Here's the explanation why.

```
2.5.1. First layer of encryption [HS-DESC-FIRST-LAYER]
The first layer of HS descriptor encryption is designed to protect
descriptor confidentiality against entities who don't know the blinded
public key of the hidden service.
```
Here is the design document for Tor's next generation onion service.
https://gitweb.torproject.org/torspec.git/tree/proposals/224-rend-spec-ng.txt

**Comment by leonardoporpora** [comment]
Perfect 👌
