### ISSUE TITLE
Onionshare Debian Stretch

### ISSUE THREAD

**Issue by HulaHoopWhonix** [micahflee/onionshare#613]
Hi @micahflee. Do you know why Debian stretch doesn't include onionshare? It should be readily supported as you guys' wiki says and its available for Buster and Jessie but I'm not seeing it in stretch :(

**Comment by mig5** [comment]
@u451f I believe is one of the Onionshare maintainers for Debian, maybe you know why this is?

**Comment by u451f** [comment]
Oh and Stretch does not automatically include Onionshare - you will need to install from testing or from stretch-backports.

**Comment by micahflee** [comment]
Thanks @u451f !
