### ISSUE TITLE
Simultaneous downloads is failing for the second download

### ISSUE THREAD

**Issue by mig5** [micahflee/onionshare#614]
With 'close automatically after first download' turned off, there is a bug affecting simultaneous downloads.

While running two downloads at once of the same share - one slightly ahead of the other - once the first one completes, the progress bar of the second download in the OnionShare GUI 'freezes' e.g at 88%.

In the Downloads tab of my browser, the second download continues for a little way (due to the discrepancy between progress sent to Tor and what's come out the other side, as usual), but the download suddenly 'completes' (but really cancels: the file size, in this case 9.9MB, is only 8.5MB, and the zip is 'corrupt', so the download is only partial).

Whilst watching the progress bars of both downloads, in the browser, it seems as though once the first download gets 100% of the file client-side, that's around when the other download fails too - as if its stream is closed when the first one is complete. It happens that way for me every time.

It happens if I am downloading the share twice in the same Whonix browser, but also if I am downloading the share via Whonix on Qubes, and Tor Browser on Mac, at the same time (the Mac download completed only partially in the same way). So it's not unique to using the same Tor connection client-side.

I verified the bug occurs in the develop branch as well as ux-update, so it predates the UX work. It also looks like it's present in the 1.2 release.

It occurs regardless of Tor connection method or whether I'm running OnionShare on Linux or Mac.

My guess is there's some sort of weird collision at the Flask layer when handling simultaneous downloads, but I don't know how best to debug..

**Comment by micahflee** [comment]
Good find!
