### ISSUE TITLE
Move downloads progress into download info widget

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#632]
As @mig5 referenced in #629, it would be good to move the download progress out of the main window where it takes up a ton of space, and somewhere nice, probably the download info widget. Or maybe even the systray applet?

**Comment by mig5** [comment]
One idea I had was to somehow write a toolTip for the info widget that writes the progress of the downloads, but appends with a <br> separator for where there are simultaneous downloads in progress. 

The tricky part would be removing a completed download's progress bar from the tooltip.

**Comment by mig5** [comment]
See an implementation of this at #651
