### ISSUE TITLE
Should not revert to connecting to Tor directly when bridge syntax is invalid

### ISSUE THREAD

**Issue by irykoon** [micahflee/onionshare#634]
According to the onionshare wiki: https://github.com/micahflee/onionshare/wiki/Using-Bridges

> Invalid bridge syntax
> 
> If you supply bridges in an invalid format, they will simply be ignored. If none of your bridges are valid, OnionShare will alert you about this, and revert to connecting to Tor directly.

"[R]evert[ing] to connecting to Tor directly" can be dangerous especially considering most of the people who use a custom bridge because they may want to hide the fact that they are using Tor.

Therefore, do you think it is a good idea to:
1. inform the user which bridge's syntax is invalid
2. do not auto connecting to the Tor network until user fixes the syntax error or explicitly choose to connect to the Tor network without a bridge?

**Comment by micahflee** [comment]
I agree this is a good idea.
