### ISSUE TITLE
When I start a share, onionshare becomes unresponsive

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#637]
When I start a share, onionshare becomes unresponsive, When I run it in --debug it gets stuck at
`[Feb 24 2018 14:41:39] Onion.Starting a hidden service with a new private key`
I captured a sample of the frozen process.
I have onionshare set to connect to TorBrowser and "Stop after first share" disabled
[Sample of OnionShare.txt](https://github.com/micahflee/onionshare/files/1755396/Sample.of.OnionShare.txt)

**I built and tested with the latest develop build**

**Update.**
I captured a full log when the app became unresponsive.

[full log.txt](https://github.com/micahflee/onionshare/files/1755404/full.log.txt)
@micahflee 
@mig5

**Comment by mig5** [comment]
Hmm, I can't reproduce this... but I will keep trying to.

**Comment by mig5** [comment]
Does it happen every time @Baccount ?

**Comment by Baccount** [comment]
This does not happen every time, when it does happen I have to force quit the app.

**Comment by Baccount** [comment]
I attached a full log that shows all the steps I took to cause a freeze.
https://github.com/micahflee/onionshare/files/1755404/full.log.txt

**Comment by mig5** [comment]
If I understand that log correctly, it looks like you canceled the first share? So does the freeze happen each time you cancel a share and then try to start a new one?

I already suspected from the Sample file that this is maybe related to the queue/thread introduced by 'cancel share' feature, but am not sure..

**Comment by mig5** [comment]
I just reproduced it after canceling a share and trying to start a new one. So it does look like the new Qthread in the 'cancel share' feature has something to do with this @micahflee :( might have to revert that feature.

39954c6ee8435c1762a2679b1325e66be248bebd
9da3e2d8b019ce0429fd5d3b98552b9815e16a6f

**Comment by mig5** [comment]
@Baccount please try and build #640 and let us know if the issue seems to consistently go away.

Unfortunately I don't know of a fix, it hasn't occurred in Linux for me.

Thanks for finding this prior to us releasing 1.3.
