### ISSUE TITLE
[Windows] info widget icons and URL description {i} are wrong/missing

### ISSUE THREAD

**Issue by mig5** [micahflee/onionshare#641]
On Windows, the download icons in the Info widget (top of screen) as well as the 'information' icon on the URL description ('This share will not stop automatically', etc) show an incorrect icon.

I made sure they were added to the .nsi so I don't know why this is. One common trait other than those being 'new' images is that each of those widgets has a tooltip, so maybe it's tooltip related.

**Comment by micahflee** [comment]
I'm debugging this now. FYI the `.nsi` is only for the installer/uninstaller (which we'll need to test before making the release), but if you're running from `dev_scripts` it's not even used. So the problem must be somewhere else.
