### ISSUE TITLE
Where there are multiple files in a share, ability to download each individually.

### ISSUE THREAD

**Issue by ghostlands** [micahflee/onionshare#653]
Currently (1.3) they all get compressed into a single archive to download. It would be nice to allow the receiver to choose, especially in cases where the collective size of the share ends up being large.

Only one file being available to download at a time would be acceptable, if for whatever reason that made implementation easier. The main aim is to allow the downloader to have a choice and to avoid huge archive sizes.

The finished work on 1.2 and 1.3 is just beautiful, by the way.

**Comment by ghostlands** [comment]
Ah, crap. Duplicate of #597.

My wording is clearer though ;)

Also probably reliant on  #582.

**Comment by mig5** [comment]
I'll close this as a duplicate. FYI at the moment we're seeing this as a #wontfix unfortunately because there is no real sane way to implement (and for the same reason #582 is the same - adding a route for every single file would be crazy, and if there are say, 20,000 files, navigating that in a browser would have its own problems), but we can have more discussion in the other ticket, I think Micah is going to weigh in on it soon.

Thanks for the feedback!

**Comment by ghostlands** [comment]
No problem. I'll bet that at some point a workaround/"not quite as good but almost"/approximation will be workable.

To clarify for me, limiting access to one file at at time wouldn't be helpful towards this?

**Comment by mig5** [comment]
Not really. The fundamental issue here is not the act of downloading the files simultaneously, but that we are only sharing one file via Flask, a zip file. The list you see in the web interface is nothing more than an array of file names taken from the list in the OnionShare client..

To support downloading individual files, we'd have to (I think) add routes for each individual file in Flask (a Python web server). That means we'd also need to allow access to those files somewhere (either in their original location on-disk, or copied to some temporary area, which might have implications for disk usage on the sender's side). I see potential problems for both.

Currently we just add all the proposed files into a zip file and share that single file, which is about 1000x simpler from a code point of view, and less problematic both in terms of disk/security issues as it's adding just one file to the filesystem in /tmp and it's compressed.

In any case, maybe there's an easier way than I can think of to do this, which can be discussed in the other ticket, but the issue of 'one file at a time' is ironically not really part of the problem.

**Comment by ghostlands** [comment]
@mig5, @micahflee,

I want to bump this (or at least ping it even though it's closed) since some progress has been made in #663 via #774.

In addition to the original purpose of this bug (implementing one onion url for the receiver with multiple individual file links), I'm finding that the storage requirements for keeping a compressed file somewhere are dissuasive for using OnionShare in most of the applications I'd use it for. The sending user must have at least twice the equivalent in space of the file(s) that need(s) to be sent (at least during compression), and in some of my environments that simply isn't possible. So really this should be about #774, but since I'm hoping it can be in service to individual file downloads from one page, I'm adding it here in 653.

What I wish could happen is some function similar to a feature of an old project I just discovered called FileTea:

https://github.com/search?q=filetea

...that being a lack of necessity to pre-transfer or repackage the files being offered as links. FileTea acts more as an intermediary between disk locations and clients seeking to access files.

FileTea also lacks the ability to offer individual links via one page, so it isn't a panacea, and again I do understand this makes it seem a reference more suitable to #774.

Anyway I know the thought of creating 20,000 onion URLs seems absurd. Possibly there could be a limit to the number of files offered in this way. In that case the twist seems mainly to be how to declare which URL is the one for the main page, and which are the ones for the individual files, and how they relate to one another.

http://yjuwkcxlgo7f7o6s.onion can easily serve files in the manner referenced, and if you point any web browser to file:///somedirectory/somefile you can also easily get a browseable list of files and directories, all individually accessible. This may not be easy in any way to include as functionality, and obviously we're talking about basic elements of webservers here, but it's the kind of thing several people are I'm sure using as the basis of hope that it could be possible.

Other relevant bugs:
#582
#597
#653
#656
#663
and of course, #774

I understand this bump might be a bit disruptive, so I apologize for that. It's just that for many of my uses, this functionality is an obvious necessity.

**Comment by ghostlands** [comment]
Wow, due to #791 and #855 all this is moot.

Exciting stuff.
