### ISSUE TITLE
A warning is needed when selecting meek because of the CDN fees

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#657]
When a user chooses to use meek they should be warned that it cost TorProject more than using other pluggable transports. This warning could recommend users to try directly connecting to the tor network or using the obfs4 pluggable transport.

There has all ready been a large increase in meek users.
![userstats-bridge-transport-2017-12-03-2018-03-03-meek](https://user-images.githubusercontent.com/10781882/36928306-ad12d42a-1e39-11e8-9ce0-ee1765e82706.png)

**The cost using meek is listed in this summery.**
https://lists.torproject.org/pipermail/tor-project/2017-March/001052.html

**Comment by micahflee** [comment]
Good idea.
