### ISSUE TITLE
Can we use OnionShare app in China?

### ISSUE THREAD

**Issue by beknazar** [micahflee/onionshare#659]
Hello,
Is it possible to use OnionShare app in China?

Thanks.

**Comment by mig5** [comment]
Hi @beknazar,

If you are running Linux, you can install the latest version and choose one of the 'meek lite' bridges in the settings. Hopefully after that, you can use OnionShare. The 'meek_lite' bridges are supposed to help users in China connect to Tor.

If you already have a working Tor Browser, you can also [configure OnionShare to use your Tor Browser's tor connection](https://github.com/micahflee/onionshare/wiki/Connecting-to-Tor#attempt-automatic-configuration-with-tor-browser), and OnionShare should then work just like your Tor Browser works.

A future version will have direct meek bridge support for MacOS and Windows.

Hope that helps!

If you are having a problem using or downloading OnionShare, please let us know what the error is.

Thanks!
