### ISSUE TITLE
With --local-only flag, don't try connecting to Tor

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#662]
I've been using the `--local-only` flag more often while developing, but the Onion object still tries connecting to Tor. Instead, when `--local-only` is set, Onion should basically just stub out connecting to Tor, as if it was successful.

**Comment by mig5** [comment]
That's curious, didn't that used to work, e.g is it a regression?

Oh, or is it just something that never worked with bundled mode when it was introduced?
