### ISSUE TITLE
OnionShare freezing on Windows

### ISSUE THREAD

**Issue by leonardoporpora** [micahflee/onionshare#666]
I'm using windows and it doesn't work. I have dropped the file I wanted to share and after 2 days my friend tried to connect and it didn't work than i tried to stop the sharing and the App did not respond

**Comment by mig5** [comment]
I'm curious if you are running Windows in a virtual machine. I can confirm I periodically get freezes on Windows, but sometimes it works fine. I am using a Virtualbox VM.

**Comment by leonardoporpora** [comment]
No it wasn’t not a guest os. Not in a VM but in the main OS it got freezer after 2 days it was sharing

**Comment by mig5** [comment]
I've been doing lots of testing in Windows of the develop branch and it's been quite snappy and no freezes now. So I suspect we fixed this bug with our improved Threading changes and/or updated dependencies such as PyQt, Flask etc. I'm inclined to close this, the 2.0 release should be better on Windows.
