### ISSUE TITLE
V3 onionshare.org offline

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#668]
I get a unable to connect error every time I try to connect to http://lldan5gahapx5k7iafb3s4ikijc4ni7gx5iywdflkba5y2ezyg6sjgyd.onion/
@micahflee

**Comment by mig5** [comment]
Seems to be back online now. Maybe one of those cases we've seen where (on restart) re-uploading the v3 descriptor failed for a while.

**Comment by Baccount** [comment]
Its online for me too, thanks for checking.
