### ISSUE TITLE
Improve the CLI mode output

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#687]
I think it would be nice if the CLI version of OnionShare used some terminal colors to emphasize the right stuff, and perhaps had an ASCII art OnionShare logo.

**Comment by SamPatt** [comment]
I've created a color ASCII logo for OnionShare:

https://gist.github.com/SamPatt/974de851fe836e5823d35c1b635c3374

![image](https://user-images.githubusercontent.com/6955773/71699659-aed4a980-2d8e-11ea-881f-be8dce600d45.png)

Feel free to use if you like it.

**Comment by SamPatt** [comment]
ASCII art logo was merged in #1085.
