### ISSUE TITLE
V3 onion offline again

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#689]
Your v3 onion is offline again, I tried to build circuits to it multiple times and it keeps timing out. Try updating the server to Tor 0.3.2 or 0.3.3 Rc and see if that fixes the problem. Also make sure your servers clock is correctly synced.
@micahflee 
http://lldan5gahapx5k7iafb3s4ikijc4ni7gx5iywdflkba5y2ezyg6sjgyd.onion/

**Comment by micahflee** [comment]
Thanks @Baccount. I just checked, and I can connect fine now. The tor service is already 0.3.2.10, so I think it was likely a Tor network issues at the time you were checking.
