### ISSUE TITLE
Remove support for meek_lite Amazon :(

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#691]
Because Amazon <3 censorship.

Microsoft Azure should be the only meek bridge option now. Also, this is related to #674.

**Comment by Baccount** [comment]
@micahflee Tor said "For the time being, we are shifting to Microsoft’s Azure cloud. **But we’ve heard that option will soon be shut down, as wel**l." will  Azure also be removed?

**Comment by micahflee** [comment]
I saw that, but it sounds like that's just a rumor at this point, and as of now Azure still works. I don't think we need to remove support for it until they block it too, because (hopefully?) it's possible they won't.
