### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [micahflee/onionshare#694]
Hello Sir. I'm a UI/UX and Graphics Designer. I want provide a logo for you. Would you mind if I propose a new logo design for your application as my Open Source Contribution?

Thanks before.

**Comment by micahflee** [comment]
Way back in 2014 there was an issue for improving the OnionShare logo, #24. We ultimately ended up sticking with the current logo, which I designed in GIMP. I've gotten very used to the OnionShare logo, but I'm still totally open to improving it. Please go ahead and post some design ideas in this issue, if you'd like, and we can discuss if we'd like to switch to it.

**Comment by anharismail** [comment]
Hello, Sir @micahflee . These are my logo proposal for your application.
I'm very welcome if you have any comments, opinions, or revisions. Please just tell me.
I'll provide all file types and sizes you needed.
Hope you like it.

### Version 1
![onion share ver 1](https://user-images.githubusercontent.com/37614260/40276418-c986e35c-5c33-11e8-83eb-9682a95b0591.png)
### Version 2
![onion share ver 2](https://user-images.githubusercontent.com/37614260/40276421-d6517b4c-5c33-11e8-9ddc-ac84cd52dbbc.png)
### Version 3
![onion share ver 3](https://user-images.githubusercontent.com/37614260/40276424-ddd2a1f2-5c33-11e8-9efd-d53397c6e1c2.png)

**Comment by Baccount** [comment]
I like it, but it is almost identical to https://github.com/anharismail/onionr
![onionr-logo](https://user-images.githubusercontent.com/10781882/40579562-d8f27e96-60de-11e8-93ee-b410c081b659.png)

**Comment by anharismail** [comment]
Hi @Baccount , I think because its idea from the same thing "onion", there are some similarities. But if you look clearly, it will be different, I think there are three versions of design I propose to @micahflee . Hope the project owner give the solusion of your comments

**Comment by anharismail** [comment]
Hello Sir @micahflee , I thinks there's another idea for my proposal. It took your brand colour to the new logo.

### Ver. 1
![onion share ver 1 edit](https://user-images.githubusercontent.com/37614260/40584078-1944cbc0-61c5-11e8-9413-cfeaa70782fa.png)

### Ver. 2
![onion share ver 2 edit](https://user-images.githubusercontent.com/37614260/40584080-19d4dfda-61c5-11e8-888c-889bf5f5baf7.png)

### Ver. 3
![onion share ver 3 edit](https://user-images.githubusercontent.com/37614260/40584079-198fb194-61c5-11e8-9468-5d217bc54452.png)

**Comment by micahflee** [comment]
Hello @anharismail, thank you for your efforts in designing a new OnionShare logo.

After a lot of consideration, I think I've grown an attachment to the existing logo and want to keep it. Thanks for volunteering some graphics design time though!
