### ISSUE TITLE
Version 2.0 release

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#696]
There's already all of the issues in the [2.0 milestone](https://github.com/micahflee/onionshare/milestone/20), but I figured I'd make an issue where we can discuss other things that need to finished for this release, and a bit of a release strategy.

The major new feature is receiver mode (#695, #683, #97).

I think #663 (if you're sharing just one file, don't zip it) would be an excellent feature to get done with this release, and I don't think would be too difficult. Likewise, I'd like to get #406 (turn on macOS app sandboxing) working for this release. There are a handful of small Tor-related issues (#670, #674, #691), and a few other stranglers (#688, #667, #665, #685).

Finally, there are the localization issues (#669, #681, #685). I had a discussion with Localization Lab and they've agreed to help localize OnionShare into several languages! So I think finally, the 2.0 release be fully translated, with good, verified translations, into many different languages.

They said to reserve a full month to allow the localization community to get through all of the strings and to verify them. Also this is a major release that includes a lot of new functionality that should be tested thoroughly. So here's what I'm thinking would be a good plan:

* Finish everything in 2.0 except the localizations
* Upload the final English strings to a translation platform and work with Localization Lab to start getting them translated
* But in the meantime, create a development release, complete with signed binaries, and try to get people on the internet to begin testing them
* A month later, resolve any new bugs and merge in the final translations
* Make the final 2.0 release

**Comment by mig5** [comment]
OnionShare 2.0 was released, so we can close this :)
