### ISSUE TITLE
receiver-mode-gui, clicking the menu item and clicking on help causes the app to crash

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#702]
receiver-mode-gui, clicking the menu item and clicking on help button, causes the app to crash.
```
OnionShare.app/Contents/MacOS/onionshare-gui 
OnionShare 1.3 | https://onionshare.org/
Traceback (most recent call last):
  File "onionshare_gui/settings_dialog.py", line 795, in help_clicked
    self.common.log('SettingsDialog', 'help_clicked')
AttributeError: 'bool' object has no attribute 'common'
Abort trap: 6
```

**Comment by mig5** [comment]
I don't reproduce this (anymore? although the code hasn't changed there..) 

@Baccount is the issue gone now? If so we might be able to close this ticket.

**Comment by mig5** [comment]
Ah, via the System Tray this occurs indeed. I misread (works via SettingsDialog)
