### ISSUE TITLE
Load balancing and redundancy, Onionbalance 

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#703]
If a user wants to distribute a file between many receiving users, implementing onionbalance should help distribute the load between many introduction points. [Onionbalance also should work with V3 onions](https://onionbalance.readthedocs.io/en/latest/design.html#next-generation-onion-services-prop-224-compatibility), https://github.com/DonnchaC/onionbalance/issues/69#issuecomment-370928212

> OnionBalance implements round-robin like load balancing on top of Tor onion services. A typical OnionBalance deployment will incorporate one management servers and multiple backend application servers.
https://onionbalance.readthedocs.io/en/latest/getting-started.html

Installation instructions.
https://onionbalance.readthedocs.io/en/latest/installation.html
https://github.com/DonnchaC/onionbalance/
### Update
Here is the trac ticket, tracking the progress on _**Adding support for onionbalance in HSv3's**_
https://trac.torproject.org/projects/tor/ticket/26768

**Comment by Baccount** [comment]
Here is the trac ticket, tracking the progress on _**Adding support for onionbalance in HSv3's**_
https://trac.torproject.org/projects/tor/ticket/26768

**Comment by Baccount** [comment]
### Onionbalance has added support for V3 onions!
"Onionbalance is one of the standard ways onion service administrators can load balance onion services, but it didn't work for v3 onions. Until now. We just released a [new version of Onionbalance](https://gitlab.torproject.org/asn/onionbalance) that supports v3 onion services."
https://blog.torproject.org/cooking-onions-reclaiming-onionbalance
@mig5 
@micahflee

**Comment by micahflee** [comment]
This is interesting, but I don't think I've seen any real use cases for load balancing with OnionShare yet
