### ISSUE TITLE
Crash after adding a new file right after I end a share

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#706]
Onionshare crashed after Adding file right after I end a share. I attached the full crash log.
[Onionshare crash log.rtf.zip](https://github.com/micahflee/onionshare/files/2064639/Onionshare.crash.log.rtf.zip)
```
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Thread 7 Crashed:: OnionThread
0   libsystem_kernel.dylib        	0x00007fff5e47ab6e __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff5e645080 pthread_kill + 333
2   libsystem_c.dylib             	0x00007fff5e3d61ae abort + 127
3   QtCore                        	0x000000011244af29 0x112434000 + 93993
4   QtCore                        	0x000000011244c8a0 QMessageLogger::fatal(char const*, ...) const + 224
5   PyQt5.QtCore.so               	0x00000001122a8b6c pyqt5_err_print() + 812
6   sip.so                        	0x00000001129b24e1 sip_api_call_procedure_method + 245
7   PyQt5.QtCore.so               	0x00000001121af4d4 sipQThread::run() + 84
8   QtCore                        	0x000000011245ff6f 0x112434000 + 180079
9   libsystem_pthread.dylib       	0x00007fff5e642661 _pthread_body + 340
10  libsystem_pthread.dylib       	0x00007fff5e64250d _pthread_start + 377
11  libsystem_pthread.dylib       	0x00007fff5e641bf9 thread_start + 13

```

**Comment by mig5** [comment]
@Baccount was this against develop branch?

The steps as follows?

1) Start a share
2) Stop a share by clicking 'Stop Sharing'
3) Add a new file via the 'Add' button
4) app crashes?

If so I couldn't reproduce against develop. But I wondered if you were testing against receiver-mode-gui branch, haven't tried there yet.

**Comment by Baccount** [comment]
This bug did occur on the Dev branch, but it is not easy to reproduce. Here are the steps I used.
1. Add a file and start a share.
2. Stop a share
3. Quickly drag a new file onto the app and click start share. And it crashes.
@mig5

**Comment by mig5** [comment]
Are you still able to reproduce this @Baccount ? Some of the threading stuff has changed since June, but not sure if fixed (I could never reproduce it)

**Comment by Baccount** [comment]
@mig5 I did get this crash when quickly stopping and starting a share quickly, not sure if its the same bug as above.
```
Traceback (most recent call last):
  File "onionshare_gui/mode/share_mode/threads.py", line 44, in run
  File "onionshare/web/share_mode.py", line 274, in set_file_info
  File "onionshare/web/share_mode.py", line 348, in add_file
  File "zipfile.py", line 1707, in write
ValueError: Can't write to ZIP archive while an open writing handle exists
Abort trap: 6
```
