### ISSUE TITLE
Comply with the obfs4proxy license.

### ISSUE THREAD

**Issue by Yawning** [micahflee/onionshare#709]
obfs4proxy and associated code is distributed under a two clause BSD style license, which imposes requirements on binary re-distribution.

>  * Redistributions in binary form must reproduce the above copyright notice,
>   this list of conditions and the following disclaimer in the documentation
>   and/or other materials provided with the distribution.

The Windows and OSX binary packages are not in compliance with the requirements.  Please remove the infringing binary packages, and either cease re-distributing the obfs4proxy binary, or do so according to the terms of the license.

**Comment by micahflee** [comment]
Oops! I didn't realize we weren't complying with the license. I'll make a point release that includes the obfs4 license with the Windows and Mac binary releases.

**Comment by micahflee** [comment]
Hey @Yawning, we have released OnionShare 1.3.1 which includes a copy of the obfs4proxy license along with the binary in the Windows and Mac releases: https://github.com/micahflee/onionshare/releases/tag/v1.3.1

I believe the existing binaries for OnionShare 1.2 and 1.3 still violate the license. Do you want us to delete those binaries from the github releases page, or would you be ok with leaving them up just to keep a historical archive of old OnionShare versions?

**Comment by mig5** [comment]
Thanks @Yawning!
