### ISSUE TITLE
Debian 9 crash on start up, AttributeError

### ISSUE THREAD

**Issue by kurokeeper** [micahflee/onionshare#712]
Crash on start up, onionshare 1.3.1-1:

``adolfo@xxxx:~/onionshare$ ./dev_scripts/onionshare-gui 
OnionShare 1.3.1 | https://onionshare.org/
Connecting to the Tor network: 10% - Finishing handshake with directory server
Traceback (most recent call last):
  File "/home/adolfo/onionshare/onionshare_gui/onionshare_gui.py", line 563, in check_for_requests
    if self.systemTray.supportsMessages() and self.settings.get('systray_notifications'):
AttributeError: 'OnionShareGui' object has no attribute 'settings'
Aborted
``

System info:
``Linux xxxx 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 `GNU/Linux
``

**Comment by mig5** [comment]
Thanks, this is known and there is a fix awaiting merging in #700

**Comment by dpramone** [comment]
I confirm the uncommitted fix in https://github.com/micahflee/onionshare/pull/700/files#diff-ff1b65f5b513968c7312dc8c13bdb881 resolves the issue.
