### ISSUE TITLE
Slugs should be optional in order not to allow DoSing of 'public' OnionShares

### ISSUE THREAD

**Issue by b-meson** [micahflee/onionshare#713]
Right now the keep alive option is great but kind of defeats the purpose of a slug if you want to keep a .onion running for a long time. A malicious relay could hit the slug and DOS the server. Really a public server doesn’t need a slug. This should be easier to implement in send mode.

You may also want to do a similar feature for receive mode.

**Comment by Baccount** [comment]
@b-meson When ticket #677 is finished users will be able to use V3 Onions, V3 onions are Not vulnerable to Onion Service discovery attacks. 

>  For example, did you know that in the legacy onion system, the network could [learn about your onions?](https://lists.torproject.org/pipermail/tor-talk/2017-March/042986.html) However, with this next-generation design, your onion address is completely private and only known to you and whoever you choose to disclose it to.


More information on V3 onions 
https://blog.torproject.org/tors-fall-harvest-next-generation-onion-services
https://trac.torproject.org/projects/tor/wiki/doc/NextGenOnions

**Comment by mig5** [comment]
I agree with this - it is not so much about discovery attacks as it is about a user's conscious choice to perhaps publicise their OnionShare URL for public access. Any malicious actor could immediately bring down the share by deliberately hitting 20 false slugs. Regardless of v3 we should definitely make the slug optional.

**Comment by mig5** [comment]
A PR at #722 - note it's based on the receiver-mode-gui branch, because that branch already had this feature for Receive Mode. Just expanding it to support Share mode.

**Comment by micahflee** [comment]
This is implemented in the `receiver-mode-gui` branch.
