### ISSUE TITLE
If I append .onion/static/css/style.css to the end of the onion, it will show the css file without using the slugs

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#714]
If I append .onion/static/css/style.css to the end of the onion, it will show the css file without using the slugs.
1. start a share and remove the slugs from the end of the .onion and replace it with 
http://xxd5mpnxflagbebcmqzyyvupdnu4yoaaqrjpi55kzowssoatottul5qd.onion/static/css/style.css
If this is not a bug then this issue can be closed

**Comment by micahflee** [comment]
I don't think this is a bug. OnionShare doesn't make any effort to hide the fact that an onion website you're visiting is powered by OnionShare, only the content of the files being shared. So protecting static resources is outside the scope of the threat model. The only information that can really be gleamed from that is potentially what version of OnionShare the sender is using.
