### ISSUE TITLE
1.3.1 Crash on OSX Yosemite

### ISSUE THREAD

**Issue by danmcne** [micahflee/onionshare#725]
Crashes on start-up. A bit frustrating because the update was suggested, replaced the previous installation and downloads of previous versions are not easily available on the website.

**Comment by mig5** [comment]
Hi @danmcne, sorry to hear of this issue, but thanks for reporting it!

Would it be possible for you to provide some more debug info so we can troubleshoot, since we definitely didn't reproduce this when building the last release.

You can open a Terminal and:

`cd /Applications/OnionShare.app/Contents/MacOS` 

(this is usually where OnionShare is installed on a Mac)

Then run:

`./onionshare-gui --debug`

If the app crashes, maybe there'll be some debug output in the Terminal that we can investigate.

Thanks!

**Comment by mig5** [comment]
Possibly there's some dependency issue with Yosemite. I only have a High Sierra (10.13.6) macbook to test. What do you use @micahflee?

**Comment by Baccount** [comment]
@mig5 Bumping Tor to 0.3.4.8 may fix the crashing issue 
`Work around two different bugs in the OS X 10.10 and later SDKs that would prevent us from successfully targeting earlier versions of OS X. Fixes bug 26876; bugfix on 0.3.3.1-alpha.`
https://bugs.torproject.org/26876

Here is my pull request with the latest TorBrowser 8.0.1 with Tor 0.3.4.8 https://github.com/micahflee/onionshare/pull/785

**Comment by K-Twelve** [comment]
> I also use High Sierra, however I have a 10.9 computer I use to create releases. I wasn't able to reproduce a crash on that the last time I made a release, but I haven't tested recently.

Traceback (most recent call last):
  File "onionshare-pyinstaller", line 34, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "onionshare_gui/__init__.py", line 22, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "onionshare_gui/alert.py", line 20, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
ImportError: dlopen(/Applications/OnionShare.app/Contents/MacOS/sip.so, 2): no suitable image found.  Did find:
	/Applications/OnionShare.app/Contents/MacOS/sip.so: code signature invalid for '/Applications/OnionShare.app/Contents/MacOS/sip.so'

**Comment by bitmold** [comment]
This crash seems to still occur in Version 2.3.1 on Mac OS 10.9(.5).

Running `./OnionShare --debug` produces:

```
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Applications/OnionShare.app/Contents/Resources/Support/bin/python3
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Applications/OnionShare.app/Contents/Resources/Support/bin/python3
  Expected in: /usr/lib/libSystem.B.dylib

./OnionShare: line 5:  5188 Trace/BPT trap: 5       Support/bin/python3 -m onionshare "$@"
```

It seems that this `clock_gettime` thing was provided by default in Mac OS 10.12. People online suggest on systems < 10.12 to run `xcode-select --install` which I guess downloads that dependency in addition to a bunch of other crap. 

@micahflee I would imagine that you probably have run the above xcode command before if you are/were building Onion Share on a 10.9 machine which might explain why you haven't seen the issue but others have.

**Comment by bitmold** [comment]
I might have access to a mac in the coming weeks and will try to see if I can get this going. I was really bummed to find out that my friend rocking 10.9 couldn't onionshare me stuff unless maybe she installed a ton of bloated dev tools onto her old mac book air

**Comment by micahflee** [comment]
Yosemite hasn't been supported by Apple since August 2017, so OnionShare won't support it either
