### ISSUE TITLE
Onionshare-gui coredumps after successfull file download on OpenSUSE Leap 15.0 Linux

### ISSUE THREAD

**Issue by dpramone** [micahflee/onionshare#727]
Stopped because download finished
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/onionshare_gui/onionshare_gui.py", line 588, in check_for_requests
    self.downloads.add_download(event["data"]["id"], web.zip_filesize)
NameError: name 'web' is not defined
Aborted (core dumped)

**Comment by mig5** [comment]
Thanks @dpramone, this is a known bug and there is a fix in Pull request #700 if you want to use that to patch your system. Just waiting on @micahflee to merge it in :)
