### ISSUE TITLE
build.md does not mention rpm-build package requirement for building on rpm-based system

### ISSUE THREAD

**Issue by dpramone** [micahflee/onionshare#728]
rpm-build script in install dir will bail out with "rpm -ba" error if rpmbuild is not installed on system.

Names of package dependencies may also be different on non-RH/Fedora systems, and/or may only be found in 3rd party repositories (e.g. obfs4-obfs4proxy on SuSE)

**Comment by mig5** [comment]
Hi @dpramone , thanks, we'll add rpm-build to the BUILD.md or feel free to send a pull request. It seems rpm-build comes down automatically as a dependency on Fedora 27 (at least), which is how this was missed, but maybe is not the case on other distros.

Regarding SuSE, we'd also welcome a PR for the BUILD.md with any extra info - perhaps even a single line like the ArchLinux one, that points to a new section of the [Linux Distro Support wiki page](https://github.com/micahflee/onionshare/wiki/Linux-Distribution-Support). Do you want to put something together on what worked for your system?

**Comment by dpramone** [comment]
First-time install on OpenSuSE Leap 15.0 :

1) Open a (non-root) terminal window (xterm, kconsole, yakuake) or virtual console (Alt-Ctrl-Fx)
2) Add additional repositories "obfs4" and "network". The obfs4-obfs4proxy .rpm does not exist in the main SuSE Leap 15.0 repositories. Adding the network repository is optional but recommended as standard SuSE repositories generally contain an older Tor version.
- sudo zypper addrepo --check --refresh --name "obfs4" http://download.opensuse.org/repositories/home:/hayyan71/openSUSE_Leap_15.0/
- sudo zypper addrepo --check --refresh --name "network "http://download.opensuse.org/repositories/network/openSUSE_Leap_15.0/
3) Install dependencies through GUI (System, Yast; Install/Remove Software) or command line (zypper). Accept (automatic) installation of additional dependencies, if any.
- sudo zypper install git python3-pip python3-Flask python3-qt5 python3-nautilus python3-pytest network:tor obfs4:obfs4-obfs4proxy
4) Install required Python 3 modules not available through SuSE .rpm repositories
- sudo pip3 install stem
5) Optional: for building/installing the Onionshare .rpm
- sudo zypper install rpm-build
6) Clone Onionshare git repo from Github
- As a normal user (not root): cd ~/(your preferred app/git directory) 
- git clone https://github.com/micahflee/onionshare.git
- cd onionshare
7) Optional: build and install Onionshare rpm
- rm dist/onionshare-*.rpm
- ./install/build_rpm.sh
- sudo rpm -ivf --nodeps --force dist/onionshare-*.rpm
8) Execute onionshare-gui
- Without rpm building/installation: ./dev_scripts/onionshare-gui &
- With rpm building/installation: onionshare-gui &

**Comment by mig5** [comment]
Thanks @dpramone, I've folded your documentation into https://github.com/micahflee/onionshare/wiki/Linux-Distribution-Support#opensuse-leap-150

We'll add a link to it, as well as explicitly mentioning rpm-build, in the BUILD.md.
