### ISSUE TITLE
Missing instructions on how to update translation

### ISSUE THREAD

**Issue by scootergrisen** [micahflee/onionshare#730]
I would like instructions on how to update the translation (json files).
If possible i would like po/pot instead of the json file as they are smarter to update.

**Comment by mig5** [comment]
Hi @scootergrisen, we have documentation for how to add or update Translations, see this section of the wiki:

https://github.com/micahflee/onionshare/wiki/Translating

It actually looks like you were the last person to edit this document, in February :)

With regards to changing how translations are done, we have a ticket for that too: #669

Cheers

**Comment by scootergrisen** [comment]
I don't see how that could help me update a string that have been changed like https://github.com/micahflee/onionshare/commit/aa8c07c43439819b3f4fcc4dff169e695ad84695#diff-d41af00af6adb35bcd013254185bdc6d

**Comment by mig5** [comment]
@scootergrisen the wiki instructions say (in summary):

1) fork the repo
2) add or update the line in the .json file of your relevant language (if the line doesn't exist in your .json, add it. If the line exists but the translation needs updating it, update it)
3) send a pull request to merge the changes from your fork

Which part are you unsure how to achieve?

**Comment by scootergrisen** [comment]
How would i know when a string have changed?

**Comment by mig5** [comment]
There's no real way, except to analyse the english file.

For strings that don't exist, there's a script, as per the wiki.

As noted above, we will hopefully soon move to a new system for translating that is less cumbersome.

**Comment by scootergrisen** [comment]
Ok. Weblate or po/pot files would be fine.

**Comment by mig5** [comment]
Thanks @scootergrisen ! I've noted your thoughts in #669 so hopefully we'll progress to a better solution soon. I'll close this again for now just to reduce duplication of tickets.

**Comment by scootergrisen** [comment]
Ok i just want updating the translation till it available on Weblate/Transifex/other place.
