### ISSUE TITLE
Upload History overlap bug

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#732]
When I open the upload history popup, the words **upload history** get overlapped
<img width="462" alt="screen shot 2018-08-22 at 7 54 33 pm" src="https://user-images.githubusercontent.com/10781882/44502228-5e4f2700-a645-11e8-922a-962824149183.png">
Tested using branch mig5:prop224_receiver_mode

**Comment by mig5** [comment]
Strange, it works fine for me on Linux (Debian 9)

![onionshare-upload](https://user-images.githubusercontent.com/99173/44504338-c56cea00-a6de-11e8-92cd-9799f4c1d380.png)

I'm guessing it's a stylesheets issue on the MacOS version of Qt

**Comment by mig5** [comment]
@Baccount I wonder why it looks OK for you in #704 ? As far as I know, the code there hasn't changed... very strange

**Comment by mig5** [comment]
Interesting, I don't reproduce on my Mac when compiling

<img width="462" alt="screen shot 2018-08-23 at 4 33 59 pm" src="https://user-images.githubusercontent.com/99173/44508703-8fd1fc00-a6f2-11e8-9337-1e66c6f82dab.png">

yes overlap issue is already reported by you in a separate ticket

**Comment by Baccount** [comment]
@mig5 Odd, I tried to reproduce the bug using the same steps, start receiver mode and upload any file and then view the Upload History popup and the bug is no longer occurring. Sorry I forgot about the overlap ticket.

**Comment by Baccount** [comment]
Closing and I will open a new ticket if the bug occurs again.
