### ISSUE TITLE
pip3 install pygtk

### ISSUE THREAD

**Issue by lihongbo6668201** [micahflee/onionshare#734]
Collecting pygtk
  Using cached https://files.pythonhosted.org/packages/7c/18/fa4f2de77500dd62a314fd845ff6e903ac2ce551164cb421c5750969f799/pygtk-2.24.0.tar.bz2
    Complete output from command python setup.py egg_info:
    ********************************************************************
    * Building PyGTK using distutils is only supported on windows. *
    * To build PyGTK in a supported way, read the INSTALL file.    *
    ********************************************************************

-------------------------------
I'm really hopeless! I need your help...

**Comment by lihongbo6668201** [comment]
I tried a lot of methods, but they didn't work.

**Comment by mig5** [comment]
Hi, I think you have the wrong project. PyGTK is not a dependency of OnionShare. Sorry!
