### ISSUE TITLE
Support HTTP range requests for `wget --continue`

### ISSUE THREAD

**Issue by infinity0** [micahflee/onionshare#736]
It's nice to be able to conveniently share private photos and videos over onionshare even over a shitty internet connection. At the moment I have to start 10 onionshare instances to share 100MB each because the connection is not reliable enough to share 1GB at a time, and onionshare doesn't support `torsocks wget --continue`.

All that is needed for this is for onionshare to support [HTTP Range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests).

I see a similar proposal #175 was rejected, however I think you should reconsider. This one should be more simple than that to implement, but also importantly neither of these proposals would *require* the receiver to install extra software, they can still just use Tor Browser. The proposal only makes it more convenient for users that do have other tools like `wget` at their disposal, or a Firefox extension like `DownThemAll`.

**Comment by micahflee** [comment]
This is supported
