### ISSUE TITLE
Final receive mode changes

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#748]
The #695 PR is becoming a monster, and is more current than develop. I think it's not _quite_ done, but we should merge anyway if it's in a good state. This issue is to make sure we continue to keep track of the final bits that need finishing.

Here's a to do list copied and pasted from that PR:

* If an upload fails to finish, it should be marked as failed in the upload history
* Prevent 0 byte, filename-less files (this happened when I made a public receive mode for some reason)
* Often, the open folder icon doesn't appear next to uploaded file. It should always appear

Finished:

* ~~In Upload History window, really long filenames should be word-wrapped #704~~
* ~~Related, if I start the server in receive mode, start uploading large files, then stop the server before they've uploaded, the upload history window still shows the in-progress upload. If I then start the server again, it crashes #756~~
* ~~Make sure `Settings.build_default_downloads_dir()` works in Windows~~
* ~~Update `install/onionshare.nsi` to make the Windows installer/uninstaller use all the new filenames~~
* ~~More thoroughly test the toggle button for Uploads/Downloads, making sure it actually scrolls to the bottom at the appropriate times, etc. #757~~
* ~~Improve the language of strings, based on feedback from @glenn-sorrentino~~
* ~~Change receive mode web interface, based on feedback from @glenn-sorrentino~~
* ~~In settings dialog, persistent address is a common setting, not just for share mode~~
* ~~Update "uploads complete" and "uploads in progress" numbers, and change the mouseover text #755~~
* ~~You should be able to clear upload history #766~~
* ~~In ReceiveMode, make `Uploads.open_folder()` actually open folders with specific file selected in Windows and macOS #763~~
* ~~In `ReceiveMode.timeout_finished_should_stop_server()`, wait for current uploads to finish before stopping the server, but still prevent new uploads from starting #752~~

**Comment by mig5** [comment]
"I'm finished sending" button can be pressed by a user whilst another user is still uploading a large file.

The button should be removed somehow or its route made to do nothing if an upload is still in progress.

The problem is, doing so leaks the fact that an upload *is* in progress, which might be bad for security.

Should we just prevent the option for the sender to close the share, placing that responsibility on the user who is running OnionShare?

**Comment by micahflee** [comment]
> Should we just prevent the option for the sender to close the share, placing that responsibility on the user who is running OnionShare?

This is a good question. My reasoning for adding that button is to sort of replicate the "close after first download" sharing setting, so that the OnionShare user doesn't have to keep the server running for longer than necessary.

But that said, I think the autostop timer should be fine for that use-case -- especially with #752, and we can remove the close button.

**Comment by mig5** [comment]
I've annotated your original message in this ticket to note the items that have PRs/open issues about them, or are done (strikethrough).

**Comment by mig5** [comment]
> Make sure Settings.build_default_downloads_dir() works in Windows

I confirmed I could upload a file from Whonix Tor Browser, to my Windows Receive Mode, and I found the file in C:\Users\Miguel\OnionShare\ . Does that mean we can strike that out?

> Update install/onionshare.nsi to make the Windows installer/uninstaller use all the new filenames

I think we can strike that out now that the updated dependencies have been merged in?

**Comment by micahflee** [comment]
Yup! I also just crossed out updating receive mode strings and web UI based on feedback from Glenn, and I'm pretty sure I already did that.

**Comment by mig5** [comment]
> Prevent 0 byte, filename-less files (this happened when I made a public receive mode for some reason)

I reproduced this yesterday. It occurs when you are fast enough to send a new file before the page re-renders or something on the 'redirect' that Flask sends after accepting the last file, I think. Maybe we need to use javascript to hide the button after hitting Send, or something, not sure. Ideally no javascript..

**Comment by mig5** [comment]
> Update "uploads complete" and "uploads in progress" numbers, and change the mouseover text #755 

Think this is now finished

**Comment by micahflee** [comment]
There are the items that still haven't been crossed off the to do list:

* If an upload fails to finish, it should be marked as failed in the upload history
* Prevent 0 byte, filename-less files (this happened when I made a public receive mode for some reason)
* Often, the open folder icon doesn't appear next to uploaded file. It should always appear

But, after working through #874 and testing receive mode quite thoroughly, I'm pretty sure these are all now resolved.
