### ISSUE TITLE
Add instructions to create virtualenvs for dev builds in BUILD.md

### ISSUE THREAD

**Issue by maqp** [micahflee/onionshare#759]
Currently following the [instructions](https://github.com/micahflee/onionshare/blob/master/BUILD.md#linux) on installing dev build on Linux (Ubuntu 18.04)

    git clone https://github.com/micahflee/onionshare.git  # 1
    cd onionshare  # 2
    sudo apt install -y build-essential fakeroot python3-all python3-stdeb dh-python python3-flask python3-stem python3-pyqt5 python-nautilus python3-pytest tor obfs4proxy  # 3
    ./dev_scripts/onionshare-gui  # 4

leads to

    ModuleNotFoundError: No module named 'socks'

---

This is because the pip dependencies haven't been installed. So I think it would be a good idea to add `python3-pip` to # 3 and provide virtualenv installation and use instructions:

    git clone https://github.com/micahflee/onionshare.git
    cd onionshare
    sudo apt install -y build-essential fakeroot python3-all python3-stdeb dh-python python3-flask python3-stem python3-pyqt5 python3-pip python-nautilus python3-pytest tor obfs4proxy
    pip3 install virtualenv
    virtualenv venv --system-site-packages
    source venv/bin/activate
    pip3 install -r install/requirements.txt
    
    ./dev_scripts/onionshare-gui

After closing OnionShare, exit virtual environment with

    deactivate

Subsequent launches are done by navigating to root directory of the project and doing 

    source venv/bin/activate
    ./dev_scripts/onionshare-gui

Unfortunately I'm not able to check if OSX/Windows work just by copy-pasting commands.

**Comment by mig5** [comment]
Hi @maqp , it sounds like you've checked out the `develop` branch, which depends on pysocks, but you've followed the BUILD.md from `master` branch, which does not contain the new list of dependencies.

It is normally not necessary to install using pip, except for pysha3 on some older systems, as of the `develop` branch.

Having said that I'm not against having some virtualenv instructions like this, maybe in the BUILD.md but certainly you could go right ahead and add such instructions to the wiki under 'Linux Distribution Support'.

For now I recommend using the develop branch, and following the BUILD.md from that branch, which is much more recent.

**Comment by mig5** [comment]
I've adjusted [this doc](https://github.com/micahflee/onionshare/wiki/Developing-OnionShare) which you maybe followed and it tripped you up (it clones develop branch, but points you to the master branch's BUILD.md). 

When developing, always work off of the develop branch. master branch is a pristine branch that we release off of, so it lags way behind now.

**Comment by maqp** [comment]
Whoops, yes you're absolutely right! The develop branch instructions work great. Thanks for fixing the URL to proper BUILD.md :)
