### ISSUE TITLE
After 2.0 release, get it backported into Debian stretch

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#775]
Discussion about this in #772.

**Comment by mig5** [comment]
Looks like it won't even get into Buster due to its freeze, let alone Stretch?

https://redmine.tails.boum.org/code/issues/16479

**Comment by mig5** [comment]
I feel like this is not going to happen (Stretch is not even latest stable anymore) but moreso, there is already an active downstream Debian team watching our releases and packaging the new versions of OnionShare into the latest Debian they possibly can (which is still too slow, but there you go) presumably for TAILS reasons - we don't really need a ticket for this here IMO.

I'd be willing to host a reprepro Debian repo on the onionshare infrastructure if we wanted it (maybe depending on a minimum Tor version that requires the user to set up the 3rd part Tor apt repo? or even asking the Tor Project to host the deb package for OnionShare instead?), we can open another ticket for that if we decide to do that.
