### ISSUE TITLE
Static website sharing with OnionShare

### ISSUE THREAD

**Issue by hiromipaw** [micahflee/onionshare#791]
With @holantonela have been thinking of how OnionShare could be used to share a static website. 

I have started to hack this functionality for the cli. 

https://github.com/hiromipaw/onionshare/tree/website-sharing

Please consider that there are still quite a few things to clean up and a few consideration to make, but since I believe there isn't better explanation of a feature than a few lines of code, I thought this could be a nice way to start a conversation about this.

Please let me know what you all think.

**Comment by micahflee** [comment]
Nice this is awesome! I just tested it out and it appears to partially work! :) I'm super excited for this feature, and also I'd love to help develop it with you too.

We have a bunch to finish with OnionShare 2.0, including a lot of localization work. Since this is a major new feature, I think maybe we can aim for version 2.1.

**Comment by subscriptionblocker** [comment]
> With @holantonela have been thinking of how OnionShare could be used to share a static website.
> 
> I have started to hack this functionality for the cli.
> 
> https://github.com/hiromipaw/onionshare/tree/website-sharing
> 
> Please consider that there are still quite a few things to clean up and a few consideration to make, but since I believe there isn't better explanation of a feature than a few lines of code, I thought this could be a nice way to start a conversation about this.
> 
> Please let me know what you all think.

I've been requesting this feature for a long time. Am baffled that your small group can deliver so much and the Tor group so little?

If possible would like to home host multiple static websites with onionshare. V3 with authorization cookies.

**Comment by micahflee** [comment]
I'm keeping this issue open until #990, #991, #992, #993, and #994 are resolved.

**Comment by micahflee** [comment]
#992 and #994 still need to be resolved, but I think it's fine to close this now.

**Comment by devidkupper** [comment]
**Hi. I have a beautiful , generated in another program, onion address for a static site . How to insert this address into this program ? I want to use not a random address for the site, but his beautiful.**

**Comment by mig5** [comment]
Have a read of https://github.com/onionshare/onionshare/issues/1550 where I explain how to replace an onion address in OnionShare with another, pre-generated onion address.
