### ISSUE TITLE
question: where will be files saved, after sharing

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [micahflee/onionshare#802]
you said in info page, the files will be saved on my pc, so my question is: where it will be saved

**Comment by mig5** [comment]
Hi @EsmailELBoBDev2 , do you mean in 'Receive' mode, which only exists in our develop branch (not in the latest stable)?

If so, it's usually a directory 'OnionShare' in the user's home folder, by default. You can configure the location in the Settings interface of OnionShare.

**Comment by micahflee** [comment]
In Share mode, when you send files to someone else, they click a link to download them in Tor Browser and get to choose where to save them to. But most people probably save it to their Downloads folder.

**Comment by EsmailELBoBDev2** [comment]
@mig5 i mean when i share file, its uploading to your servers or its stored on my PC ?

**Comment by EsmailELBoBDev2** [comment]
@mig5 ok, lest imagine, i uploaded file which stored on my desktop, so it will be located in OnionShare in desktop too, or program will make copy & save it in another location on my hard disk ?

**Comment by mig5** [comment]
@EsmailELBoBDev2 if someone sends a file to your OnionShare when it's in 'receive mode', it will be saved to a folder called 'OnionShare' of your user directory, by default (where this directory is, is different for Windows, Mac or Linux). See my first reply. But that feature hasn't been released yet.

If someone *downloads* a file from your OnionShare (in 'share' mode), it will be in their Downloads folder of their Tor Browser.

I'm afraid I'm not understanding your question, maybe if you add some screenshots of what you want to do it might help.

**Comment by EsmailELBoBDev2** [comment]
> But that feature hasn't been released yet
when it will come then ? & where files will be saved in current version ?

**Comment by EsmailELBoBDev2** [comment]
@mig5 
> But that feature hasn't been released yet

when it will come then ? & where files will be saved in current version ?

**Comment by micahflee** [comment]
@EsmailELBoBDev2, in the current version (1.3), OnionShare only has share mode. Here's how it works.

- You open it, add files and folders, and click a button to start sharing them. 
- OnionShare zips up all of those files and stores them in a temporary folder on your computer.
- It then runs a web server on your computer, basically with a web page that has a link to that zipped up file.
- Then it makes this web server a Tor onion service, which means other people can load the website across the internet using the Tor network. When the onion service starts, it shows you a .onion URL for your onion service and copies it to your clipboard.

Then you send this URL to your friend. On their computer, they open Tor Browser and load it. Then they can choose to click the link and download the zipped up file directly from your computer, over the Tor network, and save wherever they choose on their computer, probably their Downloads folder.

By default, as soon as they finish downloading the file, on your computer OnionShare stops the onion service and web server. When those stop, it deletes the temporary zip file.

In the next version (2.0), share mode will work exactly the same. But there's a new mode called receive mode. Here's how this mode works:

- You switch to the receive mode tab, and click a button to start receive mode.
- OnionShare starts a web server on your computer.
- It then starts an onion service, and gives you the URL.

You give the URL to a friend. They load it in Tor Browser on their computer, and they can choose to upload files to you. When they upload files, they get downloaded directly to your computer. By default, they get put in a folder called ~/OnionShare, but you can change that to whatever folder you want in the settings.

**Comment by EsmailELBoBDev2** [comment]
yay! finally i got it 😂😂

Thx 😀

**Comment by EsmailELBoBDev2** [comment]
@micahflee 

yay! finally i got it joyjoy

Thx grinning
