### ISSUE TITLE
Detect already compressed data and don't double compress

### ISSUE THREAD

**Issue by heartsucker** [micahflee/onionshare#815]
For large files, I use xz compression and it takes onionshare a long time to start up (on the CLI "Preparing files to share."), and it would be nice to be able to skip that step.

**Comment by mig5** [comment]
As above - and for the use case of 'download individual files being shared' (rather than zip them all up), I believe we have a separate ticket for that (the Website Sharing mode, which will incidentally enable this behaviour)

**Comment by Astavie** [comment]
This seems to be a thing again. Trying to send a .zip file of around 10gigs and it is re-compressing it on the cli (2.6.4)
