### ISSUE TITLE
Install on Raspbian?

### ISSUE THREAD

**Issue by GGGunrunner** [micahflee/onionshare#817]
I'm running Raspbian Stretch... Followed all instructions in BUILD.md
But seems that not all requirements are met:

ImportError: No module named 'sha3'

---
pip install sha3
Collecting sha3
  Downloading https://files.pythonhosted.org/packages/b3/b4Building wheels for collected packages: sha3
  Running setup.py bdist_wheel for sha3 ... done
  Stored in directory: /root/.cache/pip/wheels/24/e0Successfully built sha3

Ran again - same error...

I remember installing Onionshare about a year ago on Raspbian Jesse.... with some legwork, handwork, and chanting, managed it to run. But not this time (yet).

**Comment by mig5** [comment]
Hi @GGGunrunner,

You're on the develop branch. If you're trying to build the latest stable release (1.3.1), do a `git checkout master` before proceeding with the rest of the BUILD.md, and you'll avoid that issue.

If you're deliberately trying to build a version of the yet-to-be-released next version of OnionShare (2.0), that's a known issue, in that Stretch is not currently supported in `develop` branch. But you might want to checkout the branch `v3-revisited`, which happens to fix that dependency issue on Stretch, per the PR at https://github.com/micahflee/onionshare/pull/806

Let us know how you go! Cheers!

**Comment by mig5** [comment]
We no longer depend on sha3. This can be closed
