### ISSUE TITLE
Cannot resolve "stem" dependency

### ISSUE THREAD

**Issue by TROMsite** [micahflee/onionshare#824]
I get this error in Manjaro (Arch) when trying to install from AUR.

**Comment by mig5** [comment]
Hi @TROMsite , thanks for the report.

You may need to report this to the Arch maintainer of OnionShare? It sounds like Stem (the Python API for Tor) is missing or needs to be referenced in some other way.

The upstream maintainers of OnionShare are not currently building for Arch, that is handled downstream by someone involved with Arch.

I can see some discussion potentially by you already at https://aur.archlinux.org/packages/onionshare/, sounds like it might be an issue with Manjaro. I don't think we can fix this upstream unfortunately.

**Comment by TROMsite** [comment]
> Hi @TROMsite , thanks for the report.
> 
> You may need to report this to the Arch maintainer of OnionShare? It sounds like Stem (the Python API for Tor) is missing or needs to be referenced in some other way.
> 
> The upstream maintainers of OnionShare are not currently building for Arch, that is handled downstream by someone involved with Arch.
> 
> I can see some discussion potentially by you already at https://aur.archlinux.org/packages/onionshare/, sounds like it might be an issue with Manjaro. I don't think we can fix this upstream unfortunately.

Hi,
Thank you. Yes I also reported to AUR it seems it is an issue with Manjaro and AUR. Thank you for the quick reply!
