### ISSUE TITLE
Uploading files ("drop box" functionality)?

### ISSUE THREAD

**Issue by Handwrit** [micahflee/onionshare#828]
Are there plans to allow for the uploading of files? It seems like a better design for the use case - the journalist runs Onionshare, waiting for their whistleblower to get an opportunity to upload them. The whistleblower wouldn't have to stay online waiting for the journalist to show up, improving whistleblower safety.

**Comment by mig5** [comment]
Hi @Handwrit ,

Yes, that feature is what we've named 'Receive Mode', and it will be in the next release of OnionShare. You'll be able to flip between 'Share' mode (the traditional method) and 'Receive' mode (the method you describe), from within the UI, as well as via CLI.

It's actually already totally usable (almost 100% feature complete, just tidying up some rough edges), in the `develop` branch in git. 

If you wanted to try it out today, you could clone the repository and follow the instructions in the [BUILD.md](https://github.com/micahflee/onionshare/blob/develop/BUILD.md) to build from source.

I encourage you to try it out and let us know if you come across any issues! Thanks for your interest :)

**Comment by Handwrit** [comment]
Thanks so much for answering, mig5!
