### ISSUE TITLE
Installing onionshare issue on Whonix 14 "there was an error with Tor: SET EVENTS rejected HS_DESC"

### ISSUE THREAD

**Issue by Cottonwoodhill** [micahflee/onionshare#829]
Hi `@`

I am trying to install onionshare on my Whonix 14 Workstation.

I read the [Wiki documentation](https://www.whonix.org/wiki/OnionShare) but unfortunately I always get the bellow error while starting to share some files : 

https://forums.whonix.org/uploads/default/original/2X/d/dff8d57d12b36166965bcf4093692ac6d00eaa52.jpeg

**Here are my settings :** 

https://forums.whonix.org/uploads/default/original/2X/a/ae0c5f812a2d13b3502df25bc966a1204526960a.jpeg

**I also added the line**

> EXTERNAL_OPEN_PORTS+=" $(seq 17600 17659) "

into the Firewall Settings using the command line.

**Test Connection to Tor results give the output :** 
 
https://forums.whonix.org/uploads/default/original/2X/2/2b83472503242129d94816b7a815f9b300f1ed8f.jpeg

Thank you for your great support.

[Original post on the Whonix forum.](https://forums.whonix.org/t/installing-onionshare-issue/6408)

**Comment by Cottonwoodhill** [comment]
My fault sorry guys.

I extended the onion-grater whitelist in Whonix-Workstation instead of in the Whonix-Gateway... 

@Admins : please feel free to delete this thread.

Sorry for any inconvenience.

**Comment by adrelanos** [comment]
Unrelated, Whonix, FYI only:

Added support for OnionShare in "bundled Tor" configuration which is the default in Debian buster version of OnionShare.

* https://github.com/Whonix/anon-ws-disable-stacked-tor/commit/6cbc889b37648b8b8cae8193c675b3c5aef9e55f
* https://github.com/Whonix/onion-grater/commit/de336a6eff5d26f56677c45ed966f49dac885e79
