### ISSUE TITLE
Mac app bundle won't start from Finder, but will start from Terminal

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#846]
In macOS, you can build an app bundle by running `./install/build-osx.sh`, which creates `./dist/OnionShare.app`.

It works fine if I run the app bundle in a terminal by executing the binary directly: `./dist/OnionShare.app/Contents/MacOS/onionshare-gui`. It also works fine if I use the `open` command: `open ./dist/OnionShare.app/`.

However, if I open Finder, browse to the app bundle, and double-click it, you can see the icon bounce on the dock once, then it immediately closes.

In macOS 10.14.1 (Mojave), when I open the Console app, I see this error `Finder` error:

```
Unable to load Info.plist exceptions (eGPUOverrides)
```

I also see `lsd` errors:

```
Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Users/user/code/onionshare/dist/OnionShare.app/Contents/, NSFilePath=/Users/user/code/onionshare/dist/OnionShare.app/Contents/PlugIns, NSUnderlyingError=0x7feae08151d0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
cannot open file at line 42249 of [95fbac39ba]
os_unix.c:42249: (2) open(/var/db/DetachedSignatures) - No such file or directory
MacOS error: -67062
MacOS error: -67062
Parsed Info.plist for <private>
Parsed MobileInstallation data for <private>
UNIX error exception: 8
```

There also appear to be other Console error messages, but it's not clear what, if any, are related to this bug.

And on macOS 10.11.6 (El Capitan, what the OnionShare build machine runs), it's the same. It runs from the terminal, not from Finder, only it doesn't generate any Console errors.

I found this bug while working on the Mac sandbox (#823) and thought it was related to the sandbox, but it actually seems to exist in develop without the sandbox code.

I also built a new app bundle from the `v1.3.1` git tag, and it doesn't have this problem. So, whatever is going on is definitely a new bug that's been introduced somewhere.

**Comment by micahflee** [comment]
I've confirmed it doesn't have to do with `Info.plist`. If `onionshare_gui.main()` is replaced with a PyQt5 hello world app, it works fine to run from Finder.

**Comment by Baccount** [comment]
@micahflee It looks like other developers are seeing the same issue.
https://forums.developer.apple.com/thread/110340
Possible solution 
https://www.felix-schwarz.org/blog/2018/08/new-apple-event-apis-in-macos-mojave

**Comment by micahflee** [comment]
I actually think the problem is something totally weird and unrelated to any of those log messages. I updated `Common.log` to write to a file instead of stdout, and then I could determine exactly how far OnionShare gets before it dies, and I narrowed it down to [this line](https://github.com/micahflee/onionshare/blob/develop/onionshare/settings.py#L114) of code:

```python
default_locale = locale.getdefaultlocale()[0][:2]
```

I discovered that when I double-click an app bundle in Finder, `locale.getdefaultlocale()` returns `(None, None)`, but when I run the same app bundle from a terminal, it returns `('en_US', 'UTF-8')`. I'm about to confirm if this is the problem...

**Comment by cmarin-cs** [comment]
Had the same issue:
```Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." ...  NSUnderlyingError= ... {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}```

Fixed doing:
`sudo spctl --master-disable`

**Comment by BenLeggiero** [comment]
I had this same issue with my own app. I solved it by sending it through the Apple signing process again.
