### ISSUE TITLE
When a file is still being received and the timer hits zero, the Timer will start to go into the negatives.

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#852]
When a file is still being received and the timer hits zero, the Timer will start to go into the negatives.5
Here is a video showing the issue.
[issue.mov.zip](https://github.com/micahflee/onionshare/files/2697194/issue.mov.zip)
![screen shot 2018-12-19 at 6 34 23 pm](https://user-images.githubusercontent.com/10781882/50260403-ba8c4280-03bc-11e9-9da5-aac998db4de2.png)

**Comment by mig5** [comment]
Is it a bug? I kind of like this, it tells me how long the service has continued run after it was meant to time out.

(It's by design that it does not stop, it keeps going til the in-progress download finishes)
