### ISSUE TITLE
Homebrew install?

### ISSUE THREAD

**Issue by alichtman** [micahflee/onionshare#863]
It would be awesome if this could be installed with something like: `brew cask install onionshare`

Is this possible?

**Comment by pahakalle** [comment]
that is how you install it on mac

**Comment by micahflee** [comment]
At the moment you can install it for Mac by downloading and installing the `.pkg`from either https://github.com/micahflee/onionshare/releases or https://onionshare.org/. But it would be cool to install OnionShare via homebrew. I'll look into it and see how feasible it is, especially with a codesigned app bundle with the sandbox enabled. If it seems like this is doable with homebrew I'd totally be into publishing it there too.

**Comment by pahakalle** [comment]
You can install onionshare with homebrew by running `brew cask install onionshare`

**Comment by pahakalle** [comment]
i even just update it to install the lates version

**Comment by micahflee** [comment]
Oh wow, thanks @pahakalle I had no idea. I just checked out https://github.com/Homebrew/homebrew-cask/blob/master/Casks/onionshare.rb and it seems to work great.

You're the one who keeps the homebrew cask up-to-date? Would you be interested in joining the onionshare keybase team or mailing list? https://github.com/micahflee/onionshare/wiki/Developing-OnionShare#developer-and-designer-collaboration

**Comment by pahakalle** [comment]
@micahflee anyone using homebrew can update it. I just did the latest version bump for it

**Comment by pahakalle** [comment]
@micahflee if someone has a mac they can update it with the code bellow when a never version is released on github and after someone from homebrew-cask does a merges it will be available for everyone.

``` Bash
# install and setup script - only needed once
brew install vitorgalvao/tiny-scripts/cask-repair
cask-repair --help

# use to update <outdated_cask>
cask-repair <outdated_cask>
```

**Comment by pahakalle** [comment]
@micahflee i also joined the mailing list but i also watch this repo so i see notification on new releases and i can keep the cask up to date.
