### ISSUE TITLE
When the onionshare window is too small, the widgets stack on top of each other

### ISSUE THREAD

**Issue by heartsucker** [micahflee/onionshare#877]
On develop at 6af9a8a

![screenshot_2019-01-22_09-21-29](https://user-images.githubusercontent.com/3998464/51521589-4dd6ee80-1e27-11e9-9222-3df6f1a1ba58.png)

This may be an xmonad problem, but I doubt it.

**Comment by micahflee** [comment]
We tried to get around that by setting a minimum window height. Like on macOS, you simply can't resize the window to be that short, and it kinda solves the problem. But I think xmonad is resizing the window to be smaller than the minimum height.

Can you try on a non-tiling WM and see if you can reproduce the problem there? I don't seem to be able to. I'd like to support tiling window managers too in any case, but it's a bit lower priority than everything else, and debugging Qt5 display issues like this is annoying.

**Comment by heartsucker** [comment]
Ah yeah, you're right. If I kill xmonad, I can't do it.
