### ISSUE TITLE
Localizing CLI strings?

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#879]
I got feedback from the person who's translating OnionShare to Russian that maybe we shouldn't localize the command line strings, and instead keep them in English. They said that it's very odd for command line tools to not be in English (that most Russian sysadmins and programmers who use the CLI a lot use it all in English), and that it looks weird to have the OnionShare CLI in Russia. They suggest we keep the CLI in English, but localize the GUI in Russian.

It seems like the options are:

1. Translate all strings, including CLI strings
2. Keep CLI strings in English, and only translate GUI strings
3. Keep CLI strings in English only for the Russian language, and translate all strings for all other languages

@emmapeel2 and anyone else knowledgeable about localization issues, what do you think?

**Comment by emmapeel2** [comment]
Yeah, most of the projects do not translate the cli strings... sometimes the cli strings have more documentation, it depends on the project. The Debian Installer is translated (is ncurses tho) but is a user facing interface...

My personal view about this case is: I feel the CLI usage of OnionShare will be for advanced users, and  unfortunately, nowadays to be computer literate you need to speak Englis, so maybe this translation is not needed.

I would not stop adding a translation for a lack of this strings, but it may make sense to translate them to some languages.  I can lower its translation priority or write a note about that.

**Comment by micahflee** [comment]
At the moment, the CLI and GUI share a few strings. But it would be easy to make the CLI English-only just by directly including English like:

```
print("{0:s} is not a readable file.".format(filename))
```

Instead of calling `strings._()` which we currently do:

```
print(strings._("not_a_readable_file").format(filename))
```

We already do this for the web UI, because we intentionally keep that in English to avoid leaking the OnionShare user's locale. @emmapeel2 do you think this would be a worthwhile thing to do, go through the CLI version and remove all of the translations so it's only in English?

**Comment by shaymcmillan** [comment]
@micahflee guess who's here.

**Comment by mig5** [comment]
I am happy to hit this, which will actually unblock #943.

But I don't want to start on it yet, because there are a few PRs that add some more strings to the CLI stuff.. (startup timer). I think I'd rather see those merged in first, to avoid conflicts later.
