### ISSUE TITLE
OnionShare share and receive mode pages should be responsive/mobile-first

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#886]
I just looked at OnionShare share and receive mode pages in Tor Browser for Android, and while both work great, neither use responsive design, so it's like viewing a desktop-only website on your phone. We should redesign these pages to support mobile browsers.

**Comment by ninavizz** [comment]
Do ping if you'd like some help with this.

**Comment by 4jNsY6fCVqZv** [comment]
Would libhandy work here? https://gitlab.gnome.org/GNOME/libhandy/
