### ISSUE TITLE
If I click Clear all when receiving a file, the current transfer is hidden even though the transfer is still occurring

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#887]
If a user chooses to 'clear all', it should only clear the transfer history once the file transfer has completed. Onionshare 2.0

1. Start receive mode, from Torbrowser send a file 10MB +.
2. While the file is being received, click 'Clear all' in the GUI and the file transfer is hidden.

Video showing the issue.
[bug.mov.zip](https://github.com/micahflee/onionshare/files/2805947/bug.mov.zip)

**Comment by mig5** [comment]
Fixed in #902
