### ISSUE TITLE
Finish translating for 2.0 release

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#889]
We need to choose which languages OnionShare 2.0 will ship with, and get all of those languages to 100% [in weblate](https://hosted.weblate.org/projects/onionshare/translations/).

When that's complete, we need to merge those locale files in, and edit `self.available_locales` in `onionshare/settings.py` to only include that specific list of languages.

Based on how close we are, I'd say we should aim for these languages:

- Chinese (Simplified)
- Danish
- Dutch
- French
- German
- Greek
- Irish
- Italian
- Japanese
- Norwegian
- Persian
- Portuguese (Brazil)
- Russian
- Spanish
- Swedish

What do you think @emmapeel2?

**Comment by emmapeel2** [comment]
I am making another call, I hope we manage to finish them!

**Comment by micahflee** [comment]
Hey @emmapeel2, it looks like several of the languages are already at 100% and several are really close. What do you think about trying to finish up in the next few days, and aim to release OnionShare 2.0 on this coming Sunday?

I can include all languages that are >95% complete in the release.

**Comment by emmapeel2** [comment]
Yes! I will try and ping more translators

**Comment by emmapeel2** [comment]
OK, right now, the languages at 95% or more are:

Bengali 	- বাংলা
Catalan 	- Català
Danish 		- Dansk
French 		- Français
Greek 		- Ελληνικά
Italian 	- Italiano
Japanese 	- 日本語
Russian 	- Русский
Spanish 	- Español
Persian 	- فارسی
Swedish 	- Svenska
Portuguese (Brazil) - Português (Brasil)



(Only Persian is Right to Left....)

**Comment by micahflee** [comment]
Sooo awesome

![screenshot from 2019-02-10 10-41-43](https://user-images.githubusercontent.com/156128/52537880-78c6ab00-2d20-11e9-98fa-15e58e737e43.png)
