### ISSUE TITLE
Checking 'Use legacy address' causes the options below to be covered

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#892]
1. Check 'Use legacy address'  and the bug occurs.
![screen shot 2019-01-29 at 11 10 29 pm](https://user-images.githubusercontent.com/10781882/51964349-1960c500-241b-11e9-8e5a-9bedff9d8b96.png)

**Comment by mig5** [comment]
This doesn't seem to occur now - probably since we moved Persistent Addresses out of 'Legacy Mode only'.

It could still occur in future if we add more settings, but for now it doesn't seem an issue.

**Comment by Baccount** [comment]
@mig5 The bug no longer occurs on the latest branch `899_send_files_ajax`
