### ISSUE TITLE
onionshare crashs in xbuntu 18.04 

### ISSUE THREAD

**Issue by lkthawaii** [micahflee/onionshare#894]
i only get a responding notice asking to cancel or retry and it keeps repeating when i retry tried removing/reinstalling from software center and in terminal works in windows10

**Comment by micahflee** [comment]
Can you open a terminal and run:

```sh
onionshare-gui --debug
```

And then try again, and when it crashes paste the output from the terminal here?

**Comment by lkthawaii** [comment]
this is what terminal says;
Traceback (most recent call last):
  File "/usr/bin/onionshare-gui", line 21, in <module>
    import onionshare_gui
  File "/usr/lib/python3/dist-packages/onionshare_gui/__init__.py", line 22, in <module>
    from .alert import Alert
  File "/usr/lib/python3/dist-packages/onionshare_gui/alert.py", line 22, in <module>
    from onionshare import common
  File "/usr/lib/python3/dist-packages/onionshare/__init__.py", line 24, in <module>
    from .onion import *
  File "/usr/lib/python3/dist-packages/onionshare/onion.py", line 21, in <module>
    from stem.control import Controller
  File "/usr/lib/python3/dist-packages/stem/control.py", line 265, in <module>
    import stem.descriptor.microdescriptor
  File "/usr/lib/python3/dist-packages/stem/descriptor/__init__.py", line 55, in <module>
    import stem.util.system
  File "/usr/lib/python3/dist-packages/stem/util/system.py", line 70, in <module>
    import distutils.spawn
ModuleNotFoundError: No module named 'distutils.spawn'

this is what happens when i try to run onionshare nothing no notice nada.
Hi from lance.
________________________________

**Comment by micahflee** [comment]
Hmm, do you know what version of OnionShare you have installed? Did you install it directly from Ubuntu's repos, or from my PPA?

**Comment by lkthawaii** [comment]
i think this computer has this one

Hi from lance.
________________________________

**Comment by lkthawaii** [comment]
Hello Micah,

what other info or other thing you can think of for me to try

Hi from lance.
________________________________

**Comment by lkthawaii** [comment]
hello micah is anyone still there last heard from you on the 11th i think
Hi from lance.
________________________________

**Comment by micahflee** [comment]
I can't reproduce. I just installed a Xubuntu 18.04 VM, and then installed OnionShare from the PPA like this:

```sh
sudo add-apt-repository ppa:micahflee/ppa
sudo apt install -y onionshare
```

And then ran it, and it works fine without crashing:

![Screen Shot 2019-03-26 at 10 07 38 AM](https://user-images.githubusercontent.com/156128/55018014-38a94800-4faf-11e9-98f5-beb1efb6bb6b.png)

Make sure you install OnionShare from the PPA and it should work. (If there's some other problem though feel free to re-open this issue.)

**Comment by lkthawaii** [comment]
ok micah
will have to wait not home now. let you know how it goes when i get home

Hi from lance.
________________________________
