### ISSUE TITLE
In receive mode, when Tor Browser user cancels an upload, the History widget should show it as canceled

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#903]
Right now, the history widget just says that item was "Transferred", but doesn't show the open file manager button.

**Comment by mig5** [comment]
I couldn't figure this one out. It seems we have all this logic for handling a 'canceled' event, but it is somehow instead being handled as a 'finished' event.

**Comment by mig5** [comment]
If I 'cancel' an upload from the browser (e.g close the tab mid-upload), this bit of code in the `ReceiveModeRequest.close()` function always evaluates to false:

```
                if not self.web.stop_q.empty():
                    # Inform the GUI that the upload has canceled
                    self.web.add_request(self.web.REQUEST_UPLOAD_CANCELED, self.path, {
                        'id': upload_id
                    })
                else:
                    # Inform the GUI that the upload has finished
                    self.web.add_request(self.web.REQUEST_UPLOAD_FINISHED, self.path, {
                        'id': upload_id
                    })
```

The 'canceled' logic never fires. Makes sense, as the app doesn't add anything to your `stop_q` Queue when the browser does something like that.
