### ISSUE TITLE
Messaging + Page Ordering

### ISSUE THREAD

**Issue by ninavizz** [micahflee/onionshare#916]
Howdy! I worked on SecureDrop's NoScript workaround, and just saw screenshots of Onionshare's similar workaround. Very different users, so totally dig the general differences—however I did observe one very general ux best practice for the entire product (that I see many FOSS projects do wrong) that I wanted to recommend a change to. I don't code, so I'm just sharing modified screenshots here—on the chance that someone who does code, might take an interest in this. 

User messaging—task progress, success, warnings, or failures—should always be shown at the top of the user's screen, or shown in a visually connected/contained fashion when shown below content. 

**Like this:** 
![image](https://user-images.githubusercontent.com/8262612/53276656-e83f8180-36b4-11e9-88e8-d45a7a2a319f.png)

**...so current activity, error or success messaging, etc., all go here:**
![image](https://user-images.githubusercontent.com/8262612/53276756-63a13300-36b5-11e9-9d93-08b7b1946fa8.png)

**...or alternately, placed here**
![image](https://user-images.githubusercontent.com/8262612/53276686-04dbb980-36b5-11e9-84a3-676d62a90881.png)

**...and all follow the center-alignment of the rest of the page's content, to more naturally guide users to follow the page's hierarchy.**

When contextual messaging is shown below a page object where the user made an error, the messaging needs to pertain to just that one object (which, yes, in Onionshare, is only one thing, anyway). User mental models have been trained to expect the messaging to be paired directly to the functional widget, not the total contents of a page—so that'd be below the "Browse" button w/ adjacent selected file named, but above the page's primary action button to "Send Files."  

The pattern also has the specific object's color changing to match the text of the message—or some other visual device connecting the two objects. Example: you enter the digits for phone number without dashes, but the form needs dashes... so the message stating your error shows in red, below the text field, with the text field's border also changed to red (or have a red outer-glow).  Even on a single-item form, a message sitting below the top of the page still needs to paired just below the widget a user performed an action against, or they'll miss it. 

I appreciate these details may seem fussy, but the patterns have been tested exhaustively—and users who are not deeply-curious, self-starting hacker types, need visual cues and page hierarchies to be clear, or they overlook things that may seem obvious to the rest of us. Today's users just aren't trained to look for messaging below a page form's primary action buttons. That used to be a standard, but it's been moved away from as user research has come to influence page design more and more.

**Comment by mig5** [comment]
Thank you so much for this advice @ninavizz ! It totally makes sense. This is great.

I've just made a PR #917 that hopefully solves this, but @micahflee might want to tweak it some more.

Here's a screenshot example of what the change looks like in at least the ajax mode:

![onionshare-progress-above-send](https://user-images.githubusercontent.com/99173/53280383-855df100-376d-11e9-9ccc-f3a3f114ca5b.png)

Interestingly it seems to look better in responsive mode too.. but I didn't test on an actual mobile device.

**Comment by ninavizz** [comment]
@mig5 Wow, hooray!! :)

I'm curious, though—in the last screenshot, it appears that **_both_** an error and a success message are being shown to the user... is that correct?

If the red message is not in fact a returned-error message but instead just an FYI/warning that is persistently displayed, it should be handled differently. If it's an FYI/Warning that only shows after a user has uploaded something, I don't really see the point in that (eg: it's confusing, and letting them know post-mortem of something that could have but did not happen).

I cannot install onionshare on my machine (abt to create a separate issue for that) so cannot look at how it's currently configured. Happy to make a recco for the warning, if in fact it is a persistent FYI.

**Comment by ninavizz** [comment]
I'd recommend this, for a persistent FYI message.
- "Red" signifies a user or system error; a "you need to fix this" or "shit's not working" message.
- Pink is bright, and this one is on the same hue spectrum as Tor's Purple
  - Hex: `#d709df`
  - A more coral-y alternative: `#d82188`
  - An orange-y alternative: `#d67629`
- The icon is not an error-bang, so appropriately will not signify "FIX THIS!" or "Danger!" but imho does nicely signify "Yo, yo!!" or "Yoohoo!"

![image](https://user-images.githubusercontent.com/8262612/53291931-c1925100-376f-11e9-8cf5-3f88cb7e58b0.png)


Icon SVG: `<?xml version="1.0" encoding="UTF-8"?>
<svg width="325px" height="213px" viewBox="0 0 325 213" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    
    <title>Fill 1</title>
    <desc>Created with Sketch.</desc>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <path d="M62.864,111.653 L91.886,39.767 C93.839,34.888 99.374,32.518 104.249,34.473 C109.119,36.424 111.496,41.965 109.541,46.843 L93.83,86.5 C93.83,86.5 92.708,89.255 95.364,90.32 C98.076,91.407 99.109,88.616 99.109,88.616 L122.001,31.502 C123.955,26.627 129.381,24.41 134.254,26.363 C139.132,28.319 141.088,33.494 139.134,38.369 L116.242,95.481 C116.242,95.481 115.421,98.392 118.044,99.443 C120.641,100.484 121.957,97.771 121.957,97.771 L148.665,31.141 C150.618,26.268 155.775,24.039 160.65,25.993 C165.526,27.947 167.745,33.133 165.792,38.006 L139.085,104.636 C139.085,104.636 138.148,107.362 140.955,108.487 C143.714,109.592 144.798,106.926 144.798,106.926 L164.638,57.429 C166.592,52.553 171.634,51.027 176.507,52.98 C181.385,54.935 183.728,59.422 181.774,64.297 L152.778,136.637 C152.778,136.637 151.966,140.046 158.705,136.582 C175.983,127.715 183.235,127.482 183.235,127.482 C183.235,127.482 196.66,126.483 197.652,138.4 C198.368,147.042 194.399,145.9 184.966,152.378 C176.619,158.117 151.891,172.097 151.891,172.097 C151.891,172.097 121.294,191.835 94.92,181.263 C94.92,181.263 42.378,162.76 62.864,111.653 Z M270.905,152.632 L270.905,28.8 C270.905,12.96 257.946,0 242.106,0 L28.8,0 C12.96,0 0,12.96 0,28.8 L0,182.478 C0,198.318 12.96,211.278 28.8,211.278 L231.808,211.278 L242.106,211.278 L325.04,212.782 L270.905,152.632 Z" id="Fill-1" fill="#231F20"></path>
    </g>
</svg>`

**Comment by mig5** [comment]
Thank you again @ninavizz , yes it's a permanent warning when javascript is not enabled (at least, until this Firefox bug is fixed!). 

Your recommendation is much better. I've pushed the change to my PR but being less than a novice at frontend I'm not confident in the correctness of my implementation, but it might help @micahflee get it over the line.

![screenshot_2019-02-24_10-19-24](https://user-images.githubusercontent.com/99173/53292879-d88f7c80-381d-11e9-874b-f5296b64474f.png)

Thanks again for your help - one always has the faint suspicion that 'this could be better somehow', but it takes an expert to both see and explain how it should be.

**Comment by micahflee** [comment]
This is awesome, thanks for the feedback @ninavizz and for implementing it @mig5. I'm just now reviewing your PR.
