### ISSUE TITLE
Add "receive mode" docs to github wiki documentation

### ISSUE THREAD

**Issue by benlk** [micahflee/onionshare#938]
This is a feature request.

Please document the receive mode in the wiki https://github.com/micahflee/onionshare/wiki in a way that can be found with the wiki's search, the page list index, or the main page of that wiki.

**Comment by mig5** [comment]
Thanks for the reminder. I made a start here: https://github.com/micahflee/onionshare/wiki/Receive-Mode (and it is linked in the sidebar).

Contributions (perhaps some screenshots?) welcome!
