### ISSUE TITLE
ImportError: No module named queue

### ISSUE THREAD

**Issue by Throwaway684736** [micahflee/onionshare#944]
Onionshare 1.3 worked flawlessly...

Decided to try 2.0 on my Raspbian, did "python setup.py install"
Success.

But running onionshare gives me the usual:

ImportError: No module named queue

Just in case it's too buggy, does anyone still have 1.3 to rollback to? Thanks!

**Comment by Throwaway684736** [comment]
Btw, is there any uninstaller? Or how to manually remove the leftovers and reinstall ?

**Comment by pahakalle** [comment]
did you run python setup.py install with python2 or 3?

**Comment by mig5** [comment]
> Decided to try 2.0 on my Raspbian, did "python setup.py install"

None of the documentation instructs to install OnionShare in this way.

I recommend to follow the BUILD.md documentation as per the comment above, which lists all the dependencies you need to install with apt. It even includes making a .deb that you can install (but you don't have to).
 
> Just in case it's too buggy, does anyone still have 1.3 to rollback to? Thanks!

https://github.com/micahflee/onionshare/releases/tag/v1.3.1
