### ISSUE TITLE
Where do uploaded files go?

### ISSUE THREAD

**Issue by Throwaway684736** [micahflee/onionshare#947]
Ran a test of 2.0
Uploaded a file to myself
Checked the whole ./onionshare with subdirs. Cant find it anywhere.

Hmm?

**Comment by mig5** [comment]
By default, they go into a directory called 'OnionShare' in your home directory (note the case sensitivity if not on windows). You can change the location in the OnionShare settings.

**Comment by Throwaway684736** [comment]
Indeed! Thanks!
