### ISSUE TITLE
No package for Ubuntu 14

### ISSUE THREAD

**Issue by Throwaway684736** [micahflee/onionshare#948]
I have an Ubuntu 14 box... Tried today:
=========================================================
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-147-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
root@x:~# add-apt-repository ppa:micahflee/ppa
 This is where I release my Ubuntu software, including Tor Browser Launcher, OnionShare, and PDF Redact Tools.
 More info: https://launchpad.net/~micahflee/+archive/ubuntu/ppa
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmpb03smpd9/secring.gpg' created
gpg: keyring `/tmp/tmpb03smpd9/pubring.gpg' created
gpg: requesting key 7D158F33 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpb03smpd9/trustdb.gpg: trustdb created
gpg: key 7D158F33: public key "Launchpad PPA for Micah Lee" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
root@x:~# apt update
.....
OK

root@x:~# apt install onionshare
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package onionshare

==============================================================

What am I doing wrong? Thanks!

**Comment by danmcne** [comment]
Won't install on Ubuntu 16.04 LTS due to a dependency for python3 either. Seems like this software should be focused on being compatible with somewhat older hardware/OSs --- especially Ubuntu LTS releases still within their 5 years of support.

**Comment by pahakalle** [comment]
@danmcne take a look at https://github.com/micahflee/onionshare/wiki/Linux-Distribution-Support#ubuntu-1404-lts-trusty

**Comment by danmcne** [comment]
@pahakalle: The point is that having an "easy" anonymous file drop service shouldn't require building from source for Ubuntu 16.04 LTS (or perhaps even 14) --- they should simply be available for download or via apt/apt-get.

**Comment by pahakalle** [comment]
@micahflee do you know who maintaints the ubuntu repostitories, they seem to be a bit behind?

**Comment by mig5** [comment]
I am going to close this since Ubuntu 14.04 is EOL next week.

The issue of 16.04 will be addressed in the next OnionShare release now that #960 was merged.
