### ISSUE TITLE
Option to add custom string to URL

### ISSUE THREAD

**Issue by amun1** [micahflee/onionshare#952]
First of all, congratulations on this great piece of software.

I've been following its progress for a while now but I haven't actually used OnionShare because of https://github.com/micahflee/onionshare/wiki/Security-Design > What it doesn't protect against > Communicating the OnionShare URL might not be secure.

I think however that with a minimum of code change (I know that's easy for me to say) protection could be enhanced by giving the user the option to expand the slug with a custom string.

If the user would have this option then the custom string would only have to be exchanged ONCE in a secure manner for all future communication via OnionShare to be secure and http://[onionservice].onion/[slug], without the custom string of course, would no longer have to be exchanged in a secure manner.

With a voice call it would be much easier to exchange the custom string once than having to exchange http://[onionservice].onion/[slug] each and every time.

The custom string could even be exchanged via snail mail.

With the current version of the software you could also exchange http://[onionservice].onion/[slug] via snail mail but you would have to keep OnionShare running (because of the two randomly generated words in the slug) until the snail mail reached its destination.

I don't know if repetitive use of the same custom string would make users fingerprintable so the procedure described below which makes use of different custom strings for each communication might be overkill.

The way that all future communication via OnionShare would be secure is by, after exchanging http://[onionservice].onion/[slug] insecurely and reminding your contact to add the custom string, using the first communication via OnionShare to send a different second custom string you'll be using for your second communication via OnionShare.

So for the second communication via OnionShare you can again exchange http://[onionservice].onion/[slug] insecurely, remind your contact to add the different second custom string received in the first communication via OnionShare and add a different third custom string and so on.

A probably easier and less error-prone way would be to send not one different custom string but a numbered list of different custom strings so next time you can exchange http://[onionservice].onion/[slug] and a list number insecurely which would automatically remind your contact to add the custom string that corresponds to that list number.

You could even send the exact same list to all your contacts and still be able to communicate with just one or a few of them without the others being able to get to the files you're sharing as long as you don't exchange http://[onionservice].onion/[slug] with them.

It's just my two cents but unless I haven't thought things through I think it would add even more value to OnionShare.

**Comment by Baccount** [comment]
V3 onion addresses are protected Against a malicious hidden service, so that slugs are not needed for the V3 'very long' addresses.
2.5.1. First layer of encryption [HS-DESC-FIRST-LAYER]
The first layer of HS descriptor encryption is designed to protect
descriptor confidentiality against entities who don't know the blinded
public key of the hidden service.

Here is the design document for Tor's next generation onion service.
https://gitweb.torproject.org/torspec.git/tree/proposals/224-rend-spec-ng.txt

**Comment by amun1** [comment]
@Baccount

I changed the original title (Option to expand the slug) because it feels like your comment is based on the presence of the word slug in the title and not so much on what I wrote.

Like I said before this relates to https://github.com/micahflee/onionshare/wiki/Security-Design > What it doesn't protect against > Communicating the OnionShare URL might not be secure:
> The sender is responsible for securely communicating the OnionShare URL with the recipient. If they send it insecurely (such as through an e-mail message, and their e-mail is being monitored by an attacker), the eavesdropper will learn that they're sending files with OnionShare. If the attacker loads the URL in Tor Browser before the legitimate recipient gets to it, they can download the files being shared.

The fact that v3 addresses are protected against a malicious hidden service directory has got nothing to do with protection against eavesdroppers.

Please (re)read my first post before reading the rest of this post.

Besides, I bet some people are still using v2 addresses because you can't use stealth mode with v3 addresses (yet).
Stealth mode isn't really practical unless you're using a persistent URL because only then HidServAuth would remain the same.
In v2 stealth mode with a persistent URL you'll be able to communicate with just one or a few of your contacts without the others being able to get to the files you're sharing as long as you don't exchange [slug] with them and that exchange can be done insecurely if you have the option to use a custom string that only your contacts (and not the eavesdroppers) know about.

In my first post I didn't take a persistent URL into account because of the risk of de-anonymization when using it over a prolonged period of time but different people have different use cases.
The thing is however that no matter what the use case is OnionShare would only have to provide an option to add a custom string while the actual heavy lifting to take advantage of it would have to be done by the users.

And just to clarify what I have in mind:
v2: http://[onionservice].onion/[slug][customstring]
v3: http://[onionservice].onion/[customstring]

**Comment by micahflee** [comment]
The issue I see is that it doesn't actually solve the "Communicating the OnionShare URL might not be secure" problem -- phone calls and snail mail are both insecure communication channels. It just adds complexity.

If you're ok with using these channels for _part_ of the OnionShare URL, you can do that already without changing any code. Just send the `http://[onionservice].onion` part in an email (or whatever), and share the `/[slug]` part in a phone call. Then the attacker would have to be monitoring _both_ your email and your phone calls to intercept the URL.

However, I think the better and more usable way to use OnionShare is to first set up a secure communication channel with the person you're sharing files with, and use that channel to send the full URL. There are many easy-to-use ways to send encrypted and authenticated messages that would work great for this: Signal, Keybase, Wire, iMessage, even jabber/OTR or PGP (which are a bit harder to use).

**Comment by amun1** [comment]
@micahflee

I never claimed that my suggestion solves the "Communicating the OnionShare URL might not be secure" problem but only wrote that it **relates to** that because my suggestion would simplify things by only requiring a secure communication channel once instead of each and every time.

I never used the words phone call but wrote voice call (meaning encrypted) and snail mail is indeed not safe but there are ways to detect if it's been tampered with so you know you'll have to use a different communication channel.

I only used the voice call example to point out that it isn't easy to exchange a long url each and every time in a voice call compared to exchanging the custom string once in a voice call.

I only used the snail mail example to point out that with the current version of the software you would have to keep OnionShare running (because of the two randomly generated words in the slug) until the snail mail reached its destination (and was checked for tampering).

I don't see how either of those two would add any complexity at all especially since they would only have to be used once.

What certainly looks complex to me is

> ...you can do that already...Just send the http://[onionservice].onion part in an email (or whatever), and share the /[slug] part in a phone call.

especially since you would have to keep doing that each and every time.

> I think the better and more usable way to use OnionShare is to first set up a secure communication channel with the person you're sharing files with, and use that channel to send the full URL.

Certainly not compared to a one-time secure exchange of a custom string followed by never needing to use any secure communication channel ever again for all future exchanges.

> There are many easy-to-use ways to send encrypted and authenticated messages that would work great for this: Signal, Keybase, Wire, iMessage, even jabber/OTR or PGP (which are a bit harder to use).

All those methods fall short when it comes to anonymity (leaking metadata, vulnerable to timing and statistical attacks,... and that each and every time you use them) which is exactly the point of using OnionShare in the first place.

**<ins>If</ins>** the following conditions would be met:

1) repetitive use of the same custom string would not make users fingerprintable (eliminating the "overkill" in my first post)

2) [slug] would be available for v3 addresses (eliminating the "fall back to" in my second post)

but you would still think that

1) exchanging a custom string securely once and never needing a secure communication channel ever again for all future exchanges

2) plus the other advantages depending on the different use cases which I'm not going to repeat

don't add any value whatsoever to OnionShare then the only thing left to do is agree to disagree.

**Comment by micahflee** [comment]
So it looks like the feature you're looking for is to be able to securely exchange a secret once, and then never needing to communicate again because the person on the Tor Browser side can regularly check a known URL.

Have you tried the "Use a persistent address" option in the settings? I think this does what you're looking for. You use a persistent address and start sharing something, and it shows you the URL. You then communicate that URL securely to the Tor Browser user. Now until you uncheck that box, every time you start an OnionShare server, it will have the same URL.
