### ISSUE TITLE
Add "static websites" documentation

### ISSUE THREAD

**Issue by holantonela** [micahflee/onionshare#988]
Hiro and I we drafted some docs for #961. Please, feel free to review. We will publish it at the wiki after the release.

-----

**Publish Website**
In the OnionShare main interface, beginning with version 2.2, you can create your .onion website with one click.
 
**What is Publish Website?**
OnionShare allows you to publish a website via onion service very quickly. When you add an index.html file, OnionShare creates a web service and make it available on the Tor network.
Onion websites are an excellent way to offer to your users secure browsing experience. If you want to learn more about how Onion services work, go [here https://2019.www.torproject.org/docs/onion-services.html.en].
If you don't have an index.html, OnionShare will show a directory listing. In directory listing, each file can be opened, and there is no download button for the compressed archive, but a single download link for each file.

**.onion Website Settings**
By default, your new .onion website will use the General Settings. If your Public mode is not enabled, a random user/password pair will be assigned.

**Things you should know**
Remember that your web service is using your local computer as a server. If you Stop sharing, the website will disappear. Like a drop into that river, when they find the sea.

**Comment by mig5** [comment]
Thanks! I published a variant of this in the wiki now that 2.2 has been released.

**Comment by mig5** [comment]
https://github.com/micahflee/onionshare/wiki/Website-Mode
